// ═══════════════════════════════════════════════════════════════════════════════
// Template: Case Study
// Perfect for showcasing results and success stories - Enhanced
// ═══════════════════════════════════════════════════════════════════════════════

import type { CarouselTemplate } from "../carousel-designer-types"
import { VIBRANT_PALETTES } from "../carousel-designer-types"
import { generateSlideId, createTextElement, createShapeElement } from "./template-helpers"

export const caseStudyTemplate: CarouselTemplate = {
  id: "case-study",
  name: "Case Study",
  description: "Showcase results and success stories with this professional case study format.",
  category: "case-study",
  isPremium: false,
  isCustom: false,
  palette: VIBRANT_PALETTES.find((p) => p.id === "sunset-glow")!,
  size: "portrait",
  defaultFonts: {
    heading: "'Inter', sans-serif",
    body: "'Inter', sans-serif",
  },
  tags: ["case-study", "results", "success", "professional"],
  createdAt: Date.now(),
  updatedAt: Date.now(),
  slides: [
    {
      id: generateSlideId(),
      name: "Cover",
      order: 0,
      background: { type: "solid", color: "#FFFFFF" },
      elements: [
        createShapeElement("rectangle", 0, 0, 1080, 550, "#EA580C"),
        createTextElement(
          "CASE STUDY",
          60,
          180,
          200,
          35,
          { fontSize: 13, fontWeight: 600, letterSpacing: 4, color: "#FFFFFF", textTransform: "uppercase" },
          "text",
        ),
        createTextElement(
          "How [Client]\nAchieved [Result]",
          60,
          640,
          960,
          220,
          { fontSize: 52, fontWeight: 800, lineHeight: 1.2, color: "#1C1917" },
          "heading",
        ),
        createTextElement(
          "A detailed breakdown of the strategy and results",
          60,
          900,
          960,
          50,
          { fontSize: 22, fontWeight: 400, color: "#78350F" },
          "subheading",
        ),
        createShapeElement("rounded-rectangle", 60, 1100, 180, 50, "#EA580C", { borderRadius: 8 }),
        createTextElement(
          "Read More",
          60,
          1112,
          180,
          30,
          { fontSize: 16, fontWeight: 600, textAlign: "center", color: "#FFFFFF" },
          "text",
        ),
      ],
    },

    {
      id: generateSlideId(),
      name: "The Challenge",
      order: 1,
      background: { type: "solid", color: "#FAFAF9" },
      elements: [
        createShapeElement("rectangle", 0, 0, 1080, 100, "#EA580C"),
        createTextElement(
          "THE CHALLENGE",
          60,
          35,
          400,
          35,
          { fontSize: 13, fontWeight: 600, letterSpacing: 4, color: "#FFFFFF", textTransform: "uppercase" },
          "text",
        ),
        createTextElement(
          "What was the problem?",
          60,
          230,
          960,
          60,
          { fontSize: 38, fontWeight: 700, color: "#1C1917" },
          "heading",
        ),
        createShapeElement("rounded-rectangle", 60, 330, 960, 320, "#FFFFFF", { borderRadius: 12 }),
        createTextElement(
          "Describe the specific challenge or problem that needed to be solved. Include relevant context, constraints, and what was at stake.",
          100,
          370,
          880,
          240,
          { fontSize: 22, fontWeight: 400, lineHeight: 1.7, color: "#1C1917" },
          "body",
        ),
        createTextElement(
          "Key Pain Points",
          60,
          710,
          400,
          40,
          { fontSize: 18, fontWeight: 600, color: "#EA580C" },
          "text",
        ),
        createTextElement(
          "• First pain point\n• Second pain point\n• Third pain point",
          80,
          770,
          920,
          150,
          { fontSize: 20, fontWeight: 400, lineHeight: 2, color: "#78350F" },
          "body",
        ),
      ],
    },

    {
      id: generateSlideId(),
      name: "The Solution",
      order: 2,
      background: { type: "solid", color: "#FFFFFF" },
      elements: [
        createShapeElement("rectangle", 0, 0, 1080, 100, "#F97316"),
        createTextElement(
          "THE SOLUTION",
          60,
          35,
          400,
          35,
          { fontSize: 13, fontWeight: 600, letterSpacing: 4, color: "#FFFFFF", textTransform: "uppercase" },
          "text",
        ),
        createTextElement(
          "Our Approach",
          60,
          230,
          960,
          60,
          { fontSize: 38, fontWeight: 700, color: "#1C1917" },
          "heading",
        ),
        createShapeElement("rounded-rectangle", 60, 330, 960, 200, "#FFF7ED", { borderRadius: 12 }),
        createTextElement(
          "STRATEGY 1",
          100,
          360,
          880,
          30,
          { fontSize: 16, fontWeight: 600, color: "#EA580C", letterSpacing: 2 },
          "text",
        ),
        createTextElement(
          "Explanation of first strategy and implementation",
          100,
          400,
          880,
          100,
          { fontSize: 20, fontWeight: 400, lineHeight: 1.6, color: "#1C1917" },
          "body",
        ),
        createShapeElement("rounded-rectangle", 60, 560, 960, 200, "#FFF7ED", { borderRadius: 12 }),
        createTextElement(
          "STRATEGY 2",
          100,
          590,
          880,
          30,
          { fontSize: 16, fontWeight: 600, color: "#EA580C", letterSpacing: 2 },
          "text",
        ),
        createTextElement(
          "Explanation of second strategy and implementation",
          100,
          630,
          880,
          100,
          { fontSize: 20, fontWeight: 400, lineHeight: 1.6, color: "#1C1917" },
          "body",
        ),
        createShapeElement("rounded-rectangle", 60, 790, 960, 200, "#FFF7ED", { borderRadius: 12 }),
        createTextElement(
          "STRATEGY 3",
          100,
          820,
          880,
          30,
          { fontSize: 16, fontWeight: 600, color: "#EA580C", letterSpacing: 2 },
          "text",
        ),
        createTextElement(
          "Explanation of third strategy and implementation",
          100,
          860,
          880,
          100,
          { fontSize: 20, fontWeight: 400, lineHeight: 1.6, color: "#1C1917" },
          "body",
        ),
      ],
    },

    {
      id: generateSlideId(),
      name: "Results",
      order: 3,
      background: {
        type: "gradient",
        gradient: { from: "#EA580C", to: "#F97316", direction: "to-br" },
      },
      elements: [
        createTextElement(
          "THE RESULTS",
          60,
          180,
          400,
          35,
          { fontSize: 13, fontWeight: 600, letterSpacing: 4, color: "#FFFFFF", textTransform: "uppercase" },
          "text",
        ),
        createTextElement(
          "Impact Delivered",
          60,
          260,
          960,
          60,
          { fontSize: 42, fontWeight: 700, color: "#FFFFFF" },
          "heading",
        ),
        createShapeElement("rounded-rectangle", 60, 400, 300, 200, "#FFFFFF", { borderRadius: 16 }),
        createTextElement(
          "+150%",
          60,
          440,
          300,
          80,
          { fontSize: 44, fontWeight: 800, textAlign: "center", color: "#EA580C" },
          "text",
        ),
        createTextElement(
          "Revenue Growth",
          60,
          530,
          300,
          40,
          { fontSize: 15, fontWeight: 500, textAlign: "center", color: "#78350F" },
          "text",
        ),
        createShapeElement("rounded-rectangle", 390, 400, 300, 200, "#FFFFFF", { borderRadius: 16 }),
        createTextElement(
          "50K+",
          390,
          440,
          300,
          80,
          { fontSize: 44, fontWeight: 800, textAlign: "center", color: "#EA580C" },
          "text",
        ),
        createTextElement(
          "New Customers",
          390,
          530,
          300,
          40,
          { fontSize: 15, fontWeight: 500, textAlign: "center", color: "#78350F" },
          "text",
        ),
        createShapeElement("rounded-rectangle", 720, 400, 300, 200, "#FFFFFF", { borderRadius: 16 }),
        createTextElement(
          "3x",
          720,
          440,
          300,
          80,
          { fontSize: 44, fontWeight: 800, textAlign: "center", color: "#EA580C" },
          "text",
        ),
        createTextElement(
          "ROI Achieved",
          720,
          530,
          300,
          40,
          { fontSize: 15, fontWeight: 500, textAlign: "center", color: "#78350F" },
          "text",
        ),
        createTextElement(
          '"This exceeded all our expectations. The results speak for themselves."',
          60,
          700,
          960,
          100,
          { fontSize: 22, fontWeight: 500, textAlign: "center", fontStyle: "italic", color: "#FFFFFF" },
          "quote",
        ),
        createTextElement(
          "Client Name, CEO",
          60,
          820,
          960,
          30,
          { fontSize: 16, fontWeight: 400, textAlign: "center", color: "#FED7AA" },
          "text",
        ),
      ],
    },

    {
      id: generateSlideId(),
      name: "Testimonial",
      order: 4,
      background: { type: "solid", color: "#FFF7ED" },
      elements: [
        createShapeElement("circle", 340, 200, 400, 400, "#FED7AA", { opacity: 0.4 }),
        createTextElement(
          "CLIENT FEEDBACK",
          60,
          300,
          960,
          40,
          { fontSize: 16, fontWeight: 600, textAlign: "center", color: "#EA580C", letterSpacing: 3 },
          "text",
        ),
        createShapeElement("line", 420, 370, 240, 3, "#EA580C"),
        createTextElement(
          "Working with this team was a game-changer for our business. They understood our challenges and delivered beyond expectations.",
          100,
          440,
          880,
          200,
          {
            fontSize: 26,
            fontWeight: 500,
            textAlign: "center",
            fontStyle: "italic",
            color: "#1C1917",
            lineHeight: 1.6,
          },
          "quote",
        ),
        createShapeElement("rounded-rectangle", 360, 720, 360, 120, "#FFFFFF", { borderRadius: 16 }),
        createTextElement(
          "John Smith",
          360,
          750,
          360,
          40,
          { fontSize: 24, fontWeight: 700, textAlign: "center", color: "#1C1917" },
          "text",
        ),
        createTextElement(
          "CEO, Company Name",
          360,
          795,
          360,
          30,
          { fontSize: 18, fontWeight: 400, textAlign: "center", color: "#78350F" },
          "text",
        ),
      ],
    },

    {
      id: generateSlideId(),
      name: "CTA",
      order: 5,
      background: { type: "solid", color: "#1C1917" },
      elements: [
        createShapeElement("circle", -100, 800, 400, 400, "#EA580C", { opacity: 0.2 }),
        createShapeElement("circle", 800, -100, 350, 350, "#F97316", { opacity: 0.15 }),
        createTextElement(
          "Ready for similar results?",
          60,
          450,
          960,
          70,
          { fontSize: 44, fontWeight: 700, textAlign: "center", color: "#FFFFFF" },
          "heading",
        ),
        createTextElement(
          "Let's discuss how we can help\nyour business grow.",
          60,
          560,
          960,
          100,
          { fontSize: 26, fontWeight: 400, textAlign: "center", color: "rgba(255,255,255,0.9)", lineHeight: 1.6 },
          "body",
        ),
        createShapeElement("rounded-rectangle", 290, 730, 500, 70, "#EA580C", { borderRadius: 35 }),
        createTextElement(
          "GET IN TOUCH",
          290,
          745,
          500,
          40,
          { fontSize: 22, fontWeight: 700, textAlign: "center", color: "#FFFFFF" },
          "text",
        ),
        createTextElement(
          "www.yourwebsite.com",
          60,
          900,
          960,
          30,
          { fontSize: 18, fontWeight: 500, textAlign: "center", color: "#FED7AA" },
          "text",
        ),
      ],
    },
  ],
}
