// Template: Data Story - Perfect for presenting statistics and research findings
import type { CarouselTemplate } from "../carousel-designer-types"
import { VIBRANT_PALETTES } from "../carousel-designer-types"
import { generateSlideId, createTextElement, createShapeElement } from "./template-helpers"

export const dataStoryTemplate: CarouselTemplate = {
  id: "data-story",
  name: "Data Story",
  description: "Present statistics and research findings in a compelling visual format.",
  category: "data-driven",
  isPremium: false,
  isCustom: false,
  palette: VIBRANT_PALETTES.find((p) => p.id === "tech-cyan")!,
  size: "portrait",
  defaultFonts: {
    heading: "'Inter', sans-serif",
    body: "'Inter', sans-serif",
  },
  tags: ["data", "statistics", "research", "analytics"],
  createdAt: Date.now(),
  updatedAt: Date.now(),
  slides: [
    {
      id: generateSlideId(),
      name: "Cover",
      order: 0,
      background: { type: "solid", color: "#0F172A" },
      elements: [
        createShapeElement("rectangle", 0, 1150, 1080, 200, "#00F5D4", { opacity: 0.08 }),
        createTextElement(
          "DATA INSIGHT",
          60,
          120,
          400,
          35,
          { fontSize: 13, fontWeight: 600, letterSpacing: 4, color: "#00F5D4", textTransform: "uppercase" },
          "text",
        ),
        createShapeElement("line", 60, 480, 80, 3, "#00F5D4"),
        createTextElement(
          "The Numbers Behind\n[Your Topic]",
          60,
          540,
          960,
          220,
          { fontSize: 52, fontWeight: 800, lineHeight: 1.2, color: "#FFFFFF" },
          "heading",
        ),
        createTextElement(
          "Key findings from our latest research",
          60,
          800,
          960,
          50,
          { fontSize: 22, fontWeight: 400, color: "#94A3B8" },
          "subheading",
        ),
        createTextElement(
          "@yourhandle",
          60,
          1260,
          960,
          30,
          { fontSize: 16, fontWeight: 500, color: "#64748B" },
          "text",
        ),
      ],
    },
    {
      id: generateSlideId(),
      name: "Key Stat",
      order: 1,
      background: {
        type: "gradient",
        gradient: { from: "#0F172A", to: "#1E293B", direction: "to-b" },
      },
      elements: [
        createTextElement(
          "3.5x",
          60,
          400,
          960,
          220,
          { fontSize: 160, fontWeight: 900, textAlign: "center", color: "#00F5D4" },
          "text",
        ),
        createTextElement(
          "More likely to succeed when you...",
          60,
          640,
          960,
          70,
          { fontSize: 30, fontWeight: 500, textAlign: "center", color: "#FFFFFF" },
          "text",
        ),
        createShapeElement("line", 390, 760, 300, 2, "#334155"),
        createTextElement(
          "[Your key action or finding here]",
          60,
          800,
          960,
          50,
          { fontSize: 20, fontWeight: 400, textAlign: "center", color: "#94A3B8" },
          "text",
        ),
      ],
    },
    {
      id: generateSlideId(),
      name: "Comparison",
      order: 2,
      background: { type: "solid", color: "#0F172A" },
      elements: [
        createTextElement(
          "BEFORE VS AFTER",
          60,
          80,
          400,
          35,
          { fontSize: 13, fontWeight: 600, letterSpacing: 4, color: "#8B5CF6", textTransform: "uppercase" },
          "text",
        ),
        createShapeElement("rounded-rectangle", 60, 180, 450, 350, "#1E293B", { borderRadius: 16 }),
        createTextElement(
          "BEFORE",
          100,
          220,
          370,
          35,
          { fontSize: 12, fontWeight: 600, letterSpacing: 3, color: "#EF4444" },
          "text",
        ),
        createTextElement("25%", 100, 300, 370, 120, { fontSize: 80, fontWeight: 800, color: "#FFFFFF" }, "text"),
        createTextElement(
          "Previous metric",
          100,
          440,
          370,
          30,
          { fontSize: 16, fontWeight: 400, color: "#94A3B8" },
          "text",
        ),
        createShapeElement("rounded-rectangle", 570, 180, 450, 350, "transparent", {
          borderRadius: 16,
          stroke: "#00F5D4",
          strokeWidth: 2,
        }),
        createTextElement(
          "AFTER",
          610,
          220,
          370,
          35,
          { fontSize: 12, fontWeight: 600, letterSpacing: 3, color: "#00F5D4" },
          "text",
        ),
        createTextElement("78%", 610, 300, 370, 120, { fontSize: 80, fontWeight: 800, color: "#FFFFFF" }, "text"),
        createTextElement("New metric", 610, 440, 370, 30, { fontSize: 16, fontWeight: 400, color: "#94A3B8" }, "text"),
        createTextElement(
          "+212% improvement",
          60,
          620,
          960,
          60,
          { fontSize: 32, fontWeight: 700, textAlign: "center", color: "#00F5D4" },
          "text",
        ),
      ],
    },
    {
      id: generateSlideId(),
      name: "Breakdown",
      order: 3,
      background: { type: "solid", color: "#0F172A" },
      elements: [
        createTextElement(
          "BREAKDOWN BY CATEGORY",
          60,
          80,
          600,
          35,
          { fontSize: 13, fontWeight: 600, letterSpacing: 4, color: "#00F5D4", textTransform: "uppercase" },
          "text",
        ),
        createShapeElement("rounded-rectangle", 60, 180, 920, 120, "#1E293B", { borderRadius: 12 }),
        createTextElement("Category A", 100, 210, 600, 30, { fontSize: 20, fontWeight: 600, color: "#FFFFFF" }, "text"),
        createShapeElement("rectangle", 100, 250, 700, 30, "#00F5D4", { borderRadius: 4 }),
        createTextElement("87%", 820, 250, 100, 30, { fontSize: 18, fontWeight: 700, color: "#00F5D4" }, "text"),
        createShapeElement("rounded-rectangle", 60, 330, 920, 120, "#1E293B", { borderRadius: 12 }),
        createTextElement("Category B", 100, 360, 600, 30, { fontSize: 20, fontWeight: 600, color: "#FFFFFF" }, "text"),
        createShapeElement("rectangle", 100, 400, 550, 30, "#8B5CF6", { borderRadius: 4 }),
        createTextElement("68%", 820, 400, 100, 30, { fontSize: 18, fontWeight: 700, color: "#8B5CF6" }, "text"),
        createShapeElement("rounded-rectangle", 60, 480, 920, 120, "#1E293B", { borderRadius: 12 }),
        createTextElement("Category C", 100, 510, 600, 30, { fontSize: 20, fontWeight: 600, color: "#FFFFFF" }, "text"),
        createShapeElement("rectangle", 100, 550, 400, 30, "#3B82F6", { borderRadius: 4 }),
        createTextElement("50%", 820, 550, 100, 30, { fontSize: 18, fontWeight: 700, color: "#3B82F6" }, "text"),
        createShapeElement("rounded-rectangle", 60, 630, 920, 120, "#1E293B", { borderRadius: 12 }),
        createTextElement("Category D", 100, 660, 600, 30, { fontSize: 20, fontWeight: 600, color: "#FFFFFF" }, "text"),
        createShapeElement("rectangle", 100, 700, 300, 30, "#10B981", { borderRadius: 4 }),
        createTextElement("38%", 820, 700, 100, 30, { fontSize: 18, fontWeight: 700, color: "#10B981" }, "text"),
      ],
    },
    {
      id: generateSlideId(),
      name: "Key Insight",
      order: 4,
      background: { type: "solid", color: "#0F172A" },
      elements: [
        createShapeElement("rectangle", 440, 200, 200, 4, "#00F5D4"),
        createTextElement(
          "KEY INSIGHT",
          60,
          240,
          960,
          40,
          { fontSize: 16, fontWeight: 600, letterSpacing: 4, textAlign: "center", color: "#00F5D4" },
          "text",
        ),
        createTextElement(
          "Organizations that track these metrics see 3x faster growth compared to those that don't",
          60,
          340,
          960,
          300,
          { fontSize: 40, fontWeight: 700, lineHeight: 1.4, textAlign: "center", color: "#FFFFFF" },
          "text",
        ),
        createShapeElement("rounded-rectangle", 60, 720, 920, 200, "#1E293B", { borderRadius: 16 }),
        createTextElement(
          "What This Means",
          100,
          760,
          840,
          35,
          { fontSize: 18, fontWeight: 600, color: "#00F5D4" },
          "text",
        ),
        createTextElement(
          "Data-driven decision making is no longer optional. Companies that embrace metrics-based strategies consistently outperform their competitors.",
          100,
          810,
          840,
          90,
          { fontSize: 18, fontWeight: 400, lineHeight: 1.6, color: "#94A3B8" },
          "text",
        ),
      ],
    },
    {
      id: generateSlideId(),
      name: "CTA",
      order: 5,
      background: { type: "solid", color: "#0F172A" },
      elements: [
        createShapeElement("circle", -100, 800, 400, 400, "#00F5D4", { opacity: 0.1 }),
        createShapeElement("circle", 800, 200, 300, 300, "#8B5CF6", { opacity: 0.08 }),
        createShapeElement("rectangle", 440, 300, 200, 4, "#00F5D4"),
        createTextElement(
          "Want More\nData Insights?",
          60,
          380,
          960,
          200,
          { fontSize: 60, fontWeight: 800, lineHeight: 1.2, textAlign: "center", color: "#FFFFFF" },
          "heading",
        ),
        createTextElement(
          "Follow for weekly research and data-driven insights",
          60,
          620,
          960,
          50,
          { fontSize: 22, fontWeight: 400, textAlign: "center", color: "#94A3B8" },
          "text",
        ),
        createShapeElement("rounded-rectangle", 340, 760, 400, 70, "#00F5D4", { borderRadius: 12 }),
        createTextElement(
          "Follow Now",
          340,
          775,
          400,
          40,
          { fontSize: 20, fontWeight: 600, textAlign: "center", color: "#0F172A" },
          "text",
        ),
        createTextElement(
          "@yourhandle",
          60,
          920,
          960,
          30,
          { fontSize: 16, fontWeight: 500, textAlign: "center", color: "#64748B" },
          "text",
        ),
      ],
    },
  ],
}
