// Template: Editor's Pick - Editorial design
import type { CarouselTemplate } from "../carousel-designer-types"
import { VIBRANT_PALETTES } from "../carousel-designer-types"
import { generateSlideId, createTextElement, createShapeElement } from "./template-helpers"

export const editorsPickTemplate: CarouselTemplate = {
  id: "editors-pick",
  name: "Editor's Pick",
  description: "Elegant editorial design with premium aesthetics.",
  category: "editors-pick",
  isPremium: false,
  isCustom: false,
  palette: VIBRANT_PALETTES.find((p) => p.id === "sunset-glow")!,
  size: "portrait",
  defaultFonts: { heading: "'Inter', sans-serif", body: "'Inter', sans-serif" },
  tags: ["editorial", "magazine", "professional"],
  createdAt: Date.now(),
  updatedAt: Date.now(),
  slides: [
    {
      id: generateSlideId(),
      name: "Cover",
      order: 0,
      background: { type: "solid", color: "#FFFFFF" },
      elements: [
        createShapeElement("rectangle", 0, 0, 1080, 780, "#0F172A"),
        createShapeElement("circle", -180, -180, 480, 480, "#1E293B", { opacity: 0.6 }),
        createShapeElement("circle", 850, 550, 350, 350, "#334155", { opacity: 0.3 }),
        createShapeElement("rectangle", 100, 120, 80, 5, "#3B82F6"),
        createTextElement(
          "EDITOR'S PICK",
          100,
          155,
          300,
          32,
          { fontSize: 12, fontWeight: 700, color: "#94A3B8", letterSpacing: 4 },
          "text",
        ),
        createTextElement(
          "Top Tools\nof the\nMonth",
          100,
          250,
          880,
          380,
          { fontSize: 88, fontWeight: 900, lineHeight: 1.03, color: "#FFFFFF", letterSpacing: -2 },
          "heading",
        ),
        createShapeElement("rectangle", 100, 660, 140, 5, "#FFFFFF"),
        createTextElement(
          "Curated Selection",
          100,
          860,
          550,
          55,
          { fontSize: 34, fontWeight: 800, color: "#0F172A" },
          "heading",
        ),
        createTextElement(
          "Hand-picked tools to enhance your workflow",
          100,
          930,
          640,
          38,
          { fontSize: 19, fontWeight: 400, color: "#64748B" },
          "text",
        ),
        createShapeElement("rounded-rectangle", 100, 1040, 200, 56, "#0F172A", { borderRadius: 10 }),
        createTextElement(
          "January 2026",
          100,
          1055,
          200,
          30,
          { fontSize: 15, fontWeight: 700, textAlign: "center", color: "#FFFFFF" },
          "text",
        ),
      ],
    },
    {
      id: generateSlideId(),
      name: "Tool 1",
      order: 1,
      background: { type: "solid", color: "#F8FAFC" },
      elements: [
        createShapeElement("rectangle", 0, 0, 1080, 8, "#3B82F6"),
        createShapeElement("rounded-rectangle", 100, 100, 160, 48, "#0F172A", { borderRadius: 8 }),
        createTextElement(
          "FEATURED",
          100,
          112,
          160,
          25,
          { fontSize: 13, fontWeight: 700, textAlign: "center", color: "#FFFFFF" },
          "text",
        ),
        createTextElement("01", 860, 80, 120, 85, { fontSize: 76, fontWeight: 900, color: "#E2E8F0" }, "text"),
        createTextElement(
          "Claude Code",
          100,
          220,
          880,
          75,
          { fontSize: 52, fontWeight: 900, color: "#0F172A", letterSpacing: -1 },
          "heading",
        ),
        createTextElement(
          "AI Development Assistant",
          100,
          310,
          550,
          32,
          { fontSize: 17, fontWeight: 600, color: "#3B82F6" },
          "text",
        ),
        createShapeElement("rounded-rectangle", 100, 400, 880, 500, "#FFFFFF", {
          borderRadius: 20,
          stroke: "#E2E8F0",
          strokeWidth: 2,
        }),
        createTextElement(
          "An agentic coding tool that lives in your terminal. It can understand your codebase, write code, and iterate autonomously.",
          150,
          460,
          780,
          130,
          { fontSize: 19, fontWeight: 400, lineHeight: 1.75, color: "#475569" },
          "body",
        ),
        createShapeElement("line", 150, 620, 780, 2, "#E2E8F0"),
        createTextElement(
          "Key Features",
          150,
          665,
          220,
          28,
          { fontSize: 15, fontWeight: 700, color: "#0F172A" },
          "text",
        ),
        createTextElement(
          "Terminal-based interface\n\nDeep codebase understanding\n\nAutonomous code generation\n\nMulti-file context awareness",
          150,
          720,
          780,
          150,
          { fontSize: 16, fontWeight: 400, lineHeight: 2, color: "#64748B" },
          "body",
        ),
        createShapeElement("rounded-rectangle", 100, 960, 880, 110, "#0F172A", { borderRadius: 14 }),
        createTextElement(
          "anthropic.com/claude-code",
          150,
          1005,
          550,
          32,
          { fontSize: 17, fontWeight: 600, color: "#FFFFFF" },
          "text",
        ),
      ],
    },
    {
      id: generateSlideId(),
      name: "Tool 2",
      order: 2,
      background: { type: "solid", color: "#FFFFFF" },
      elements: [
        createShapeElement("rectangle", 0, 0, 10, 1350, "#10B981"),
        createTextElement("02", 860, 80, 120, 85, { fontSize: 76, fontWeight: 900, color: "#E2E8F0" }, "text"),
        createTextElement(
          "Cursor",
          100,
          220,
          880,
          75,
          { fontSize: 52, fontWeight: 900, color: "#0F172A", letterSpacing: -1 },
          "heading",
        ),
        createTextElement(
          "AI-Powered Code Editor",
          100,
          310,
          550,
          32,
          { fontSize: 17, fontWeight: 600, color: "#10B981" },
          "text",
        ),
        createShapeElement("rounded-rectangle", 100, 400, 880, 300, "#F0FDF4", { borderRadius: 20 }),
        createTextElement(
          "The AI code editor built for pair programming. Understands your codebase and helps you code faster.",
          150,
          460,
          780,
          110,
          { fontSize: 19, fontWeight: 400, lineHeight: 1.75, color: "#15803D" },
          "body",
        ),
        createShapeElement("rounded-rectangle", 100, 750, 880, 300, "#FFFFFF", {
          borderRadius: 20,
          stroke: "#E2E8F0",
          strokeWidth: 2,
        }),
        createTextElement(
          "Why We Picked It",
          150,
          800,
          320,
          32,
          { fontSize: 17, fontWeight: 700, color: "#0F172A" },
          "text",
        ),
        createTextElement(
          "Cursor seamlessly integrates AI into the coding workflow. Multi-file editing and codebase understanding set it apart.",
          150,
          860,
          780,
          150,
          { fontSize: 17, fontWeight: 400, lineHeight: 1.85, color: "#64748B" },
          "body",
        ),
        createShapeElement("rounded-rectangle", 100, 1110, 320, 65, "#0F172A", { borderRadius: 12 }),
        createTextElement(
          "cursor.com",
          100,
          1130,
          320,
          30,
          { fontSize: 17, fontWeight: 700, textAlign: "center", color: "#FFFFFF" },
          "text",
        ),
      ],
    },
    {
      id: generateSlideId(),
      name: "Tool 3",
      order: 3,
      background: { type: "solid", color: "#F8FAFC" },
      elements: [
        createShapeElement("rectangle", 0, 0, 1080, 8, "#8B5CF6"),
        createTextElement("03", 860, 80, 120, 85, { fontSize: 76, fontWeight: 900, color: "#E2E8F0" }, "text"),
        createTextElement(
          "Replit AI",
          100,
          220,
          880,
          75,
          { fontSize: 52, fontWeight: 900, color: "#0F172A", letterSpacing: -1 },
          "heading",
        ),
        createTextElement(
          "Cloud Development Environment",
          100,
          310,
          600,
          32,
          { fontSize: 17, fontWeight: 600, color: "#8B5CF6" },
          "text",
        ),
        createShapeElement("rounded-rectangle", 100, 400, 880, 500, "#FFFFFF", {
          borderRadius: 20,
          stroke: "#E2E8F0",
          strokeWidth: 2,
        }),
        createTextElement(
          "Build, test, and deploy applications entirely in the browser with AI assistance at every step.",
          150,
          460,
          780,
          130,
          { fontSize: 19, fontWeight: 400, lineHeight: 1.75, color: "#475569" },
          "body",
        ),
        createShapeElement("line", 150, 620, 780, 2, "#E2E8F0"),
        createTextElement(
          "Key Features",
          150,
          665,
          220,
          28,
          { fontSize: 15, fontWeight: 700, color: "#0F172A" },
          "text",
        ),
        createTextElement(
          "Zero-setup cloud environment\n\nAI-powered code completion\n\nCollaborative coding features\n\nOne-click deployment",
          150,
          720,
          780,
          150,
          { fontSize: 16, fontWeight: 400, lineHeight: 2, color: "#64748B" },
          "body",
        ),
        createShapeElement("rounded-rectangle", 100, 960, 880, 110, "#0F172A", { borderRadius: 14 }),
        createTextElement(
          "replit.com",
          150,
          1005,
          550,
          32,
          { fontSize: 17, fontWeight: 600, color: "#FFFFFF" },
          "text",
        ),
      ],
    },
    {
      id: generateSlideId(),
      name: "CTA",
      order: 4,
      background: { type: "solid", color: "#0F172A" },
      elements: [
        createShapeElement("circle", -120, -120, 450, 450, "#1E293B", { opacity: 0.6 }),
        createShapeElement("circle", 780, 880, 450, 450, "#1E293B", { opacity: 0.5 }),
        createShapeElement("rectangle", 440, 280, 200, 5, "#3B82F6"),
        createTextElement(
          "Stay Updated",
          100,
          400,
          880,
          90,
          { fontSize: 68, fontWeight: 900, textAlign: "center", color: "#FFFFFF", letterSpacing: -1 },
          "heading",
        ),
        createTextElement(
          "Get weekly tool recommendations\ndelivered to your feed",
          100,
          530,
          880,
          110,
          { fontSize: 24, fontWeight: 400, lineHeight: 1.65, textAlign: "center", color: "#94A3B8" },
          "body",
        ),
        createShapeElement("rounded-rectangle", 340, 720, 400, 75, "#3B82F6", { borderRadius: 14 }),
        createTextElement(
          "Follow for More",
          340,
          740,
          400,
          38,
          { fontSize: 22, fontWeight: 700, textAlign: "center", color: "#FFFFFF" },
          "text",
        ),
        createTextElement(
          "@yourhandle",
          100,
          880,
          880,
          32,
          { fontSize: 19, fontWeight: 500, textAlign: "center", color: "#64748B" },
          "text",
        ),
      ],
    },
  ],
}
