// ═══════════════════════════════════════════════════════════════════════════════
// Template: Editors Pick Monthly
// Monthly curated selection of hand-picked AI development tools
// ═══════════════════════════════════════════════════════════════════════════════

import type { CarouselTemplate } from "../carousel-designer-types"
import { generateSlideId, createTextElement, createShapeElement } from "./template-helpers"

export const editorsPickMonthly: CarouselTemplate = {
  id: "editors-pick-monthly",
  name: "Editors Pick Monthly",
  description: "Monthly curated selection of hand-picked AI development tools with detailed reviews",
  category: "editors-pick",
  isPremium: false,
  isCustom: false,
  palette: {
    id: "dark-blue",
    name: "Dark Blue Professional",
    category: "dark",
    colors: {
      primary: "#60A5FA",
      secondary: "#3B82F6",
      accent: "#93C5FD",
      background: "#0A0E1A",
      text: "#FFFFFF",
      textSecondary: "#94A3B8",
    },
    gradient: { from: "#1E293B", to: "#0A0E1A", direction: "to-br" },
  },
  size: "portrait",
  defaultFonts: {
    heading: "'Inter', sans-serif",
    body: "'Inter', sans-serif",
  },
  tags: ["editorial", "curated", "tools", "monthly"],
  createdAt: Date.now(),
  updatedAt: Date.now(),
  slides: [
    // Cover Slide
    {
      id: generateSlideId(),
      name: "Cover",
      order: 0,
      background: { type: "solid", color: "#0A0E1A" },
      elements: [
        createShapeElement("line", 390, 420, 300, 4, "#60A5FA", { opacity: 0.6 }),
        createTextElement(
          "HAND PICKED",
          80,
          450,
          920,
          80,
          {
            fontSize: 72,
            fontWeight: 800,
            color: "#FFFFFF",
            textAlign: "center",
            letterSpacing: 8,
          },
          "heading",
        ),
        createTextElement(
          "Tools of the Month",
          80,
          540,
          920,
          60,
          {
            fontSize: 48,
            fontWeight: 300,
            color: "#60A5FA",
            textAlign: "center",
            letterSpacing: 2,
          },
          "subheading",
        ),
        createTextElement(
          "December 2024 Edition",
          80,
          720,
          920,
          30,
          {
            fontSize: 20,
            fontWeight: 400,
            color: "#94A3B8",
            textAlign: "center",
            letterSpacing: 2,
          },
          "text",
        ),
      ],
    },
    // Tool 1: Conductor
    {
      id: generateSlideId(),
      name: "Tool 1 - Conductor",
      order: 1,
      background: { type: "solid", color: "#0A0E1A" },
      elements: [
        createTextElement(
          "CONDUCTOR",
          80,
          100,
          920,
          70,
          {
            fontSize: 56,
            fontWeight: 800,
            color: "#FFFFFF",
            letterSpacing: 2,
          },
          "heading",
        ),
        createTextElement(
          "Multi-Agent Orchestration Platform",
          80,
          170,
          920,
          35,
          {
            fontSize: 24,
            fontWeight: 400,
            color: "#60A5FA",
          },
          "subheading",
        ),
        createShapeElement("rounded-rectangle", 80, 220, 920, 280, "#1E293B", { borderRadius: 16 }),
        createTextElement(
          "OVERVIEW",
          120,
          260,
          860,
          25,
          {
            fontSize: 16,
            fontWeight: 700,
            color: "#60A5FA",
            letterSpacing: 2,
          },
          "text",
        ),
        createTextElement(
          "Runs multiple AI coding agents together with isolated workspaces and UI to monitor output. Simple team and multi-agent workflow with Git worktree integration.",
          120,
          295,
          860,
          90,
          {
            fontSize: 20,
            fontWeight: 400,
            color: "#E2E8F0",
            lineHeight: 1.6,
          },
          "text",
        ),
        createTextElement(
          "FAMOUS FOR",
          120,
          405,
          860,
          25,
          {
            fontSize: 16,
            fontWeight: 700,
            color: "#60A5FA",
            letterSpacing: 2,
          },
          "text",
        ),
        createTextElement(
          "Parallel Claude Code/Codex agents in one environment with built-in workspace management.",
          120,
          440,
          860,
          60,
          {
            fontSize: 19,
            fontWeight: 400,
            color: "#CBD5E1",
            lineHeight: 1.5,
          },
          "text",
        ),
        // Pros Section
        createShapeElement("rounded-rectangle", 80, 530, 440, 280, "#1E293B", { borderRadius: 16 }),
        createTextElement(
          "PROS",
          120,
          565,
          360,
          25,
          {
            fontSize: 16,
            fontWeight: 700,
            color: "#34D399",
            letterSpacing: 2,
          },
          "text",
        ),
        createTextElement(
          "• Simple team workflow\n• Git worktree integration\n• Isolated workspaces\n• Monitor agent output",
          120,
          600,
          360,
          130,
          {
            fontSize: 18,
            fontWeight: 400,
            color: "#E2E8F0",
            lineHeight: 1.8,
          },
          "text",
        ),
        // Cons Section
        createShapeElement("rounded-rectangle", 560, 530, 440, 280, "#1E293B", { borderRadius: 16 }),
        createTextElement(
          "CONS",
          600,
          565,
          360,
          25,
          {
            fontSize: 16,
            fontWeight: 700,
            color: "#F87171",
            letterSpacing: 2,
          },
          "text",
        ),
        createTextElement(
          "• Tied to Claude agents only\n• Limited to specific workflow\n• Early stage platform",
          600,
          600,
          360,
          100,
          {
            fontSize: 18,
            fontWeight: 400,
            color: "#E2E8F0",
            lineHeight: 1.8,
          },
          "text",
        ),
        // Funding Section
        createShapeElement("rounded-rectangle", 80, 840, 920, 120, "#1E293B", { borderRadius: 16 }),
        createTextElement(
          "FUNDING",
          120,
          875,
          860,
          25,
          {
            fontSize: 16,
            fontWeight: 700,
            color: "#60A5FA",
            letterSpacing: 2,
          },
          "text",
        ),
        createTextElement(
          "Pre-seed: Y Combinator (2024)",
          120,
          910,
          860,
          30,
          {
            fontSize: 20,
            fontWeight: 600,
            color: "#FFFFFF",
          },
          "text",
        ),
        createTextElement(
          "https://conductor.build/",
          120,
          1000,
          860,
          28,
          {
            fontSize: 18,
            fontWeight: 500,
            color: "#60A5FA",
          },
          "text",
        ),
      ],
    },
    // Tool 2: Graphite
    {
      id: generateSlideId(),
      name: "Tool 2 - Graphite",
      order: 2,
      background: { type: "solid", color: "#0A0E1A" },
      elements: [
        createTextElement(
          "GRAPHITE",
          80,
          100,
          920,
          70,
          {
            fontSize: 56,
            fontWeight: 800,
            color: "#FFFFFF",
            letterSpacing: 2,
          },
          "heading",
        ),
        createTextElement(
          "AI-Assisted Code Review Platform",
          80,
          170,
          920,
          35,
          {
            fontSize: 24,
            fontWeight: 400,
            color: "#60A5FA",
          },
          "subheading",
        ),
        createShapeElement("rounded-rectangle", 80, 220, 920, 280, "#1E293B", { borderRadius: 16 }),
        createTextElement(
          "OVERVIEW",
          120,
          260,
          860,
          25,
          {
            fontSize: 16,
            fontWeight: 700,
            color: "#60A5FA",
            letterSpacing: 2,
          },
          "text",
        ),
        createTextElement(
          "AI-assisted code review platform focused on pull requests and team workflows. Boosts code quality via AI review with unified workflow across review, CI, and merge.",
          120,
          295,
          860,
          90,
          {
            fontSize: 20,
            fontWeight: 400,
            color: "#E2E8F0",
            lineHeight: 1.6,
          },
          "text",
        ),
        createTextElement(
          "FAMOUS FOR",
          120,
          405,
          860,
          25,
          {
            fontSize: 16,
            fontWeight: 700,
            color: "#60A5FA",
            letterSpacing: 2,
          },
          "text",
        ),
        createTextElement(
          "AI feedback on PRs, stacked PRs, merge queue, and deep GitHub integration.",
          120,
          440,
          860,
          60,
          {
            fontSize: 19,
            fontWeight: 400,
            color: "#CBD5E1",
            lineHeight: 1.5,
          },
          "text",
        ),
        createShapeElement("rounded-rectangle", 80, 530, 440, 280, "#1E293B", { borderRadius: 16 }),
        createTextElement(
          "PROS",
          120,
          565,
          360,
          25,
          {
            fontSize: 16,
            fontWeight: 700,
            color: "#34D399",
            letterSpacing: 2,
          },
          "text",
        ),
        createTextElement(
          "• AI-powered PR feedback\n• Stacked PRs support\n• Deep GitHub integration\n• Free trial available",
          120,
          600,
          360,
          130,
          {
            fontSize: 18,
            fontWeight: 400,
            color: "#E2E8F0",
            lineHeight: 1.8,
          },
          "text",
        ),
        createShapeElement("rounded-rectangle", 560, 530, 440, 280, "#1E293B", { borderRadius: 16 }),
        createTextElement(
          "CONS",
          600,
          565,
          360,
          25,
          {
            fontSize: 16,
            fontWeight: 700,
            color: "#F87171",
            letterSpacing: 2,
          },
          "text",
        ),
        createTextElement(
          "• Unified workflow learning\n• Team adoption required\n• CI/CD integration needed",
          600,
          600,
          360,
          100,
          {
            fontSize: 18,
            fontWeight: 400,
            color: "#E2E8F0",
            lineHeight: 1.8,
          },
          "text",
        ),
        createShapeElement("rounded-rectangle", 80, 840, 920, 120, "#1E293B", { borderRadius: 16 }),
        createTextElement(
          "FUNDING",
          120,
          875,
          860,
          25,
          {
            fontSize: 16,
            fontWeight: 700,
            color: "#60A5FA",
            letterSpacing: 2,
          },
          "text",
        ),
        createTextElement(
          "$81M total, $52M Series B (Accel, Menlo/Anthropic, a16z)",
          120,
          910,
          860,
          28,
          {
            fontSize: 19,
            fontWeight: 600,
            color: "#FFFFFF",
          },
          "text",
        ),
        createTextElement(
          "https://graphite.com/",
          120,
          1000,
          860,
          28,
          {
            fontSize: 18,
            fontWeight: 500,
            color: "#60A5FA",
          },
          "text",
        ),
      ],
    },
    // Tool 3: Kapa.ai
    {
      id: generateSlideId(),
      name: "Tool 3 - Kapa.ai",
      order: 3,
      background: { type: "solid", color: "#0A0E1A" },
      elements: [
        createTextElement(
          "KAPA.AI",
          80,
          100,
          920,
          70,
          {
            fontSize: 56,
            fontWeight: 800,
            color: "#FFFFFF",
            letterSpacing: 2,
          },
          "heading",
        ),
        createTextElement(
          "AI-Powered Documentation Generator",
          80,
          170,
          920,
          35,
          {
            fontSize: 24,
            fontWeight: 400,
            color: "#60A5FA",
          },
          "subheading",
        ),
        createShapeElement("rounded-rectangle", 80, 220, 920, 280, "#1E293B", { borderRadius: 16 }),
        createTextElement(
          "OVERVIEW",
          120,
          260,
          860,
          25,
          {
            fontSize: 16,
            fontWeight: 700,
            color: "#60A5FA",
            letterSpacing: 2,
          },
          "text",
        ),
        createTextElement(
          "AI-powered interactive documentation generator that maintains up-to-date wiki for code-bases. Eliminates stale manual docs with interactive Q&A tied to real code.",
          120,
          295,
          860,
          90,
          {
            fontSize: 20,
            fontWeight: 400,
            color: "#E2E8F0",
            lineHeight: 1.6,
          },
          "text",
        ),
        createTextElement(
          "FAMOUS FOR",
          120,
          405,
          860,
          25,
          {
            fontSize: 16,
            fontWeight: 700,
            color: "#60A5FA",
            letterSpacing: 2,
          },
          "text",
        ),
        createTextElement(
          "Auto-generated living docs with code links and integrated AI chat to explain structure.",
          120,
          440,
          860,
          60,
          {
            fontSize: 19,
            fontWeight: 400,
            color: "#CBD5E1",
            lineHeight: 1.5,
          },
          "text",
        ),
        createShapeElement("rounded-rectangle", 80, 530, 440, 280, "#1E293B", { borderRadius: 16 }),
        createTextElement(
          "PROS",
          120,
          565,
          360,
          25,
          {
            fontSize: 16,
            fontWeight: 700,
            color: "#34D399",
            letterSpacing: 2,
          },
          "text",
        ),
        createTextElement(
          "• Eliminates stale docs\n• Interactive Q&A system\n• Tied to real code\n• Auto-generated updates",
          120,
          600,
          360,
          130,
          {
            fontSize: 18,
            fontWeight: 400,
            color: "#E2E8F0",
            lineHeight: 1.8,
          },
          "text",
        ),
        createShapeElement("rounded-rectangle", 560, 530, 440, 280, "#1E293B", { borderRadius: 16 }),
        createTextElement(
          "CONS",
          600,
          565,
          360,
          25,
          {
            fontSize: 16,
            fontWeight: 700,
            color: "#F87171",
            letterSpacing: 2,
          },
          "text",
        ),
        createTextElement(
          "• Public preview for open repos\n• Private CLI coming soon\n• Complex interdependencies",
          600,
          600,
          360,
          100,
          {
            fontSize: 18,
            fontWeight: 400,
            color: "#E2E8F0",
            lineHeight: 1.8,
          },
          "text",
        ),
        createShapeElement("rounded-rectangle", 80, 840, 920, 120, "#1E293B", { borderRadius: 16 }),
        createTextElement(
          "FUNDING",
          120,
          875,
          860,
          25,
          {
            fontSize: 16,
            fontWeight: 700,
            color: "#60A5FA",
            letterSpacing: 2,
          },
          "text",
        ),
        createTextElement(
          "Corporate-backed (Google)",
          120,
          910,
          860,
          30,
          {
            fontSize: 20,
            fontWeight: 600,
            color: "#FFFFFF",
          },
          "text",
        ),
        createTextElement(
          "https://kapa.ai/",
          120,
          1000,
          860,
          28,
          {
            fontSize: 18,
            fontWeight: 500,
            color: "#60A5FA",
          },
          "text",
        ),
      ],
    },
    // Outro Slide
    {
      id: generateSlideId(),
      name: "Outro",
      order: 4,
      background: { type: "solid", color: "#0A0E1A" },
      elements: [
        createTextElement(
          "STAY TUNED",
          80,
          480,
          920,
          70,
          {
            fontSize: 52,
            fontWeight: 800,
            color: "#FFFFFF",
            textAlign: "center",
            letterSpacing: 6,
          },
          "heading",
        ),
        createTextElement(
          "More tools coming next month",
          80,
          570,
          920,
          40,
          {
            fontSize: 28,
            fontWeight: 400,
            color: "#60A5FA",
            textAlign: "center",
          },
          "subheading",
        ),
        createShapeElement("rounded-rectangle", 290, 680, 500, 80, "#1E293B", { borderRadius: 12 }),
        createTextElement(
          "@YourHandle",
          290,
          695,
          500,
          50,
          {
            fontSize: 32,
            fontWeight: 700,
            color: "#60A5FA",
            textAlign: "center",
          },
          "text",
        ),
        createTextElement(
          "Like | Save | Share | Follow",
          80,
          820,
          920,
          35,
          {
            fontSize: 22,
            fontWeight: 400,
            color: "#94A3B8",
            textAlign: "center",
          },
          "text",
        ),
      ],
    },
  ],
}
