// ═══════════════════════════════════════════════════════════════════════════════
// Template: Gradient Wave
// Modern gradient design with flowing shapes - Enhanced
// ═══════════════════════════════════════════════════════════════════════════════

import type { CarouselTemplate } from "../carousel-designer-types"
import { generateSlideId, createTextElement, createShapeElement } from "./template-helpers"

export const gradientWaveTemplate: CarouselTemplate = {
  id: "gradient-wave",
  name: "Gradient Wave",
  description: "Modern professional design with sophisticated gradients. Great for business professionals.",
  category: "creative",
  isPremium: false,
  isCustom: false,
  palette: {
    id: "navy-gradient",
    name: "Navy Gradient",
    category: "professional",
    colors: {
      primary: "#1E40AF",
      secondary: "#3B82F6",
      accent: "#60A5FA",
      background: "#F8FAFC",
      text: "#1E293B",
      textSecondary: "#475569",
    },
  },
  size: "portrait",
  defaultFonts: {
    heading: "'Inter', sans-serif",
    body: "'Inter', sans-serif",
  },
  tags: ["gradient", "professional", "modern", "business"],
  createdAt: Date.now(),
  updatedAt: Date.now(),
  slides: [
    {
      id: generateSlideId(),
      name: "Cover",
      order: 0,
      background: {
        type: "gradient",
        gradient: { from: "#1E40AF", to: "#3B82F6", direction: "to-br" },
      },
      elements: [
        createShapeElement("circle", -150, 1000, 500, 500, "#60A5FA", { opacity: 0.2 }),
        createShapeElement("circle", 700, -100, 400, 400, "#93C5FD", { opacity: 0.15 }),
        createTextElement(
          "PROFESSIONAL",
          60,
          220,
          300,
          35,
          { fontSize: 13, fontWeight: 600, letterSpacing: 5, color: "#DBEAFE", textTransform: "uppercase" },
          "text",
        ),
        createShapeElement("line", 60, 520, 80, 3, "#DBEAFE"),
        createTextElement(
          "Strategic\nTitle Here",
          60,
          580,
          960,
          220,
          { fontSize: 64, fontWeight: 800, lineHeight: 1.15, color: "#FFFFFF" },
          "heading",
        ),
        createTextElement(
          "Engage your audience with professional insights",
          60,
          840,
          960,
          60,
          { fontSize: 22, fontWeight: 400, color: "#DBEAFE" },
          "subheading",
        ),
        createTextElement(
          "@yourhandle",
          60,
          1260,
          480,
          30,
          { fontSize: 16, fontWeight: 500, color: "rgba(255,255,255,0.7)" },
          "text",
        ),
        createTextElement(
          "Swipe",
          780,
          1260,
          240,
          30,
          { fontSize: 16, fontWeight: 500, textAlign: "right", color: "rgba(255,255,255,0.7)" },
          "text",
        ),
      ],
    },

    {
      id: generateSlideId(),
      name: "Content 1",
      order: 1,
      background: { type: "solid", color: "#F8FAFC" },
      elements: [
        createShapeElement("rectangle", 0, 0, 1080, 100, "#1E40AF"),
        createShapeElement("rounded-rectangle", 60, 200, 180, 180, "#1E40AF", { borderRadius: 20 }),
        createTextElement(
          "01",
          60,
          250,
          180,
          80,
          { fontSize: 56, fontWeight: 800, textAlign: "center", color: "#FFFFFF" },
          "text",
        ),
        createTextElement(
          "Key Insight",
          280,
          240,
          720,
          70,
          { fontSize: 40, fontWeight: 700, color: "#1E293B" },
          "heading",
        ),
        createTextElement(
          "Professional overview",
          280,
          320,
          720,
          40,
          { fontSize: 18, fontWeight: 400, color: "#475569" },
          "text",
        ),
        createTextElement(
          "Your main content goes here. Use engaging language and provide real value to your readers. Include examples, data, or insights to make it memorable.",
          60,
          460,
          960,
          250,
          { fontSize: 24, fontWeight: 400, lineHeight: 1.7, color: "#1E293B" },
          "body",
        ),
        createShapeElement("rounded-rectangle", 60, 780, 960, 150, "#EFF6FF", { borderRadius: 12 }),
        createTextElement(
          "Key Takeaway",
          100,
          820,
          880,
          30,
          { fontSize: 14, fontWeight: 600, letterSpacing: 2, color: "#1E40AF", textTransform: "uppercase" },
          "text",
        ),
        createTextElement(
          "A memorable insight from this section",
          100,
          860,
          880,
          50,
          { fontSize: 20, fontWeight: 500, color: "#1E293B" },
          "text",
        ),
      ],
    },

    {
      id: generateSlideId(),
      name: "Content 2",
      order: 2,
      background: { type: "solid", color: "#F8FAFC" },
      elements: [
        createShapeElement("rectangle", 0, 0, 1080, 100, "#3B82F6"),
        createShapeElement("rounded-rectangle", 60, 200, 180, 180, "#3B82F6", { borderRadius: 20 }),
        createTextElement(
          "02",
          60,
          250,
          180,
          80,
          { fontSize: 56, fontWeight: 800, textAlign: "center", color: "#FFFFFF" },
          "text",
        ),
        createTextElement(
          "Second Point",
          280,
          240,
          720,
          70,
          { fontSize: 40, fontWeight: 700, color: "#1E293B" },
          "heading",
        ),
        createTextElement(
          "Another key aspect",
          280,
          320,
          720,
          40,
          { fontSize: 18, fontWeight: 400, color: "#475569" },
          "text",
        ),
        createTextElement(
          "Continue building on your narrative. Each slide should add value and move the story forward. Keep your audience engaged with relevant information.",
          60,
          460,
          960,
          250,
          { fontSize: 24, fontWeight: 400, lineHeight: 1.7, color: "#1E293B" },
          "body",
        ),
        createShapeElement("rounded-rectangle", 60, 780, 960, 150, "#EFF6FF", { borderRadius: 12 }),
        createTextElement(
          "Remember This",
          100,
          820,
          880,
          30,
          { fontSize: 14, fontWeight: 600, letterSpacing: 2, color: "#1E40AF", textTransform: "uppercase" },
          "text",
        ),
        createTextElement(
          "Another important takeaway for your audience",
          100,
          860,
          880,
          50,
          { fontSize: 20, fontWeight: 500, color: "#1E293B" },
          "text",
        ),
      ],
    },

    {
      id: generateSlideId(),
      name: "Content 3",
      order: 3,
      background: { type: "solid", color: "#F8FAFC" },
      elements: [
        createShapeElement("rectangle", 0, 0, 1080, 100, "#60A5FA"),
        createShapeElement("rounded-rectangle", 60, 200, 180, 180, "#60A5FA", { borderRadius: 20 }),
        createTextElement(
          "03",
          60,
          250,
          180,
          80,
          { fontSize: 56, fontWeight: 800, textAlign: "center", color: "#FFFFFF" },
          "text",
        ),
        createTextElement(
          "Final Insight",
          280,
          240,
          720,
          70,
          { fontSize: 40, fontWeight: 700, color: "#1E293B" },
          "heading",
        ),
        createTextElement(
          "Bringing it together",
          280,
          320,
          720,
          40,
          { fontSize: 18, fontWeight: 400, color: "#475569" },
          "text",
        ),
        createTextElement(
          "Conclude your message with a powerful final point. Make sure your audience understands the big picture and knows what action to take next.",
          60,
          460,
          960,
          250,
          { fontSize: 24, fontWeight: 400, lineHeight: 1.7, color: "#1E293B" },
          "body",
        ),
        createShapeElement("rounded-rectangle", 60, 780, 960, 150, "#EFF6FF", { borderRadius: 12 }),
        createTextElement(
          "Action Step",
          100,
          820,
          880,
          30,
          { fontSize: 14, fontWeight: 600, letterSpacing: 2, color: "#1E40AF", textTransform: "uppercase" },
          "text",
        ),
        createTextElement(
          "What your audience should do with this information",
          100,
          860,
          880,
          50,
          { fontSize: 20, fontWeight: 500, color: "#1E293B" },
          "text",
        ),
      ],
    },

    {
      id: generateSlideId(),
      name: "Summary",
      order: 4,
      background: {
        type: "gradient",
        gradient: { from: "#3B82F6", to: "#1E40AF", direction: "to-b" },
      },
      elements: [
        createShapeElement("circle", -100, 900, 500, 500, "#93C5FD", { opacity: 0.2 }),
        createShapeElement("circle", 800, -100, 400, 400, "#DBEAFE", { opacity: 0.15 }),
        createTextElement(
          "KEY TAKEAWAYS",
          60,
          300,
          960,
          40,
          { fontSize: 18, fontWeight: 600, textAlign: "center", color: "#DBEAFE", letterSpacing: 4 },
          "text",
        ),
        createTextElement(
          "Remember These\nThree Things",
          60,
          380,
          960,
          180,
          { fontSize: 48, fontWeight: 800, textAlign: "center", color: "#FFFFFF", lineHeight: 1.3 },
          "heading",
        ),
        createShapeElement("rounded-rectangle", 60, 620, 960, 80, "rgba(255,255,255,0.15)", { borderRadius: 12 }),
        createTextElement(
          "1. First key takeaway",
          100,
          645,
          880,
          30,
          { fontSize: 22, fontWeight: 600, color: "#FFFFFF" },
          "text",
        ),
        createShapeElement("rounded-rectangle", 60, 720, 960, 80, "rgba(255,255,255,0.15)", { borderRadius: 12 }),
        createTextElement(
          "2. Second key takeaway",
          100,
          745,
          880,
          30,
          { fontSize: 22, fontWeight: 600, color: "#FFFFFF" },
          "text",
        ),
        createShapeElement("rounded-rectangle", 60, 820, 960, 80, "rgba(255,255,255,0.15)", { borderRadius: 12 }),
        createTextElement(
          "3. Third key takeaway",
          100,
          845,
          880,
          30,
          { fontSize: 22, fontWeight: 600, color: "#FFFFFF" },
          "text",
        ),
      ],
    },

    {
      id: generateSlideId(),
      name: "CTA",
      order: 5,
      background: { type: "solid", color: "#1E293B" },
      elements: [
        createShapeElement("circle", 300, 400, 480, 480, "#3B82F6", { opacity: 0.3 }),
        createTextElement(
          "Want more content like this?",
          60,
          500,
          960,
          70,
          { fontSize: 42, fontWeight: 700, textAlign: "center", color: "#FFFFFF" },
          "heading",
        ),
        createTextElement(
          "Follow @yourhandle for daily inspiration",
          60,
          610,
          960,
          50,
          { fontSize: 24, fontWeight: 400, textAlign: "center", color: "#DBEAFE" },
          "text",
        ),
        createShapeElement("rounded-rectangle", 340, 730, 400, 70, "#3B82F6", { borderRadius: 35 }),
        createTextElement(
          "FOLLOW NOW",
          340,
          745,
          400,
          40,
          { fontSize: 22, fontWeight: 700, textAlign: "center", color: "#FFFFFF" },
          "text",
        ),
      ],
    },
  ],
}
