// Template: Minimal Professional - Clean, elegant design for thought leadership content
import type { CarouselTemplate } from "../carousel-designer-types"
import { VIBRANT_PALETTES } from "../carousel-designer-types"
import { createTextElement, createShapeElement, generateSlideId } from "./template-helpers"

export const minimalProfessionalTemplate: CarouselTemplate = {
  id: "minimal-professional",
  name: "Minimal Professional",
  description: "Clean and elegant design for thought leadership content. Perfect for executives and consultants.",
  category: "minimal",
  isPremium: false,
  isCustom: false,
  palette: VIBRANT_PALETTES.find((p) => p.id === "minimal-gray") || VIBRANT_PALETTES[0],
  size: "portrait",
  defaultFonts: {
    heading: "'Inter', sans-serif",
    body: "'Inter', sans-serif",
  },
  tags: ["minimal", "clean", "professional", "elegant"],
  createdAt: Date.now(),
  updatedAt: Date.now(),
  slides: [
    {
      id: generateSlideId(),
      name: "Cover",
      order: 0,
      background: { type: "solid", color: "#FFFFFF" },
      elements: [
        createShapeElement("rectangle", 0, 0, 1080, 180, "#1A1A1A"),
        createShapeElement("line", 60, 500, 80, 4, "#1A1A1A"),
        createTextElement(
          "YOUR TITLE HERE",
          60,
          560,
          960,
          100,
          { fontSize: 56, fontWeight: 700, textAlign: "left", color: "#1A1A1A", lineHeight: 1.1 },
          "heading",
        ),
        createTextElement(
          "Subtitle or tagline goes here",
          60,
          700,
          960,
          50,
          { fontSize: 24, fontWeight: 400, textAlign: "left", color: "#6B7280" },
          "subheading",
        ),
        createShapeElement("line", 60, 1200, 960, 1, "#E5E7EB"),
        createTextElement(
          "@yourhandle",
          60,
          1260,
          480,
          30,
          { fontSize: 16, fontWeight: 500, textAlign: "left", color: "#9CA3AF" },
          "text",
        ),
        createTextElement(
          "Swipe",
          780,
          1260,
          240,
          30,
          { fontSize: 16, fontWeight: 500, textAlign: "right", color: "#9CA3AF" },
          "text",
        ),
      ],
    },
    {
      id: generateSlideId(),
      name: "Point 1",
      order: 1,
      background: { type: "solid", color: "#FFFFFF" },
      elements: [
        createTextElement("01", 60, 80, 120, 70, { fontSize: 52, fontWeight: 800, color: "#1A1A1A" }, "text"),
        createShapeElement("line", 60, 180, 80, 3, "#1A1A1A"),
        createTextElement(
          "First Key Point",
          60,
          240,
          960,
          70,
          { fontSize: 44, fontWeight: 700, color: "#1A1A1A" },
          "heading",
        ),
        createTextElement(
          "Your detailed explanation goes here. Keep it concise and impactful. Use short sentences for better readability on mobile devices.",
          60,
          360,
          960,
          250,
          { fontSize: 24, fontWeight: 400, lineHeight: 1.7, color: "#4B5563" },
          "body",
        ),
        createShapeElement("rounded-rectangle", 60, 700, 960, 180, "#F9FAFB", { borderRadius: 12 }),
        createTextElement(
          "Key Takeaway",
          100,
          740,
          880,
          30,
          { fontSize: 14, fontWeight: 600, letterSpacing: 2, color: "#6B7280", textTransform: "uppercase" },
          "text",
        ),
        createTextElement(
          "A memorable insight that summarizes this point",
          100,
          790,
          880,
          60,
          { fontSize: 20, fontWeight: 500, color: "#1A1A1A", lineHeight: 1.5 },
          "text",
        ),
      ],
    },
    {
      id: generateSlideId(),
      name: "Point 2",
      order: 2,
      background: { type: "solid", color: "#FFFFFF" },
      elements: [
        createTextElement("02", 60, 80, 120, 70, { fontSize: 52, fontWeight: 800, color: "#1A1A1A" }, "text"),
        createShapeElement("line", 60, 180, 80, 3, "#1A1A1A"),
        createTextElement(
          "Second Key Point",
          60,
          240,
          960,
          70,
          { fontSize: 44, fontWeight: 700, color: "#1A1A1A" },
          "heading",
        ),
        createTextElement(
          "Continue building your narrative. Each slide should flow naturally into the next one, creating a cohesive story.",
          60,
          360,
          960,
          250,
          { fontSize: 24, fontWeight: 400, lineHeight: 1.7, color: "#4B5563" },
          "body",
        ),
        createShapeElement("rounded-rectangle", 60, 700, 960, 180, "#F9FAFB", { borderRadius: 12 }),
        createTextElement(
          "Key Takeaway",
          100,
          740,
          880,
          30,
          { fontSize: 14, fontWeight: 600, letterSpacing: 2, color: "#6B7280", textTransform: "uppercase" },
          "text",
        ),
        createTextElement(
          "Another insight that reinforces your message",
          100,
          790,
          880,
          60,
          { fontSize: 20, fontWeight: 500, color: "#1A1A1A", lineHeight: 1.5 },
          "text",
        ),
      ],
    },
    {
      id: generateSlideId(),
      name: "Point 3",
      order: 3,
      background: { type: "solid", color: "#FFFFFF" },
      elements: [
        createTextElement("03", 60, 80, 120, 70, { fontSize: 52, fontWeight: 800, color: "#1A1A1A" }, "text"),
        createShapeElement("line", 60, 180, 80, 3, "#1A1A1A"),
        createTextElement(
          "Third Key Point",
          60,
          240,
          960,
          70,
          { fontSize: 44, fontWeight: 700, color: "#1A1A1A" },
          "heading",
        ),
        createTextElement(
          "Add more value with your third point. Make sure it adds something new and meaningful to the discussion.",
          60,
          360,
          960,
          250,
          { fontSize: 24, fontWeight: 400, lineHeight: 1.7, color: "#4B5563" },
          "body",
        ),
        createShapeElement("rounded-rectangle", 60, 700, 960, 180, "#F9FAFB", { borderRadius: 12 }),
        createTextElement(
          "Key Takeaway",
          100,
          740,
          880,
          30,
          { fontSize: 14, fontWeight: 600, letterSpacing: 2, color: "#6B7280", textTransform: "uppercase" },
          "text",
        ),
        createTextElement(
          "The final takeaway that ties everything together",
          100,
          790,
          880,
          60,
          { fontSize: 20, fontWeight: 500, color: "#1A1A1A", lineHeight: 1.5 },
          "text",
        ),
      ],
    },
    {
      id: generateSlideId(),
      name: "Call to Action",
      order: 4,
      background: { type: "solid", color: "#1A1A1A" },
      elements: [
        createShapeElement("line", 60, 450, 80, 3, "#FFFFFF"),
        createTextElement(
          "Ready to learn more?",
          60,
          510,
          960,
          70,
          { fontSize: 44, fontWeight: 700, textAlign: "left", color: "#FFFFFF" },
          "heading",
        ),
        createTextElement(
          "Follow for more insights like this",
          60,
          610,
          960,
          50,
          { fontSize: 24, fontWeight: 400, textAlign: "left", color: "#9CA3AF" },
          "subheading",
        ),
        createShapeElement("rounded-rectangle", 60, 780, 280, 60, "#FFFFFF", { borderRadius: 8 }),
        createTextElement(
          "Follow",
          60,
          795,
          280,
          35,
          { fontSize: 18, fontWeight: 600, textAlign: "center", color: "#1A1A1A" },
          "text",
        ),
        createTextElement(
          "@yourhandle",
          60,
          1260,
          960,
          30,
          { fontSize: 18, fontWeight: 500, textAlign: "left", color: "#6B7280" },
          "text",
        ),
      ],
    },
  ],
}
