// ═══════════════════════════════════════════════════════════════════════════════
// Template: Mint Fresh
// Professional charcoal and teal tones - Enhanced with more slides
// ═══════════════════════════════════════════════════════════════════════════════

import type { CarouselTemplate } from "../carousel-designer-types"
import { generateSlideId, createTextElement, createShapeElement } from "./template-helpers"

export const mintFreshTemplate: CarouselTemplate = {
  id: "mint-fresh",
  name: "Mint Fresh",
  description: "Professional charcoal and teal design for business and professional topics.",
  category: "vibrant",
  isPremium: false,
  isCustom: false,
  palette: {
    id: "charcoal-teal",
    name: "Charcoal Teal",
    category: "professional",
    colors: {
      primary: "#0F766E",
      secondary: "#14B8A6",
      accent: "#5EEAD4",
      background: "#F9FAFB",
      text: "#111827",
      textSecondary: "#4B5563",
    },
    gradient: { from: "#0F766E", to: "#14B8A6", direction: "to-br" },
  },
  size: "portrait",
  defaultFonts: {
    heading: "'Inter', sans-serif",
    body: "'Inter', sans-serif",
  },
  tags: ["professional", "teal", "charcoal", "business", "clean"],
  createdAt: Date.now(),
  updatedAt: Date.now(),
  slides: [
    {
      id: generateSlideId(),
      name: "Intro",
      order: 0,
      background: { type: "solid", color: "#0F766E" },
      elements: [
        createShapeElement("circle", 700, 1000, 500, 500, "#14B8A6", { opacity: 0.2 }),
        createShapeElement("circle", -100, -100, 400, 400, "#5EEAD4", { opacity: 0.15 }),
        createShapeElement("line", 60, 570, 80, 3, "#5EEAD4"),
        createTextElement(
          "STRATEGIC INSIGHTS",
          60,
          610,
          960,
          80,
          { fontSize: 56, fontWeight: 800, textAlign: "center", color: "#FFFFFF" },
          "heading",
        ),
        createTextElement(
          "Professional guidance for growth",
          60,
          710,
          960,
          50,
          { fontSize: 24, fontWeight: 400, textAlign: "center", color: "rgba(255,255,255,0.85)" },
          "text",
        ),
      ],
    },

    {
      id: generateSlideId(),
      name: "Point 1",
      order: 1,
      background: { type: "solid", color: "#F9FAFB" },
      elements: [
        createShapeElement("rounded-rectangle", 860, 140, 140, 140, "#0F766E", { borderRadius: 70 }),
        createTextElement(
          "01",
          860,
          180,
          140,
          60,
          { fontSize: 42, fontWeight: 800, textAlign: "center", color: "#FFFFFF" },
          "text",
        ),
        createTextElement(
          "Start With Strategy",
          60,
          450,
          800,
          80,
          { fontSize: 46, fontWeight: 700, color: "#111827" },
          "heading",
        ),
        createTextElement(
          "Understanding your strategic direction is the first step to any meaningful business growth.",
          60,
          570,
          960,
          150,
          { fontSize: 24, fontWeight: 400, color: "#4B5563", lineHeight: 1.6 },
          "text",
        ),
      ],
    },

    {
      id: generateSlideId(),
      name: "Point 2",
      order: 2,
      background: { type: "solid", color: "#F9FAFB" },
      elements: [
        createShapeElement("rounded-rectangle", 860, 140, 140, 140, "#14B8A6", { borderRadius: 70 }),
        createTextElement(
          "02",
          860,
          180,
          140,
          60,
          { fontSize: 42, fontWeight: 800, textAlign: "center", color: "#FFFFFF" },
          "text",
        ),
        createTextElement(
          "Build Systems",
          60,
          450,
          800,
          80,
          { fontSize: 46, fontWeight: 700, color: "#111827" },
          "heading",
        ),
        createTextElement(
          "Systematic processes compound into exceptional results and sustainable growth over time.",
          60,
          570,
          960,
          150,
          { fontSize: 24, fontWeight: 400, color: "#4B5563", lineHeight: 1.6 },
          "text",
        ),
      ],
    },

    {
      id: generateSlideId(),
      name: "Point 3",
      order: 3,
      background: { type: "solid", color: "#F9FAFB" },
      elements: [
        createShapeElement("rounded-rectangle", 860, 140, 140, 140, "#5EEAD4", { borderRadius: 70 }),
        createTextElement(
          "03",
          860,
          180,
          140,
          60,
          { fontSize: 42, fontWeight: 800, textAlign: "center", color: "#111827" },
          "text",
        ),
        createTextElement(
          "Execute Consistently",
          60,
          450,
          800,
          80,
          { fontSize: 46, fontWeight: 700, color: "#111827" },
          "heading",
        ),
        createTextElement(
          "The key to transformation is disciplined execution every single day, regardless of circumstances.",
          60,
          570,
          960,
          150,
          { fontSize: 24, fontWeight: 400, color: "#4B5563", lineHeight: 1.6 },
          "text",
        ),
      ],
    },

    {
      id: generateSlideId(),
      name: "Point 4",
      order: 4,
      background: { type: "solid", color: "#F9FAFB" },
      elements: [
        createShapeElement("rounded-rectangle", 860, 140, 140, 140, "#0F766E", { borderRadius: 70 }),
        createTextElement(
          "04",
          860,
          180,
          140,
          60,
          { fontSize: 42, fontWeight: 800, textAlign: "center", color: "#FFFFFF" },
          "text",
        ),
        createTextElement(
          "Track Metrics",
          60,
          450,
          800,
          80,
          { fontSize: 46, fontWeight: 700, color: "#111827" },
          "heading",
        ),
        createTextElement(
          "Monitor your key performance indicators and adjust strategies to maintain forward momentum.",
          60,
          570,
          960,
          150,
          { fontSize: 24, fontWeight: 400, color: "#4B5563", lineHeight: 1.6 },
          "text",
        ),
      ],
    },

    {
      id: generateSlideId(),
      name: "Point 5",
      order: 5,
      background: { type: "solid", color: "#F9FAFB" },
      elements: [
        createShapeElement("rounded-rectangle", 860, 140, 140, 140, "#14B8A6", { borderRadius: 70 }),
        createTextElement(
          "05",
          860,
          180,
          140,
          60,
          { fontSize: 42, fontWeight: 800, textAlign: "center", color: "#FFFFFF" },
          "text",
        ),
        createTextElement(
          "Learn and Adapt",
          60,
          450,
          800,
          80,
          { fontSize: 46, fontWeight: 700, color: "#111827" },
          "heading",
        ),
        createTextElement(
          "Every challenge is an opportunity for refinement. Analyze, adapt, and continue advancing forward.",
          60,
          570,
          960,
          150,
          { fontSize: 24, fontWeight: 400, color: "#4B5563", lineHeight: 1.6 },
          "text",
        ),
      ],
    },

    {
      id: generateSlideId(),
      name: "Summary",
      order: 6,
      background: {
        type: "gradient",
        gradient: { from: "#0F766E", to: "#14B8A6", direction: "to-b" },
        color: "#0F766E",
      },
      elements: [
        createTextElement(
          "KEY PRINCIPLES",
          60,
          480,
          960,
          50,
          { fontSize: 20, fontWeight: 600, textAlign: "center", color: "rgba(255,255,255,0.75)", letterSpacing: 5 },
          "text",
        ),
        createTextElement(
          "Excellence is a\njourney, not a\ndestination.",
          60,
          570,
          960,
          280,
          { fontSize: 50, fontWeight: 800, textAlign: "center", color: "#FFFFFF", lineHeight: 1.35 },
          "heading",
        ),
      ],
    },

    {
      id: generateSlideId(),
      name: "Outro",
      order: 7,
      background: { type: "solid", color: "#111827" },
      elements: [
        createShapeElement("circle", 400, 550, 280, 280, "#0F766E", { opacity: 0.2 }),
        createTextElement(
          "Save for future reference",
          60,
          630,
          960,
          60,
          { fontSize: 34, fontWeight: 600, textAlign: "center", color: "#FFFFFF" },
          "heading",
        ),
        createTextElement(
          "Follow @yourhandle for more insights",
          60,
          720,
          960,
          50,
          { fontSize: 22, fontWeight: 400, textAlign: "center", color: "#5EEAD4" },
          "text",
        ),
      ],
    },
  ],
}
