// ═══════════════════════════════════════════════════════════════════════════════
// Template: Modern Sky Blue
// Light professional template with cool blue tones and geometric patterns
// ═══════════════════════════════════════════════════════════════════════════════

import type { CarouselTemplate } from "../carousel-designer-types"
import { generateSlideId, createTextElement, createShapeElement } from "./template-helpers"

export const modernSkyBlue: CarouselTemplate = {
  id: "modern-sky-blue",
  name: "Modern Sky Blue",
  description: "Professional light template with cool blue tones and geometric patterns",
  category: "minimal",
  isPremium: false,
  isCustom: false,
  palette: {
    id: "modern-sky",
    name: "Modern Sky",
    category: "professional",
    colors: {
      primary: "#1E3A8A",
      secondary: "#475569",
      accent: "#3B82F6",
      background: "#F1F5F9",
      text: "#0F172A",
      textSecondary: "#64748B",
    },
    gradient: { from: "#F1F5F9", to: "#E0E7FF", direction: "to-br" },
  },
  size: "portrait",
  defaultFonts: {
    heading: "'Inter', sans-serif",
    body: "'Inter', sans-serif",
  },
  tags: ["light", "modern", "professional", "blue"],
  createdAt: Date.now(),
  updatedAt: Date.now(),
  slides: [
    // Cover Slide
    {
      id: generateSlideId(),
      name: "Cover",
      order: 0,
      background: { type: "solid", color: "#F1F5F9" },
      elements: [
        createShapeElement("rounded-rectangle", 820, 120, 180, 180, "#3B82F6", { borderRadius: 16, opacity: 0.12 }),
        createShapeElement("rounded-rectangle", 100, 950, 140, 140, "#3B82F6", { borderRadius: 12, opacity: 0.15 }),
        createShapeElement("rounded-rectangle", 900, 1100, 100, 100, "#60A5FA", { borderRadius: 8, opacity: 0.18 }),

        createTextElement(
          "AI DEVELOPMENT",
          80,
          400,
          920,
          70,
          {
            fontSize: 62,
            fontWeight: 800,
            color: "#1E3A8A",
            textAlign: "center",
            letterSpacing: 4,
          },
          "heading",
        ),
        createTextElement(
          "TOOLKIT",
          80,
          485,
          920,
          80,
          {
            fontSize: 72,
            fontWeight: 900,
            color: "#1E3A8A",
            textAlign: "center",
            letterSpacing: 6,
          },
          "heading",
        ),
        createShapeElement("rounded-rectangle", 340, 590, 400, 4, "#3B82F6", { borderRadius: 2, opacity: 0.7 }),
        createTextElement(
          "2024 Editor's Choice • December",
          80,
          650,
          920,
          35,
          {
            fontSize: 20,
            fontWeight: 500,
            color: "#64748B",
            textAlign: "center",
            letterSpacing: 2,
          },
          "text",
        ),
        createTextElement(
          "Top 5 Tools Transforming Development",
          80,
          720,
          920,
          50,
          {
            fontSize: 24,
            fontWeight: 600,
            color: "#475569",
            textAlign: "center",
            lineHeight: 1.5,
          },
          "text",
        ),
        createShapeElement("line", 0, 850, 1080, 1, "#3B82F6", { opacity: 0.1 }),
        createShapeElement("line", 0, 900, 1080, 1, "#3B82F6", { opacity: 0.1 }),
        createShapeElement("line", 0, 950, 1080, 1, "#3B82F6", { opacity: 0.1 }),
      ],
    },
    // Tool 1: Cursor
    {
      id: generateSlideId(),
      name: "Tool 1 - Cursor",
      order: 1,
      background: { type: "solid", color: "#F1F5F9" },
      elements: [
        createShapeElement("line", 0, 60, 1080, 1, "#3B82F6", { opacity: 0.08 }),
        createShapeElement("line", 0, 110, 1080, 1, "#3B82F6", { opacity: 0.08 }),

        createShapeElement("circle", 120, 240, 110, 110, "transparent", {
          opacity: 1,
        }),
        createTextElement(
          "1",
          70,
          200,
          200,
          110,
          {
            fontSize: 68,
            fontWeight: 900,
            color: "#1E3A8A",
            textAlign: "center",
            lineHeight: 1.8,
          },
          "heading",
        ),

        createTextElement(
          "CURSOR",
          280,
          220,
          720,
          65,
          {
            fontSize: 52,
            fontWeight: 800,
            color: "#1E3A8A",
            letterSpacing: 3,
          },
          "heading",
        ),
        createTextElement(
          "AI-powered code editor built on VS Code with intelligent autocomplete and chat.",
          80,
          340,
          920,
          65,
          {
            fontSize: 22,
            fontWeight: 500,
            color: "#475569",
            lineHeight: 1.6,
          },
          "text",
        ),

        createShapeElement("rounded-rectangle", 80, 450, 920, 190, "#DBEAFE", {
          borderRadius: 16,
          opacity: 0.8,
        }),
        createTextElement(
          "FAMOUS FOR:",
          120,
          485,
          840,
          28,
          {
            fontSize: 18,
            fontWeight: 700,
            color: "#1E3A8A",
            letterSpacing: 2,
          },
          "text",
        ),
        createTextElement(
          "Tab autocomplete, Cmd+K inline edits, AI chat with codebase context, and multi-file editing.",
          120,
          525,
          840,
          95,
          {
            fontSize: 20,
            fontWeight: 500,
            color: "#0F172A",
            lineHeight: 1.7,
          },
          "text",
        ),

        createShapeElement("rounded-rectangle", 80, 670, 920, 250, "#E0E7FF", {
          borderRadius: 16,
          opacity: 0.7,
        }),
        createTextElement(
          "• Fast inline code generation",
          130,
          710,
          820,
          35,
          {
            fontSize: 21,
            fontWeight: 500,
            color: "#0F172A",
            lineHeight: 1.6,
          },
          "text",
        ),
        createTextElement(
          "• Multi-file context awareness",
          130,
          760,
          820,
          35,
          {
            fontSize: 21,
            fontWeight: 500,
            color: "#0F172A",
            lineHeight: 1.6,
          },
          "text",
        ),
        createTextElement(
          "• Built on familiar VS Code foundation",
          130,
          810,
          820,
          35,
          {
            fontSize: 21,
            fontWeight: 500,
            color: "#0F172A",
            lineHeight: 1.6,
          },
          "text",
        ),
        createTextElement(
          "• Natural language code modifications",
          130,
          860,
          820,
          35,
          {
            fontSize: 21,
            fontWeight: 500,
            color: "#0F172A",
            lineHeight: 1.6,
          },
          "text",
        ),

        createTextElement(
          "FUNDING: $60M Series A (Andreessen Horowitz, 2024)",
          80,
          960,
          920,
          30,
          {
            fontSize: 18,
            fontWeight: 600,
            color: "#1E3A8A",
          },
          "text",
        ),
        createTextElement(
          "COMPANY: Anysphere Inc. • Founded 2022",
          80,
          1005,
          920,
          28,
          {
            fontSize: 17,
            fontWeight: 500,
            color: "#64748B",
          },
          "text",
        ),
        createTextElement(
          "cursor.sh",
          80,
          1050,
          920,
          30,
          {
            fontSize: 19,
            fontWeight: 600,
            color: "#3B82F6",
            textDecoration: "underline",
          },
          "text",
        ),

        createShapeElement("rounded-rectangle", 850, 520, 140, 140, "#3B82F6", { borderRadius: 12, opacity: 0.1 }),
      ],
    },
    // Tool 2: Windsurf
    {
      id: generateSlideId(),
      name: "Tool 2 - Windsurf",
      order: 2,
      background: { type: "solid", color: "#F8FAFC" },
      elements: [
        createShapeElement("rounded-rectangle", 80, 100, 100, 6, "#0EA5E9", { borderRadius: 3, opacity: 0.3 }),
        createShapeElement("rounded-rectangle", 200, 100, 60, 6, "#0EA5E9", { borderRadius: 3, opacity: 0.2 }),

        createShapeElement("circle", 60, 180, 100, 100, "transparent", {
          opacity: 1,
        }),
        createTextElement(
          "2",
          60,
          205,
          100,
          60,
          {
            fontSize: 56,
            fontWeight: 900,
            color: "#0F172A",
            textAlign: "center",
          },
          "heading",
        ),

        createTextElement(
          "WINDSURF",
          200,
          200,
          800,
          55,
          {
            fontSize: 52,
            fontWeight: 800,
            color: "#0F172A",
            letterSpacing: 1,
          },
          "heading",
        ),
        createTextElement(
          "AI-First IDE by Codeium",
          200,
          260,
          800,
          30,
          {
            fontSize: 22,
            fontWeight: 500,
            color: "#0EA5E9",
          },
          "subheading",
        ),

        createTextElement(
          "Revolutionary IDE that pairs you with AI for collaborative coding. Flow state coding with intelligent suggestions.",
          80,
          340,
          920,
          80,
          {
            fontSize: 22,
            fontWeight: 400,
            color: "#0F172A",
            lineHeight: 1.6,
          },
          "text",
        ),

        createShapeElement("rounded-rectangle", 80, 460, 920, 200, "#E2E8F0", {
          borderRadius: 16,
        }),
        createTextElement(
          "FAMOUS FOR:",
          120,
          500,
          840,
          28,
          {
            fontSize: 18,
            fontWeight: 700,
            color: "#0F172A",
            letterSpacing: 2,
          },
          "text",
        ),
        createTextElement(
          "Flow state coding experience with AI that understands your entire codebase and coding patterns.",
          120,
          540,
          840,
          90,
          {
            fontSize: 20,
            fontWeight: 500,
            color: "#475569",
            lineHeight: 1.7,
          },
          "text",
        ),

        createShapeElement("rounded-rectangle", 80, 700, 920, 260, "#F1F5F9", { borderRadius: 16 }),
        createTextElement(
          "KEY FEATURES",
          120,
          740,
          840,
          28,
          {
            fontSize: 18,
            fontWeight: 700,
            color: "#0F172A",
            letterSpacing: 2,
          },
          "text",
        ),
        createTextElement(
          "• AI pair programming experience\n• Codebase-aware suggestions\n• Real-time collaboration mode\n• Multi-language support\n• Free for developers",
          120,
          785,
          840,
          155,
          {
            fontSize: 19,
            fontWeight: 500,
            color: "#0F172A",
            lineHeight: 1.9,
          },
          "text",
        ),

        createTextElement(
          "COMPANY:",
          80,
          1010,
          920,
          25,
          {
            fontSize: 16,
            fontWeight: 700,
            color: "#0F172A",
            letterSpacing: 2,
          },
          "text",
        ),
        createTextElement(
          "Codeium • $500M valuation • General Catalyst, Kleiner Perkins",
          80,
          1045,
          920,
          30,
          {
            fontSize: 20,
            fontWeight: 600,
            color: "#0F172A",
          },
          "text",
        ),

        createTextElement(
          "https://codeium.com/windsurf",
          80,
          1200,
          840,
          30,
          {
            fontSize: 19,
            fontWeight: 500,
            color: "#0EA5E9",
          },
          "text",
        ),

        createShapeElement("rounded-rectangle", 80, 1180, 60, 60, "#0EA5E9", { borderRadius: 8, opacity: 0.12 }),
      ],
    },
    // Tool 3: Bolt.new
    {
      id: generateSlideId(),
      name: "Tool 3 - Bolt.new",
      order: 3,
      background: { type: "solid", color: "#F8FAFC" },
      elements: [
        createShapeElement("rounded-rectangle", 80, 100, 100, 6, "#0EA5E9", { borderRadius: 3, opacity: 0.3 }),
        createShapeElement("rounded-rectangle", 200, 100, 60, 6, "#0EA5E9", { borderRadius: 3, opacity: 0.2 }),

        createShapeElement("circle", 60, 180, 100, 100, "transparent", {
          opacity: 1,
        }),
        createTextElement(
          "3",
          60,
          205,
          100,
          60,
          {
            fontSize: 56,
            fontWeight: 900,
            color: "#0F172A",
            textAlign: "center",
          },
          "heading",
        ),

        createTextElement(
          "BOLT.NEW",
          200,
          200,
          800,
          55,
          {
            fontSize: 52,
            fontWeight: 800,
            color: "#0F172A",
            letterSpacing: 1,
          },
          "heading",
        ),
        createTextElement(
          "AI Full-Stack App Builder",
          200,
          260,
          800,
          30,
          {
            fontSize: 22,
            fontWeight: 500,
            color: "#0EA5E9",
          },
          "subheading",
        ),

        createTextElement(
          "Build and deploy full-stack applications with AI. Prompt to production in minutes with live preview.",
          80,
          340,
          920,
          80,
          {
            fontSize: 22,
            fontWeight: 400,
            color: "#0F172A",
            lineHeight: 1.6,
          },
          "text",
        ),

        createShapeElement("rounded-rectangle", 80, 460, 920, 200, "#E2E8F0", {
          borderRadius: 16,
        }),
        createTextElement(
          "FAMOUS FOR:",
          120,
          500,
          840,
          28,
          {
            fontSize: 18,
            fontWeight: 700,
            color: "#0F172A",
            letterSpacing: 2,
          },
          "text",
        ),
        createTextElement(
          "Instant full-stack app generation with live preview, real-time editing, and one-click deployment.",
          120,
          540,
          840,
          90,
          {
            fontSize: 20,
            fontWeight: 500,
            color: "#475569",
            lineHeight: 1.7,
          },
          "text",
        ),

        createShapeElement("rounded-rectangle", 80, 700, 920, 260, "#F1F5F9", { borderRadius: 16 }),
        createTextElement(
          "KEY FEATURES",
          120,
          740,
          840,
          28,
          {
            fontSize: 18,
            fontWeight: 700,
            color: "#0F172A",
            letterSpacing: 2,
          },
          "text",
        ),
        createTextElement(
          "• Full-stack app generation\n• Live preview environment\n• Real-time code editing\n• Instant deployment\n• Multiple framework support",
          120,
          785,
          840,
          155,
          {
            fontSize: 19,
            fontWeight: 500,
            color: "#0F172A",
            lineHeight: 1.9,
          },
          "text",
        ),

        createTextElement(
          "COMPANY:",
          80,
          1010,
          920,
          25,
          {
            fontSize: 16,
            fontWeight: 700,
            color: "#0F172A",
            letterSpacing: 2,
          },
          "text",
        ),
        createTextElement(
          "StackBlitz • Part of WebContainer technology",
          80,
          1045,
          920,
          30,
          {
            fontSize: 20,
            fontWeight: 600,
            color: "#0F172A",
          },
          "text",
        ),

        createTextElement(
          "https://bolt.new",
          80,
          1200,
          840,
          30,
          {
            fontSize: 19,
            fontWeight: 500,
            color: "#0EA5E9",
          },
          "text",
        ),

        createShapeElement("rounded-rectangle", 900, 1100, 90, 90, "#0EA5E9", { borderRadius: 14, opacity: 0.12 }),
      ],
    },
    // Tool 4: Tabnine
    {
      id: generateSlideId(),
      name: "Tool 4 - Tabnine",
      order: 4,
      background: { type: "solid", color: "#F8FAFC" },
      elements: [
        createShapeElement("rounded-rectangle", 80, 100, 100, 6, "#0EA5E9", { borderRadius: 3, opacity: 0.3 }),
        createShapeElement("rounded-rectangle", 200, 100, 60, 6, "#0EA5E9", { borderRadius: 3, opacity: 0.2 }),

        createShapeElement("circle", 60, 180, 100, 100, "transparent", {
          opacity: 1,
        }),
        createTextElement(
          "4",
          60,
          205,
          100,
          60,
          {
            fontSize: 56,
            fontWeight: 900,
            color: "#0F172A",
            textAlign: "center",
          },
          "heading",
        ),

        createTextElement(
          "TABNINE",
          200,
          200,
          800,
          55,
          {
            fontSize: 52,
            fontWeight: 800,
            color: "#0F172A",
            letterSpacing: 1,
          },
          "heading",
        ),
        createTextElement(
          "Enterprise AI Code Assistant",
          200,
          260,
          800,
          30,
          {
            fontSize: 22,
            fontWeight: 500,
            color: "#0EA5E9",
          },
          "subheading",
        ),

        createTextElement(
          "Privacy-focused AI code assistant for enterprises. Train on your codebase with complete data control.",
          80,
          340,
          920,
          80,
          {
            fontSize: 22,
            fontWeight: 400,
            color: "#0F172A",
            lineHeight: 1.6,
          },
          "text",
        ),

        createShapeElement("rounded-rectangle", 80, 460, 920, 200, "#E2E8F0", {
          borderRadius: 16,
        }),
        createTextElement(
          "FAMOUS FOR:",
          120,
          500,
          840,
          28,
          {
            fontSize: 18,
            fontWeight: 700,
            color: "#0F172A",
            letterSpacing: 2,
          },
          "text",
        ),
        createTextElement(
          "Enterprise-grade privacy and security with on-premise deployment options and custom model training.",
          120,
          540,
          840,
          90,
          {
            fontSize: 20,
            fontWeight: 500,
            color: "#475569",
            lineHeight: 1.7,
          },
          "text",
        ),

        createShapeElement("rounded-rectangle", 80, 700, 920, 260, "#F1F5F9", { borderRadius: 16 }),
        createTextElement(
          "KEY FEATURES",
          120,
          740,
          840,
          28,
          {
            fontSize: 18,
            fontWeight: 700,
            color: "#0F172A",
            letterSpacing: 2,
          },
          "text",
        ),
        createTextElement(
          "• Enterprise-grade privacy\n• On-premise deployment option\n• Custom model training\n• SOC 2 Type II certified\n• Zero data retention policy",
          120,
          785,
          840,
          155,
          {
            fontSize: 19,
            fontWeight: 500,
            color: "#0F172A",
            lineHeight: 1.9,
          },
          "text",
        ),

        createTextElement(
          "COMPANY:",
          80,
          1010,
          920,
          25,
          {
            fontSize: 16,
            fontWeight: 700,
            color: "#0F172A",
            letterSpacing: 2,
          },
          "text",
        ),
        createTextElement(
          "Tabnine • $55M Series B • Qualcomm Ventures, Telstra Ventures",
          80,
          1045,
          920,
          30,
          {
            fontSize: 20,
            fontWeight: 600,
            color: "#0F172A",
          },
          "text",
        ),

        createTextElement(
          "https://tabnine.com",
          80,
          1200,
          840,
          30,
          {
            fontSize: 19,
            fontWeight: 500,
            color: "#0EA5E9",
          },
          "text",
        ),

        createShapeElement("rounded-rectangle", 100, 1150, 70, 70, "#0EA5E9", { borderRadius: 10, opacity: 0.12 }),
      ],
    },
    // Outro Slide
    {
      id: generateSlideId(),
      name: "Outro",
      order: 5,
      background: { type: "solid", color: "#F8FAFC" },
      elements: [
        createShapeElement("rounded-rectangle", 80, 200, 100, 100, "#0EA5E9", { borderRadius: 16, opacity: 0.15 }),
        createShapeElement("rounded-rectangle", 900, 250, 120, 120, "#0EA5E9", { borderRadius: 18, opacity: 0.12 }),

        createTextElement(
          "SEE YOU NEXT",
          80,
          530,
          920,
          60,
          {
            fontSize: 52,
            fontWeight: 800,
            color: "#0F172A",
            textAlign: "center",
            letterSpacing: 6,
          },
          "heading",
        ),
        createTextElement(
          "WEEK",
          80,
          600,
          920,
          70,
          {
            fontSize: 64,
            fontWeight: 900,
            color: "#0EA5E9",
            textAlign: "center",
            letterSpacing: 8,
          },
          "heading",
        ),

        createShapeElement("rounded-rectangle", 390, 710, 300, 4, "#0EA5E9", { borderRadius: 2 }),

        createShapeElement("rounded-rectangle", 290, 780, 500, 90, "#0F172A", { borderRadius: 16 }),
        createTextElement(
          "@YourHandle",
          290,
          800,
          500,
          50,
          {
            fontSize: 34,
            fontWeight: 700,
            color: "#F8FAFC",
            textAlign: "center",
          },
          "text",
        ),

        createTextElement(
          "Like • Save • Share • Follow",
          80,
          930,
          920,
          35,
          {
            fontSize: 24,
            fontWeight: 500,
            color: "#475569",
            textAlign: "center",
            letterSpacing: 3,
          },
          "text",
        ),

        createShapeElement("rounded-rectangle", 150, 1080, 80, 80, "#0EA5E9", { borderRadius: 12, opacity: 0.1 }),
        createShapeElement("rounded-rectangle", 850, 1100, 60, 60, "#0EA5E9", { borderRadius: 8, opacity: 0.1 }),
      ],
    },
  ],
}
