// ═══════════════════════════════════════════════════════════════════════════════
// Template: Personal Brand
// Perfect for personal branding and storytelling - Enhanced
// ═══════════════════════════════════════════════════════════════════════════════

import type { CarouselTemplate } from "../carousel-designer-types"
import { VIBRANT_PALETTES } from "../carousel-designer-types"
import { generateSlideId, createTextElement, createShapeElement } from "./template-helpers"

export const personalBrandTemplate: CarouselTemplate = {
  id: "personal-brand",
  name: "Personal Brand",
  description: "Build your personal brand with this authentic storytelling template.",
  category: "personal-brand",
  isPremium: false,
  isCustom: false,
  palette: VIBRANT_PALETTES.find((p) => p.id === "rose-gold")!,
  size: "portrait",
  defaultFonts: {
    heading: "'Inter', sans-serif",
    body: "'Inter', sans-serif",
  },
  tags: ["personal", "brand", "storytelling", "authentic"],
  createdAt: Date.now(),
  updatedAt: Date.now(),
  slides: [
    {
      id: generateSlideId(),
      name: "Cover",
      order: 0,
      background: { type: "solid", color: "#FFFBF7" },
      elements: [
        createShapeElement("circle", 340, 220, 400, 400, "#F5E6E0"),
        createTextElement(
          "MY STORY",
          60,
          180,
          400,
          35,
          { fontSize: 13, fontWeight: 600, letterSpacing: 5, color: "#9B6B5A", textTransform: "uppercase" },
          "text",
        ),
        createShapeElement("line", 60, 720, 80, 3, "#9B6B5A"),
        createTextElement(
          "How I went from\n[A] to [B]",
          60,
          780,
          960,
          200,
          { fontSize: 48, fontWeight: 700, lineHeight: 1.3, color: "#2D2A26" },
          "heading",
        ),
        createTextElement(
          "A journey of transformation",
          60,
          1020,
          960,
          50,
          { fontSize: 22, fontWeight: 400, fontStyle: "italic", color: "#6B6560" },
          "subheading",
        ),
        createTextElement("Thread", 920, 1220, 100, 30, { fontSize: 14, fontWeight: 500, color: "#9B6B5A" }, "text"),
      ],
    },

    {
      id: generateSlideId(),
      name: "Story",
      order: 1,
      background: { type: "solid", color: "#FFFFFF" },
      elements: [
        createShapeElement("rectangle", 0, 0, 60, 1350, "#9B6B5A"),
        createShapeElement("line", 100, 300, 60, 3, "#9B6B5A"),
        createTextElement(
          "Your powerful quote or statement that captures the essence of your story.",
          100,
          360,
          920,
          240,
          { fontSize: 36, fontWeight: 600, lineHeight: 1.5, fontStyle: "italic", color: "#2D2A26" },
          "body",
        ),
        createShapeElement("line", 100, 660, 100, 2, "#9B6B5A"),
        createTextElement(
          "This is where you share a key moment or lesson from your journey. Make it personal and relatable.",
          100,
          720,
          920,
          240,
          { fontSize: 22, fontWeight: 400, lineHeight: 1.7, color: "#6B6560" },
          "body",
        ),
        createShapeElement("rounded-rectangle", 100, 1040, 860, 140, "#FFF8F4", { borderRadius: 12 }),
        createTextElement(
          "Key Lesson",
          140,
          1080,
          780,
          30,
          { fontSize: 14, fontWeight: 600, letterSpacing: 2, color: "#9B6B5A", textTransform: "uppercase" },
          "text",
        ),
        createTextElement(
          "A memorable insight from this chapter",
          140,
          1120,
          780,
          40,
          { fontSize: 18, fontWeight: 500, color: "#2D2A26" },
          "text",
        ),
      ],
    },

    {
      id: generateSlideId(),
      name: "Chapter 2",
      order: 2,
      background: { type: "solid", color: "#FFFBF7" },
      elements: [
        createShapeElement("rounded-rectangle", 60, 100, 120, 120, "#9B6B5A", { borderRadius: 60 }),
        createTextElement(
          "02",
          75,
          125,
          90,
          70,
          { fontSize: 44, fontWeight: 800, textAlign: "center", color: "#FFFFFF" },
          "text",
        ),
        createTextElement(
          "The Turning Point",
          60,
          280,
          960,
          80,
          { fontSize: 42, fontWeight: 700, color: "#2D2A26" },
          "heading",
        ),
        createTextElement(
          "Every great story has a moment where everything changes. This was mine.",
          60,
          400,
          960,
          100,
          { fontSize: 24, fontWeight: 400, color: "#6B6560", lineHeight: 1.6 },
          "body",
        ),
        createShapeElement("rounded-rectangle", 60, 540, 960, 280, "#F5E6E0", { borderRadius: 16 }),
        createTextElement(
          "Describe your pivotal moment here. What happened? How did you feel? What did you decide to do differently?",
          100,
          590,
          880,
          180,
          { fontSize: 22, fontWeight: 400, lineHeight: 1.7, color: "#2D2A26" },
          "body",
        ),
      ],
    },

    {
      id: generateSlideId(),
      name: "Chapter 3",
      order: 3,
      background: { type: "solid", color: "#FFFFFF" },
      elements: [
        createShapeElement("rectangle", 1020, 0, 60, 1350, "#9B6B5A"),
        createShapeElement("rounded-rectangle", 60, 100, 120, 120, "#F5E6E0", { borderRadius: 60 }),
        createTextElement(
          "03",
          75,
          125,
          90,
          70,
          { fontSize: 44, fontWeight: 800, textAlign: "center", color: "#9B6B5A" },
          "text",
        ),
        createTextElement(
          "Taking Action",
          60,
          280,
          900,
          80,
          { fontSize: 42, fontWeight: 700, color: "#2D2A26" },
          "heading",
        ),
        createTextElement(
          "Here's what I did next:",
          60,
          400,
          900,
          40,
          { fontSize: 20, fontWeight: 600, color: "#9B6B5A" },
          "text",
        ),
        createShapeElement("line", 80, 480, 4, 60, "#9B6B5A"),
        createTextElement(
          "First action step and what I learned",
          120,
          480,
          840,
          60,
          { fontSize: 22, fontWeight: 500, color: "#2D2A26", lineHeight: 1.5 },
          "text",
        ),
        createShapeElement("line", 80, 580, 4, 60, "#9B6B5A"),
        createTextElement(
          "Second action step and the results",
          120,
          580,
          840,
          60,
          { fontSize: 22, fontWeight: 500, color: "#2D2A26", lineHeight: 1.5 },
          "text",
        ),
        createShapeElement("line", 80, 680, 4, 60, "#9B6B5A"),
        createTextElement(
          "Third action step and the impact",
          120,
          680,
          840,
          60,
          { fontSize: 22, fontWeight: 500, color: "#2D2A26", lineHeight: 1.5 },
          "text",
        ),
      ],
    },

    {
      id: generateSlideId(),
      name: "Results",
      order: 4,
      background: { type: "solid", color: "#9B6B5A" },
      elements: [
        createShapeElement("circle", -100, 900, 400, 400, "#FFFFFF", { opacity: 0.1 }),
        createShapeElement("circle", 800, -100, 350, 350, "#FFFFFF", { opacity: 0.08 }),
        createTextElement(
          "THE RESULTS",
          60,
          250,
          960,
          40,
          { fontSize: 18, fontWeight: 600, textAlign: "center", color: "rgba(255,255,255,0.8)", letterSpacing: 4 },
          "text",
        ),
        createTextElement(
          "Where I Am Today",
          60,
          320,
          960,
          100,
          { fontSize: 44, fontWeight: 700, textAlign: "center", color: "#FFFFFF" },
          "heading",
        ),
        createShapeElement("rounded-rectangle", 60, 480, 300, 180, "rgba(255,255,255,0.15)", { borderRadius: 16 }),
        createTextElement(
          "Result 1",
          60,
          510,
          300,
          120,
          { fontSize: 32, fontWeight: 700, textAlign: "center", color: "#FFFFFF", lineHeight: 1.3 },
          "text",
        ),
        createShapeElement("rounded-rectangle", 390, 480, 300, 180, "rgba(255,255,255,0.15)", { borderRadius: 16 }),
        createTextElement(
          "Result 2",
          390,
          510,
          300,
          120,
          { fontSize: 32, fontWeight: 700, textAlign: "center", color: "#FFFFFF", lineHeight: 1.3 },
          "text",
        ),
        createShapeElement("rounded-rectangle", 720, 480, 300, 180, "rgba(255,255,255,0.15)", { borderRadius: 16 }),
        createTextElement(
          "Result 3",
          720,
          510,
          300,
          120,
          { fontSize: 32, fontWeight: 700, textAlign: "center", color: "#FFFFFF", lineHeight: 1.3 },
          "text",
        ),
        createTextElement(
          "And this is just the beginning of the journey.",
          60,
          740,
          960,
          60,
          { fontSize: 22, fontWeight: 400, textAlign: "center", color: "rgba(255,255,255,0.9)", lineHeight: 1.5 },
          "body",
        ),
      ],
    },

    {
      id: generateSlideId(),
      name: "Call to Action",
      order: 5,
      background: { type: "solid", color: "#FFFBF7" },
      elements: [
        createShapeElement("circle", 340, 400, 400, 400, "#F5E6E0"),
        createTextElement(
          "Your Turn",
          60,
          450,
          960,
          70,
          { fontSize: 48, fontWeight: 700, textAlign: "center", color: "#2D2A26" },
          "heading",
        ),
        createTextElement(
          "If I can do it, so can you.\nStart your journey today.",
          60,
          560,
          960,
          100,
          { fontSize: 26, fontWeight: 400, textAlign: "center", color: "#6B6560", lineHeight: 1.6 },
          "body",
        ),
        createShapeElement("rounded-rectangle", 290, 720, 500, 70, "#9B6B5A", { borderRadius: 35 }),
        createTextElement(
          "FOLLOW @yourhandle",
          290,
          735,
          500,
          40,
          { fontSize: 20, fontWeight: 700, textAlign: "center", color: "#FFFFFF" },
          "text",
        ),
      ],
    },
  ],
}
