// Template: Professional Dark Mode - Clean corporate dark design
import type { CarouselTemplate } from "../carousel-designer-types"
import { VIBRANT_PALETTES } from "../carousel-designer-types"
import { generateSlideId, createTextElement, createShapeElement } from "./template-helpers"

export const professionalDarkModeTemplate: CarouselTemplate = {
  id: "professional-dark-mode",
  name: "Professional Dark Mode",
  description: "Clean dark mode template with subtle blue accents for corporate presentations",
  category: "corporate",
  isPremium: false,
  isCustom: false,
  palette: VIBRANT_PALETTES.find((p) => p.id === "professional-blue") || VIBRANT_PALETTES[0],
  size: "portrait",
  defaultFonts: { heading: "'Inter', sans-serif", body: "'Inter', sans-serif" },
  tags: ["dark", "professional", "corporate", "modern"],
  createdAt: Date.now(),
  updatedAt: Date.now(),
  slides: [
    {
      id: generateSlideId(),
      name: "Cover",
      order: 0,
      background: { type: "solid", color: "#0F172A" },
      elements: [
        createShapeElement("rectangle", 80, 200, 120, 4, "#3B82F6", { borderRadius: 2 }),
        createTextElement(
          "BUSINESS INSIGHTS",
          80,
          230,
          920,
          50,
          { fontSize: 20, fontWeight: 600, color: "#3B82F6", letterSpacing: 3 },
          "text",
        ),
        createTextElement(
          "Strategic\nGrowth\nFramework",
          80,
          300,
          920,
          280,
          { fontSize: 72, fontWeight: 700, color: "#F8FAFC", lineHeight: 1.1 },
          "heading",
        ),
        createTextElement(
          "A proven methodology for scaling your business with confidence and clarity",
          80,
          620,
          920,
          100,
          { fontSize: 24, fontWeight: 400, color: "#94A3B8", lineHeight: 1.5 },
          "text",
        ),
        createShapeElement("rectangle", 0, 1250, 1080, 100, "#1E293B"),
        createTextElement(
          "Your Name | Expert Title",
          80,
          1275,
          500,
          50,
          { fontSize: 18, fontWeight: 500, color: "#CBD5E1" },
          "text",
        ),
        createTextElement(
          "@yourhandle",
          580,
          1275,
          420,
          50,
          { fontSize: 18, fontWeight: 500, color: "#3B82F6", textAlign: "right" },
          "text",
        ),
      ],
    },
    {
      id: generateSlideId(),
      name: "Challenge",
      order: 1,
      background: { type: "solid", color: "#0F172A" },
      elements: [
        createShapeElement("rectangle", 0, 0, 1080, 180, "#1E293B"),
        createTextElement("01", 80, 60, 100, 60, { fontSize: 48, fontWeight: 700, color: "#3B82F6" }, "text"),
        createTextElement(
          "The Challenge",
          200,
          70,
          800,
          60,
          { fontSize: 32, fontWeight: 600, color: "#F8FAFC" },
          "heading",
        ),
        createTextElement(
          "Most businesses struggle with scaling because they lack a systematic approach to growth.",
          80,
          260,
          920,
          200,
          { fontSize: 36, fontWeight: 600, color: "#F8FAFC", lineHeight: 1.4 },
          "text",
        ),
        createShapeElement("rounded-rectangle", 80, 520, 440, 200, "#1E293B", { borderRadius: 12 }),
        createTextElement("73%", 110, 550, 380, 80, { fontSize: 56, fontWeight: 700, color: "#3B82F6" }, "text"),
        createTextElement(
          "of startups fail due to premature scaling",
          110,
          640,
          380,
          60,
          { fontSize: 18, fontWeight: 400, color: "#94A3B8", lineHeight: 1.4 },
          "text",
        ),
        createShapeElement("rounded-rectangle", 560, 520, 440, 200, "#1E293B", { borderRadius: 12 }),
        createTextElement("2.5x", 590, 550, 380, 80, { fontSize: 56, fontWeight: 700, color: "#3B82F6" }, "text"),
        createTextElement(
          "more likely to succeed with a framework",
          590,
          640,
          380,
          60,
          { fontSize: 18, fontWeight: 400, color: "#94A3B8", lineHeight: 1.4 },
          "text",
        ),
        createTextElement(
          "The good news? With the right framework, you can avoid these pitfalls and scale strategically.",
          80,
          780,
          920,
          120,
          { fontSize: 22, fontWeight: 400, color: "#CBD5E1", lineHeight: 1.5 },
          "text",
        ),
      ],
    },
    {
      id: generateSlideId(),
      name: "Framework",
      order: 2,
      background: { type: "solid", color: "#0F172A" },
      elements: [
        createShapeElement("rectangle", 0, 0, 1080, 180, "#1E293B"),
        createTextElement("02", 80, 60, 100, 60, { fontSize: 48, fontWeight: 700, color: "#3B82F6" }, "text"),
        createTextElement(
          "The Framework",
          200,
          70,
          800,
          60,
          { fontSize: 32, fontWeight: 600, color: "#F8FAFC" },
          "heading",
        ),
        createShapeElement("rounded-rectangle", 80, 240, 920, 150, "#1E293B", { borderRadius: 12 }),
        createTextElement(
          "1",
          110,
          280,
          80,
          70,
          { fontSize: 48, fontWeight: 700, color: "#3B82F6", textAlign: "center" },
          "text",
        ),
        createTextElement(
          "Foundation",
          200,
          270,
          760,
          50,
          { fontSize: 28, fontWeight: 600, color: "#F8FAFC" },
          "heading",
        ),
        createTextElement(
          "Build a solid operational base before scaling",
          200,
          320,
          760,
          50,
          { fontSize: 18, fontWeight: 400, color: "#94A3B8" },
          "text",
        ),
        createShapeElement("rounded-rectangle", 80, 420, 920, 150, "#1E293B", { borderRadius: 12 }),
        createTextElement(
          "2",
          110,
          460,
          80,
          70,
          { fontSize: 48, fontWeight: 700, color: "#3B82F6", textAlign: "center" },
          "text",
        ),
        createTextElement(
          "Validation",
          200,
          450,
          760,
          50,
          { fontSize: 28, fontWeight: 600, color: "#F8FAFC" },
          "heading",
        ),
        createTextElement(
          "Test and refine your growth hypotheses",
          200,
          500,
          760,
          50,
          { fontSize: 18, fontWeight: 400, color: "#94A3B8" },
          "text",
        ),
        createShapeElement("rounded-rectangle", 80, 600, 920, 150, "#1E293B", { borderRadius: 12 }),
        createTextElement(
          "3",
          110,
          640,
          80,
          70,
          { fontSize: 48, fontWeight: 700, color: "#3B82F6", textAlign: "center" },
          "text",
        ),
        createTextElement(
          "Acceleration",
          200,
          630,
          760,
          50,
          { fontSize: 28, fontWeight: 600, color: "#F8FAFC" },
          "heading",
        ),
        createTextElement(
          "Scale proven strategies with confidence",
          200,
          680,
          760,
          50,
          { fontSize: 18, fontWeight: 400, color: "#94A3B8" },
          "text",
        ),
        createShapeElement("rounded-rectangle", 80, 780, 920, 150, "#1E293B", { borderRadius: 12 }),
        createTextElement(
          "4",
          110,
          820,
          80,
          70,
          { fontSize: 48, fontWeight: 700, color: "#3B82F6", textAlign: "center" },
          "text",
        ),
        createTextElement(
          "Optimization",
          200,
          810,
          760,
          50,
          { fontSize: 28, fontWeight: 600, color: "#F8FAFC" },
          "heading",
        ),
        createTextElement(
          "Continuously improve and iterate",
          200,
          860,
          760,
          50,
          { fontSize: 18, fontWeight: 400, color: "#94A3B8" },
          "text",
        ),
      ],
    },
    {
      id: generateSlideId(),
      name: "Metrics",
      order: 3,
      background: { type: "solid", color: "#0F172A" },
      elements: [
        createShapeElement("rectangle", 0, 0, 1080, 180, "#1E293B"),
        createTextElement("03", 80, 60, 100, 60, { fontSize: 48, fontWeight: 700, color: "#3B82F6" }, "text"),
        createTextElement(
          "Key Metrics",
          200,
          70,
          800,
          60,
          { fontSize: 32, fontWeight: 600, color: "#F8FAFC" },
          "heading",
        ),
        createTextElement(
          "Track these metrics to measure your progress:",
          80,
          240,
          920,
          80,
          { fontSize: 24, fontWeight: 500, color: "#CBD5E1" },
          "text",
        ),
        createShapeElement("rounded-rectangle", 80, 360, 440, 280, "#1E293B", { borderRadius: 12 }),
        createTextElement(
          "Customer Acquisition Cost",
          110,
          400,
          380,
          50,
          { fontSize: 20, fontWeight: 600, color: "#F8FAFC" },
          "text",
        ),
        createTextElement("$45-65", 110, 460, 380, 70, { fontSize: 48, fontWeight: 700, color: "#3B82F6" }, "text"),
        createTextElement(
          "Target range for sustainable growth in B2B SaaS",
          110,
          540,
          380,
          80,
          { fontSize: 16, fontWeight: 400, color: "#94A3B8", lineHeight: 1.4 },
          "text",
        ),
        createShapeElement("rounded-rectangle", 560, 360, 440, 280, "#1E293B", { borderRadius: 12 }),
        createTextElement(
          "Monthly Recurring Revenue",
          590,
          400,
          380,
          50,
          { fontSize: 20, fontWeight: 600, color: "#F8FAFC" },
          "text",
        ),
        createTextElement("15-20%", 590, 460, 380, 70, { fontSize: 48, fontWeight: 700, color: "#3B82F6" }, "text"),
        createTextElement(
          "Month-over-month growth rate benchmark",
          590,
          540,
          380,
          80,
          { fontSize: 16, fontWeight: 400, color: "#94A3B8", lineHeight: 1.4 },
          "text",
        ),
        createShapeElement("rounded-rectangle", 80, 680, 920, 180, "#1E293B", { borderRadius: 12 }),
        createTextElement(
          "Customer Lifetime Value",
          110,
          720,
          400,
          50,
          { fontSize: 20, fontWeight: 600, color: "#F8FAFC" },
          "text",
        ),
        createTextElement("3:1", 110, 770, 200, 70, { fontSize: 48, fontWeight: 700, color: "#3B82F6" }, "text"),
        createTextElement(
          "Your LTV to CAC ratio should be at least 3:1 for healthy unit economics. This ensures profitability per customer.",
          320,
          730,
          650,
          110,
          { fontSize: 18, fontWeight: 400, color: "#94A3B8", lineHeight: 1.5 },
          "text",
        ),
      ],
    },
    {
      id: generateSlideId(),
      name: "CTA",
      order: 4,
      background: { type: "solid", color: "#0F172A" },
      elements: [
        createShapeElement("rectangle", 440, 300, 200, 6, "#3B82F6", { borderRadius: 3 }),
        createTextElement(
          "Ready to Scale\nYour Business?",
          80,
          360,
          920,
          180,
          { fontSize: 64, fontWeight: 700, color: "#F8FAFC", textAlign: "center", lineHeight: 1.2 },
          "heading",
        ),
        createTextElement(
          "Follow for more strategic insights on\nbusiness growth and scaling",
          80,
          570,
          920,
          100,
          { fontSize: 26, fontWeight: 400, color: "#94A3B8", textAlign: "center", lineHeight: 1.5 },
          "text",
        ),
        createShapeElement("rounded-rectangle", 340, 720, 400, 70, "#3B82F6", { borderRadius: 8 }),
        createTextElement(
          "Save This Post",
          340,
          735,
          400,
          50,
          { fontSize: 24, fontWeight: 600, color: "#FFFFFF", textAlign: "center" },
          "text",
        ),
        createShapeElement("rectangle", 0, 1250, 1080, 100, "#1E293B"),
        createTextElement(
          "Your Name | Expert Title",
          80,
          1275,
          500,
          50,
          { fontSize: 18, fontWeight: 500, color: "#CBD5E1" },
          "text",
        ),
        createTextElement(
          "@yourhandle",
          580,
          1275,
          420,
          50,
          { fontSize: 18, fontWeight: 500, color: "#3B82F6", textAlign: "right" },
          "text",
        ),
      ],
    },
  ],
}
