// ═══════════════════════════════════════════════════════════════════════════════
// Template: Purple Haze
// Professional business insights carousel
// ═══════════════════════════════════════════════════════════════════════════════

import type { CarouselTemplate } from "../carousel-designer-types"
import { generateSlideId, createTextElement, createShapeElement } from "./template-helpers"

export const purpleHazeTemplate: CarouselTemplate = {
  id: "purple-haze",
  name: "Purple Haze",
  description: "Professional business insights in a clean, corporate design.",
  category: "vibrant",
  isPremium: false,
  isCustom: false,
  palette: {
    id: "slate-corporate",
    name: "Slate Corporate",
    category: "professional",
    colors: {
      primary: "#1E293B",
      secondary: "#334155",
      accent: "#3B82F6",
      background: "#F9FAFB",
      text: "#0F172A",
      textSecondary: "#64748B",
    },
    gradient: { from: "#1E293B", to: "#0F172A", direction: "to-br" },
  },
  size: "portrait",
  defaultFonts: {
    heading: "'Inter', sans-serif",
    body: "'Inter', sans-serif",
  },
  tags: ["professional", "business", "insights", "corporate"],
  createdAt: Date.now(),
  updatedAt: Date.now(),
  slides: [
    {
      id: generateSlideId(),
      name: "Intro",
      order: 0,
      background: {
        type: "gradient",
        gradient: { from: "#1E293B", to: "#0F172A", direction: "to-br" },
        color: "#1E293B",
      },
      elements: [
        createShapeElement("line", 80, 520, 140, 4, "#3B82F6"),
        createTextElement(
          "STRATEGIC\nINSIGHTS",
          80,
          580,
          920,
          220,
          { fontSize: 64, fontWeight: 700, textAlign: "center", color: "#FFFFFF", lineHeight: 1.1 },
          "heading",
        ),
        createTextElement(
          "Swipe for actionable business insights",
          80,
          840,
          920,
          50,
          { fontSize: 22, fontWeight: 400, textAlign: "center", color: "rgba(255,255,255,0.85)" },
          "text",
        ),
        createShapeElement("line", 480, 960, 140, 4, "#3B82F6"),
      ],
    },
    {
      id: generateSlideId(),
      name: "Idea 1",
      order: 1,
      background: { type: "solid", color: "#F9FAFB" },
      elements: [
        createShapeElement("rounded-rectangle", 80, 240, 100, 100, "#1E293B", { borderRadius: 16 }),
        createTextElement(
          "01",
          80,
          262,
          100,
          60,
          { fontSize: 36, fontWeight: 700, textAlign: "center", color: "#FFFFFF" },
          "text",
        ),
        createTextElement(
          "Think Different",
          80,
          390,
          920,
          80,
          { fontSize: 48, fontWeight: 700, color: "#0F172A" },
          "heading",
        ),
        createTextElement(
          "Challenge conventional wisdom. The best ideas often come from questioning what everyone else accepts as truth.",
          80,
          520,
          920,
          180,
          { fontSize: 26, fontWeight: 400, color: "#334155", lineHeight: 1.6 },
          "text",
        ),
        createShapeElement("rounded-rectangle", 80, 780, 920, 220, "#FFFFFF", { borderRadius: 16 }),
        createTextElement(
          "KEY TAKEAWAY",
          120,
          820,
          840,
          30,
          { fontSize: 13, fontWeight: 600, letterSpacing: 2, color: "#64748B", textTransform: "uppercase" },
          "text",
        ),
        createTextElement(
          "Question assumptions and explore new perspectives to unlock innovation",
          120,
          860,
          840,
          120,
          { fontSize: 20, fontWeight: 500, color: "#0F172A", lineHeight: 1.5 },
          "text",
        ),
      ],
    },
    {
      id: generateSlideId(),
      name: "Idea 2",
      order: 2,
      background: { type: "solid", color: "#F9FAFB" },
      elements: [
        createShapeElement("rounded-rectangle", 80, 240, 100, 100, "#334155", { borderRadius: 16 }),
        createTextElement(
          "02",
          80,
          262,
          100,
          60,
          { fontSize: 36, fontWeight: 700, textAlign: "center", color: "#FFFFFF" },
          "text",
        ),
        createTextElement(
          "Embrace Failure",
          80,
          390,
          920,
          80,
          { fontSize: 48, fontWeight: 700, color: "#0F172A" },
          "heading",
        ),
        createTextElement(
          "Every failure is a stepping stone to success. Learn fast, iterate faster, and never stop experimenting with new approaches.",
          80,
          520,
          920,
          180,
          { fontSize: 26, fontWeight: 400, color: "#334155", lineHeight: 1.6 },
          "text",
        ),
        createShapeElement("rounded-rectangle", 80, 780, 920, 220, "#FFFFFF", { borderRadius: 16 }),
        createTextElement(
          "KEY TAKEAWAY",
          120,
          820,
          840,
          30,
          { fontSize: 13, fontWeight: 600, letterSpacing: 2, color: "#64748B", textTransform: "uppercase" },
          "text",
        ),
        createTextElement(
          "Turn setbacks into learning opportunities that accelerate growth",
          120,
          860,
          840,
          120,
          { fontSize: 20, fontWeight: 500, color: "#0F172A", lineHeight: 1.5 },
          "text",
        ),
      ],
    },
    {
      id: generateSlideId(),
      name: "Idea 3",
      order: 3,
      background: { type: "solid", color: "#F9FAFB" },
      elements: [
        createShapeElement("rounded-rectangle", 80, 240, 100, 100, "#3B82F6", { borderRadius: 16 }),
        createTextElement(
          "03",
          80,
          262,
          100,
          60,
          { fontSize: 36, fontWeight: 700, textAlign: "center", color: "#FFFFFF" },
          "text",
        ),
        createTextElement(
          "Stay Curious",
          80,
          390,
          920,
          80,
          { fontSize: 48, fontWeight: 700, color: "#0F172A" },
          "heading",
        ),
        createTextElement(
          "The most successful people never stop asking questions. Curiosity is the fuel that drives continuous innovation and improvement.",
          80,
          520,
          920,
          180,
          { fontSize: 26, fontWeight: 400, color: "#334155", lineHeight: 1.6 },
          "text",
        ),
        createShapeElement("rounded-rectangle", 80, 780, 920, 220, "#FFFFFF", { borderRadius: 16 }),
        createTextElement(
          "KEY TAKEAWAY",
          120,
          820,
          840,
          30,
          { fontSize: 13, fontWeight: 600, letterSpacing: 2, color: "#64748B", textTransform: "uppercase" },
          "text",
        ),
        createTextElement(
          "Cultivate a mindset of continuous learning and exploration",
          120,
          860,
          840,
          120,
          { fontSize: 20, fontWeight: 500, color: "#0F172A", lineHeight: 1.5 },
          "text",
        ),
      ],
    },
    {
      id: generateSlideId(),
      name: "Quote",
      order: 4,
      background: {
        type: "gradient",
        gradient: { from: "#1E293B", to: "#0F172A", direction: "to-br" },
        color: "#1E293B",
      },
      elements: [
        createShapeElement("line", 120, 520, 4, 280, "rgba(59,130,246,0.6)"),
        createTextElement(
          "Creativity is intelligence having fun.",
          180,
          560,
          800,
          220,
          { fontSize: 42, fontWeight: 600, textAlign: "left", color: "#FFFFFF", lineHeight: 1.4 },
          "text",
        ),
        createTextElement(
          "— Albert Einstein",
          180,
          820,
          800,
          40,
          { fontSize: 20, fontWeight: 500, color: "rgba(255,255,255,0.75)" },
          "text",
        ),
      ],
    },
    {
      id: generateSlideId(),
      name: "Idea 4",
      order: 5,
      background: { type: "solid", color: "#F9FAFB" },
      elements: [
        createShapeElement("rounded-rectangle", 80, 240, 100, 100, "#475569", { borderRadius: 16 }),
        createTextElement(
          "04",
          80,
          262,
          100,
          60,
          { fontSize: 36, fontWeight: 700, textAlign: "center", color: "#FFFFFF" },
          "text",
        ),
        createTextElement(
          "Take Action",
          80,
          390,
          920,
          80,
          { fontSize: 48, fontWeight: 700, color: "#0F172A" },
          "heading",
        ),
        createTextElement(
          "Ideas without execution are just dreams. Start small, but start today. Progress comes from consistent action.",
          80,
          520,
          920,
          180,
          { fontSize: 26, fontWeight: 400, color: "#334155", lineHeight: 1.6 },
          "text",
        ),
        createShapeElement("rounded-rectangle", 80, 780, 920, 220, "#FFFFFF", { borderRadius: 16 }),
        createTextElement(
          "KEY TAKEAWAY",
          120,
          820,
          840,
          30,
          { fontSize: 13, fontWeight: 600, letterSpacing: 2, color: "#64748B", textTransform: "uppercase" },
          "text",
        ),
        createTextElement(
          "Transform ideas into results through consistent, deliberate action",
          120,
          860,
          840,
          120,
          { fontSize: 20, fontWeight: 500, color: "#0F172A", lineHeight: 1.5 },
          "text",
        ),
      ],
    },
    {
      id: generateSlideId(),
      name: "Summary",
      order: 6,
      background: { type: "solid", color: "#0F172A" },
      elements: [
        createTextElement(
          "KEY TAKEAWAYS",
          80,
          380,
          920,
          50,
          { fontSize: 18, fontWeight: 700, textAlign: "center", color: "#3B82F6", letterSpacing: 3 },
          "text",
        ),
        createShapeElement("line", 440, 450, 200, 2, "#3B82F6"),
        createTextElement(
          "1. Think Different\n2. Embrace Failure\n3. Stay Curious\n4. Take Action",
          80,
          540,
          920,
          360,
          { fontSize: 32, fontWeight: 600, textAlign: "center", color: "#FFFFFF", lineHeight: 2 },
          "text",
        ),
        createTextElement(
          "Apply these principles to drive success",
          80,
          940,
          920,
          50,
          { fontSize: 20, fontWeight: 400, textAlign: "center", color: "#94A3B8" },
          "text",
        ),
      ],
    },
    {
      id: generateSlideId(),
      name: "Outro",
      order: 7,
      background: {
        type: "gradient",
        gradient: { from: "#1E293B", to: "#0F172A", direction: "to-r" },
        color: "#1E293B",
      },
      elements: [
        createTextElement(
          "Thank you",
          80,
          600,
          920,
          70,
          { fontSize: 44, fontWeight: 700, textAlign: "center", color: "#FFFFFF" },
          "heading",
        ),
        createTextElement(
          "Like | Comment | Share | Follow",
          80,
          690,
          920,
          50,
          { fontSize: 20, fontWeight: 400, textAlign: "center", color: "rgba(255,255,255,0.85)" },
          "text",
        ),
        createShapeElement("rounded-rectangle", 340, 800, 400, 60, "#FFFFFF", { borderRadius: 8 }),
        createTextElement(
          "@yourhandle",
          340,
          810,
          400,
          40,
          { fontSize: 24, fontWeight: 700, textAlign: "center", color: "#1E293B" },
          "text",
        ),
      ],
    },
  ],
}
