// ═══════════════════════════════════════════════════════════════════════════════
// Template: Quote Cards
// Elegant quote presentation for thought leadership
// ═══════════════════════════════════════════════════════════════════════════════

import type { CarouselTemplate } from "../carousel-designer-types"
import { generateSlideId, createTextElement, createShapeElement } from "./template-helpers"

export const quoteCardsTemplate: CarouselTemplate = {
  id: "quote-cards",
  name: "Quote Cards",
  description: "Elegant quote presentation for sharing insights and thought leadership.",
  category: "storytelling",
  isPremium: false,
  isCustom: false,
  palette: {
    id: "navy-charcoal",
    name: "Navy Charcoal",
    category: "professional",
    colors: {
      primary: "#0F172A",
      secondary: "#334155",
      accent: "#3B82F6",
      background: "#F8FAFC",
      text: "#1F2937",
      textSecondary: "#64748B",
    },
    gradient: { from: "#0F172A", to: "#1E293B", direction: "to-br" },
  },
  size: "portrait",
  defaultFonts: {
    heading: "'Inter', sans-serif",
    body: "'Georgia', serif",
  },
  tags: ["quotes", "inspiration", "thought-leadership", "elegant"],
  createdAt: Date.now(),
  updatedAt: Date.now(),
  slides: [
    {
      id: generateSlideId(),
      name: "Cover",
      order: 0,
      background: {
        type: "gradient",
        gradient: { from: "#0F172A", to: "#1E293B", direction: "to-br" },
      },
      elements: [
        createShapeElement("line", 80, 460, 120, 3, "#3B82F6"),
        createTextElement(
          "WISDOM SERIES",
          80,
          500,
          920,
          40,
          { fontSize: 16, fontWeight: 600, letterSpacing: 4, color: "#94A3B8", textTransform: "uppercase" },
          "text",
        ),
        createTextElement(
          "5 Powerful Quotes\non Leadership",
          80,
          600,
          920,
          220,
          { fontSize: 58, fontWeight: 700, lineHeight: 1.15, color: "#FFFFFF", textAlign: "center" },
          "heading",
        ),
        createTextElement(
          "Insights for modern professionals",
          80,
          860,
          920,
          45,
          { fontSize: 22, fontWeight: 400, color: "#CBD5E1", textAlign: "center" },
          "subheading",
        ),
        createShapeElement("line", 480, 960, 120, 3, "#3B82F6"),
      ],
    },
    {
      id: generateSlideId(),
      name: "Quote 1",
      order: 1,
      background: { type: "solid", color: "#F8FAFC" },
      elements: [
        createShapeElement("rounded-rectangle", 80, 320, 920, 880, "#FFFFFF", {
          borderRadius: 16,
        }),
        createTextElement(
          '"',
          120,
          340,
          120,
          120,
          { fontSize: 140, fontWeight: 400, color: "#3B82F6", opacity: 0.12 },
          "text",
        ),
        createTextElement(
          "The function of leadership is to produce more leaders, not more followers.",
          180,
          560,
          720,
          260,
          {
            fontSize: 34,
            fontWeight: 500,
            lineHeight: 1.5,
            textAlign: "center",
            fontFamily: "'Georgia', serif",
            color: "#1F2937",
          },
          "quote",
        ),
        createShapeElement("line", 440, 860, 200, 2, "#3B82F6"),
        createTextElement(
          "Ralph Nader",
          80,
          920,
          920,
          40,
          { fontSize: 22, fontWeight: 600, textAlign: "center", color: "#1F2937" },
          "text",
        ),
        createTextElement(
          "Political Activist",
          80,
          970,
          920,
          35,
          { fontSize: 18, fontWeight: 400, textAlign: "center", color: "#64748B" },
          "text",
        ),
      ],
    },
    {
      id: generateSlideId(),
      name: "Quote 2",
      order: 2,
      background: { type: "solid", color: "#F8FAFC" },
      elements: [
        createShapeElement("rounded-rectangle", 80, 300, 920, 900, "#FFFFFF", {
          borderRadius: 16,
        }),
        createTextElement(
          '"',
          120,
          320,
          120,
          120,
          { fontSize: 140, fontWeight: 400, color: "#3B82F6", opacity: 0.12 },
          "text",
        ),
        createTextElement(
          "Leadership is not about being in charge. It's about taking care of those in your charge.",
          180,
          540,
          720,
          280,
          {
            fontSize: 34,
            fontWeight: 500,
            lineHeight: 1.5,
            textAlign: "center",
            fontFamily: "'Georgia', serif",
            color: "#1F2937",
          },
          "quote",
        ),
        createShapeElement("line", 440, 880, 200, 2, "#3B82F6"),
        createTextElement(
          "Simon Sinek",
          80,
          940,
          920,
          40,
          { fontSize: 22, fontWeight: 600, textAlign: "center", color: "#1F2937" },
          "text",
        ),
        createTextElement(
          "Author & Speaker",
          80,
          990,
          920,
          35,
          { fontSize: 18, fontWeight: 400, textAlign: "center", color: "#64748B" },
          "text",
        ),
      ],
    },
    {
      id: generateSlideId(),
      name: "Quote 3",
      order: 3,
      background: { type: "solid", color: "#F8FAFC" },
      elements: [
        createShapeElement("rounded-rectangle", 80, 280, 920, 940, "#FFFFFF", {
          borderRadius: 16,
        }),
        createTextElement(
          '"',
          120,
          300,
          120,
          120,
          { fontSize: 140, fontWeight: 400, color: "#3B82F6", opacity: 0.12 },
          "text",
        ),
        createTextElement(
          "The greatest leader is not necessarily the one who does the greatest things. They get the people to do the greatest things.",
          180,
          520,
          720,
          320,
          {
            fontSize: 32,
            fontWeight: 500,
            lineHeight: 1.5,
            textAlign: "center",
            fontFamily: "'Georgia', serif",
            color: "#1F2937",
          },
          "quote",
        ),
        createShapeElement("line", 440, 900, 200, 2, "#3B82F6"),
        createTextElement(
          "Ronald Reagan",
          80,
          960,
          920,
          40,
          { fontSize: 22, fontWeight: 600, textAlign: "center", color: "#1F2937" },
          "text",
        ),
        createTextElement(
          "40th President",
          80,
          1010,
          920,
          35,
          { fontSize: 18, fontWeight: 400, textAlign: "center", color: "#64748B" },
          "text",
        ),
      ],
    },
    {
      id: generateSlideId(),
      name: "Quote 4",
      order: 4,
      background: { type: "solid", color: "#F8FAFC" },
      elements: [
        createShapeElement("rounded-rectangle", 80, 340, 920, 860, "#FFFFFF", {
          borderRadius: 16,
        }),
        createTextElement(
          '"',
          120,
          360,
          120,
          120,
          { fontSize: 140, fontWeight: 400, color: "#3B82F6", opacity: 0.12 },
          "text",
        ),
        createTextElement(
          "A leader is one who knows the way, goes the way, and shows the way.",
          180,
          580,
          720,
          240,
          {
            fontSize: 34,
            fontWeight: 500,
            lineHeight: 1.5,
            textAlign: "center",
            fontFamily: "'Georgia', serif",
            color: "#1F2937",
          },
          "quote",
        ),
        createShapeElement("line", 440, 880, 200, 2, "#3B82F6"),
        createTextElement(
          "John C. Maxwell",
          80,
          940,
          920,
          40,
          { fontSize: 22, fontWeight: 600, textAlign: "center", color: "#1F2937" },
          "text",
        ),
        createTextElement(
          "Leadership Expert",
          80,
          990,
          920,
          35,
          { fontSize: 18, fontWeight: 400, textAlign: "center", color: "#64748B" },
          "text",
        ),
      ],
    },
    {
      id: generateSlideId(),
      name: "Quote 5",
      order: 5,
      background: { type: "solid", color: "#F8FAFC" },
      elements: [
        createShapeElement("rounded-rectangle", 80, 280, 920, 940, "#FFFFFF", {
          borderRadius: 16,
        }),
        createTextElement(
          '"',
          120,
          300,
          120,
          120,
          { fontSize: 140, fontWeight: 400, color: "#3B82F6", opacity: 0.12 },
          "text",
        ),
        createTextElement(
          "Before you are a leader, success is all about growing yourself. When you become a leader, success is all about growing others.",
          180,
          520,
          720,
          320,
          {
            fontSize: 32,
            fontWeight: 500,
            lineHeight: 1.5,
            textAlign: "center",
            fontFamily: "'Georgia', serif",
            color: "#1F2937",
          },
          "quote",
        ),
        createShapeElement("line", 440, 900, 200, 2, "#3B82F6"),
        createTextElement(
          "Jack Welch",
          80,
          960,
          920,
          40,
          { fontSize: 22, fontWeight: 600, textAlign: "center", color: "#1F2937" },
          "text",
        ),
        createTextElement(
          "Former CEO of GE",
          80,
          1010,
          920,
          35,
          { fontSize: 18, fontWeight: 400, textAlign: "center", color: "#64748B" },
          "text",
        ),
      ],
    },
    {
      id: generateSlideId(),
      name: "Outro",
      order: 6,
      background: {
        type: "gradient",
        gradient: { from: "#0F172A", to: "#1E293B", direction: "to-br" },
      },
      elements: [
        createShapeElement("line", 480, 580, 120, 3, "#3B82F6"),
        createTextElement(
          "Thank you",
          80,
          660,
          920,
          70,
          { fontSize: 44, fontWeight: 700, textAlign: "center", color: "#FFFFFF" },
          "heading",
        ),
        createTextElement(
          "Like | Save | Share | Follow",
          80,
          750,
          920,
          50,
          { fontSize: 20, fontWeight: 400, textAlign: "center", color: "#CBD5E1" },
          "text",
        ),
        createShapeElement("rounded-rectangle", 340, 860, 400, 60, "#FFFFFF", { borderRadius: 8 }),
        createTextElement(
          "@yourhandle",
          340,
          870,
          400,
          40,
          { fontSize: 24, fontWeight: 700, textAlign: "center", color: "#0F172A" },
          "text",
        ),
      ],
    },
  ],
}
