// ═══════════════════════════════════════════════════════════════════════════════
// Template: Step by Step
// Professional tutorial and process guide
// ═══════════════════════════════════════════════════════════════════════════════

import type { CarouselTemplate } from "../carousel-designer-types"
import { generateSlideId, createTextElement, createShapeElement } from "./template-helpers"

export const stepByStepTemplate: CarouselTemplate = {
  id: "step-by-step",
  name: "Step by Step",
  description: "Professional step-by-step format for tutorials and process guides.",
  category: "educational",
  isPremium: false,
  isCustom: false,
  palette: {
    id: "charcoal-teal",
    name: "Charcoal Teal",
    category: "professional",
    colors: {
      primary: "#1F2937",
      secondary: "#115E59",
      accent: "#14B8A6",
      background: "#F9FAFB",
      text: "#111827",
      textSecondary: "#4B5563",
    },
    gradient: { from: "#1F2937", to: "#115E59", direction: "to-br" },
  },
  size: "portrait",
  defaultFonts: {
    heading: "'Inter', sans-serif",
    body: "'Inter', sans-serif",
  },
  tags: ["tutorial", "howto", "process", "steps", "professional"],
  createdAt: Date.now(),
  updatedAt: Date.now(),
  slides: [
    {
      id: generateSlideId(),
      name: "Cover",
      order: 0,
      background: {
        type: "gradient",
        gradient: { from: "#1F2937", to: "#115E59", direction: "to-br" },
      },
      elements: [
        createShapeElement("line", 440, 440, 200, 4, "#14B8A6"),
        createTextElement(
          "STEP-BY-STEP",
          80,
          500,
          920,
          50,
          {
            fontSize: 18,
            fontWeight: 700,
            letterSpacing: 4,
            color: "#14B8A6",
            textTransform: "uppercase",
            textAlign: "center",
          },
          "text",
        ),
        createTextElement(
          "How to Master\nYour Topic",
          80,
          580,
          920,
          180,
          { fontSize: 56, fontWeight: 800, lineHeight: 1.1, color: "#FFFFFF", textAlign: "center" },
          "heading",
        ),
        createTextElement(
          "A complete guide in 5 actionable steps",
          80,
          800,
          920,
          50,
          { fontSize: 22, fontWeight: 400, color: "rgba(255,255,255,0.85)", textAlign: "center" },
          "subheading",
        ),
      ],
    },
    {
      id: generateSlideId(),
      name: "Step 1",
      order: 1,
      background: { type: "solid", color: "#F9FAFB" },
      elements: [
        createShapeElement("rounded-rectangle", 80, 180, 120, 120, "#1F2937", { borderRadius: 16 }),
        createTextElement(
          "01",
          80,
          205,
          120,
          75,
          { fontSize: 48, fontWeight: 800, textAlign: "center", color: "#FFFFFF" },
          "text",
        ),
        createTextElement(
          "Step Title Here",
          230,
          205,
          770,
          75,
          { fontSize: 40, fontWeight: 700, color: "#111827" },
          "heading",
        ),
        createShapeElement("line", 80, 360, 920, 2, "#E5E7EB"),
        createTextElement(
          "Detailed explanation of how to complete this step. Include specific instructions, best practices, and important considerations.",
          80,
          430,
          920,
          160,
          { fontSize: 24, fontWeight: 400, lineHeight: 1.6, color: "#374151" },
          "body",
        ),
        createShapeElement("rounded-rectangle", 80, 670, 920, 240, "#FFFFFF", { borderRadius: 12 }),
        createTextElement(
          "ACTION ITEM",
          120,
          710,
          840,
          30,
          { fontSize: 13, fontWeight: 600, letterSpacing: 2, color: "#115E59", textTransform: "uppercase" },
          "text",
        ),
        createTextElement(
          "What to do right now to successfully implement this step",
          120,
          755,
          840,
          130,
          { fontSize: 22, fontWeight: 500, color: "#111827", lineHeight: 1.5 },
          "text",
        ),
        createTextElement(
          "Step 1 of 5",
          80,
          1240,
          920,
          30,
          { fontSize: 15, fontWeight: 500, textAlign: "center", color: "#9CA3AF" },
          "text",
        ),
      ],
    },
    {
      id: generateSlideId(),
      name: "Step 2",
      order: 2,
      background: { type: "solid", color: "#F9FAFB" },
      elements: [
        createShapeElement("rounded-rectangle", 80, 180, 120, 120, "#115E59", { borderRadius: 16 }),
        createTextElement(
          "02",
          80,
          205,
          120,
          75,
          { fontSize: 48, fontWeight: 800, textAlign: "center", color: "#FFFFFF" },
          "text",
        ),
        createTextElement(
          "Second Step Title",
          230,
          205,
          770,
          75,
          { fontSize: 40, fontWeight: 700, color: "#111827" },
          "heading",
        ),
        createShapeElement("line", 80, 360, 920, 2, "#E5E7EB"),
        createTextElement(
          "Build on the first step with the next logical phase. Provide clear guidance and actionable advice for this stage of the process.",
          80,
          430,
          920,
          160,
          { fontSize: 24, fontWeight: 400, lineHeight: 1.6, color: "#374151" },
          "body",
        ),
        createShapeElement("rounded-rectangle", 80, 670, 920, 240, "#FFFFFF", { borderRadius: 12 }),
        createTextElement(
          "ACTION ITEM",
          120,
          710,
          840,
          30,
          { fontSize: 13, fontWeight: 600, letterSpacing: 2, color: "#115E59", textTransform: "uppercase" },
          "text",
        ),
        createTextElement(
          "Specific action to complete for this critical second step",
          120,
          755,
          840,
          130,
          { fontSize: 22, fontWeight: 500, color: "#111827", lineHeight: 1.5 },
          "text",
        ),
        createTextElement(
          "Step 2 of 5",
          80,
          1240,
          920,
          30,
          { fontSize: 15, fontWeight: 500, textAlign: "center", color: "#9CA3AF" },
          "text",
        ),
      ],
    },
    {
      id: generateSlideId(),
      name: "Step 3",
      order: 3,
      background: { type: "solid", color: "#F9FAFB" },
      elements: [
        createShapeElement("rounded-rectangle", 80, 180, 120, 120, "#14B8A6", { borderRadius: 16 }),
        createTextElement(
          "03",
          80,
          205,
          120,
          75,
          { fontSize: 48, fontWeight: 800, textAlign: "center", color: "#FFFFFF" },
          "text",
        ),
        createTextElement(
          "Third Step Title",
          230,
          205,
          770,
          75,
          { fontSize: 40, fontWeight: 700, color: "#111827" },
          "heading",
        ),
        createShapeElement("line", 80, 360, 920, 2, "#E5E7EB"),
        createTextElement(
          "Now implement the core of the process. Focus on quality execution and attention to detail for optimal results.",
          80,
          430,
          920,
          160,
          { fontSize: 24, fontWeight: 400, lineHeight: 1.6, color: "#374151" },
          "body",
        ),
        createShapeElement("rounded-rectangle", 80, 670, 920, 240, "#FFFFFF", { borderRadius: 12 }),
        createTextElement(
          "ACTION ITEM",
          120,
          710,
          840,
          30,
          { fontSize: 13, fontWeight: 600, letterSpacing: 2, color: "#115E59", textTransform: "uppercase" },
          "text",
        ),
        createTextElement(
          "Execute this core action with focus and precision for best results",
          120,
          755,
          840,
          130,
          { fontSize: 22, fontWeight: 500, color: "#111827", lineHeight: 1.5 },
          "text",
        ),
        createTextElement(
          "Step 3 of 5",
          80,
          1240,
          920,
          30,
          { fontSize: 15, fontWeight: 500, textAlign: "center", color: "#9CA3AF" },
          "text",
        ),
      ],
    },
    {
      id: generateSlideId(),
      name: "Step 4",
      order: 4,
      background: { type: "solid", color: "#F9FAFB" },
      elements: [
        createShapeElement("rounded-rectangle", 80, 180, 120, 120, "#0D9488", { borderRadius: 16 }),
        createTextElement(
          "04",
          80,
          205,
          120,
          75,
          { fontSize: 48, fontWeight: 800, textAlign: "center", color: "#FFFFFF" },
          "text",
        ),
        createTextElement(
          "Fourth Step Title",
          230,
          205,
          770,
          75,
          { fontSize: 40, fontWeight: 700, color: "#111827" },
          "heading",
        ),
        createShapeElement("line", 80, 360, 920, 2, "#E5E7EB"),
        createTextElement(
          "Refine and optimize your work. Make adjustments, test thoroughly, and ensure everything performs as expected.",
          80,
          430,
          920,
          160,
          { fontSize: 24, fontWeight: 400, lineHeight: 1.6, color: "#374151" },
          "body",
        ),
        createShapeElement("rounded-rectangle", 80, 670, 920, 240, "#FFFFFF", { borderRadius: 12 }),
        createTextElement(
          "ACTION ITEM",
          120,
          710,
          840,
          30,
          { fontSize: 13, fontWeight: 600, letterSpacing: 2, color: "#115E59", textTransform: "uppercase" },
          "text",
        ),
        createTextElement(
          "Review and refine your implementation for optimal performance",
          120,
          755,
          840,
          130,
          { fontSize: 22, fontWeight: 500, color: "#111827", lineHeight: 1.5 },
          "text",
        ),
        createTextElement(
          "Step 4 of 5",
          80,
          1240,
          920,
          30,
          { fontSize: 15, fontWeight: 500, textAlign: "center", color: "#9CA3AF" },
          "text",
        ),
      ],
    },
    {
      id: generateSlideId(),
      name: "Step 5",
      order: 5,
      background: { type: "solid", color: "#F9FAFB" },
      elements: [
        createShapeElement("rounded-rectangle", 80, 180, 120, 120, "#2DD4BF", { borderRadius: 16 }),
        createTextElement(
          "05",
          80,
          205,
          120,
          75,
          { fontSize: 48, fontWeight: 800, textAlign: "center", color: "#111827" },
          "text",
        ),
        createTextElement(
          "Final Step Title",
          230,
          205,
          770,
          75,
          { fontSize: 40, fontWeight: 700, color: "#111827" },
          "heading",
        ),
        createShapeElement("line", 80, 360, 920, 2, "#E5E7EB"),
        createTextElement(
          "Complete final touches, verify everything works perfectly, and you're ready to launch. Celebrate your achievement!",
          80,
          430,
          920,
          160,
          { fontSize: 24, fontWeight: 400, lineHeight: 1.6, color: "#374151" },
          "body",
        ),
        createShapeElement("rounded-rectangle", 80, 670, 920, 240, "#FFFFFF", { borderRadius: 12 }),
        createTextElement(
          "ACTION ITEM",
          120,
          710,
          840,
          30,
          { fontSize: 13, fontWeight: 600, letterSpacing: 2, color: "#115E59", textTransform: "uppercase" },
          "text",
        ),
        createTextElement(
          "Launch and share your success with confidence!",
          120,
          755,
          840,
          130,
          { fontSize: 22, fontWeight: 500, color: "#111827", lineHeight: 1.5 },
          "text",
        ),
        createTextElement(
          "Step 5 of 5",
          80,
          1240,
          920,
          30,
          { fontSize: 15, fontWeight: 500, textAlign: "center", color: "#9CA3AF" },
          "text",
        ),
      ],
    },
    {
      id: generateSlideId(),
      name: "Complete",
      order: 6,
      background: {
        type: "gradient",
        gradient: { from: "#1F2937", to: "#115E59", direction: "to-br" },
      },
      elements: [
        createShapeElement("line", 440, 480, 200, 4, "#14B8A6"),
        createTextElement(
          "COMPLETE",
          80,
          540,
          920,
          80,
          { fontSize: 56, fontWeight: 800, textAlign: "center", color: "#FFFFFF" },
          "heading",
        ),
        createTextElement(
          "You've mastered all 5 steps",
          80,
          650,
          920,
          60,
          { fontSize: 24, fontWeight: 400, textAlign: "center", color: "rgba(255,255,255,0.85)" },
          "text",
        ),
        createShapeElement("rounded-rectangle", 340, 760, 400, 60, "#14B8A6", { borderRadius: 8 }),
        createTextElement(
          "@yourhandle",
          340,
          770,
          400,
          40,
          { fontSize: 24, fontWeight: 700, textAlign: "center", color: "#1F2937" },
          "text",
        ),
      ],
    },
  ],
}
