// ═══════════════════════════════════════════════════════════════════════════════
// Template: Tips & Tricks
// Professional numbered tips format
// ═══════════════════════════════════════════════════════════════════════════════

import type { CarouselTemplate } from "../carousel-designer-types"
import { generateSlideId, createTextElement, createShapeElement } from "./template-helpers"

export const tipsTricksTemplate: CarouselTemplate = {
  id: "tips-tricks",
  name: "Tips & Tricks",
  description: "Professional numbered format for tips, tricks, and how-to guides.",
  category: "tips-tricks",
  isPremium: false,
  isCustom: false,
  palette: {
    id: "navy-teal",
    name: "Navy Teal",
    category: "professional",
    colors: {
      primary: "#1E3A8A",
      secondary: "#115E59",
      accent: "#0891B2",
      background: "#F8FAFC",
      text: "#0F172A",
      textSecondary: "#475569",
    },
    gradient: { from: "#1E3A8A", to: "#115E59", direction: "to-br" },
  },
  size: "portrait",
  defaultFonts: {
    heading: "'Inter', sans-serif",
    body: "'Inter', sans-serif",
  },
  tags: ["tips", "howto", "listicle", "professional"],
  createdAt: Date.now(),
  updatedAt: Date.now(),
  slides: [
    {
      id: generateSlideId(),
      name: "Cover",
      order: 0,
      background: {
        type: "gradient",
        gradient: { from: "#1E3A8A", to: "#115E59", direction: "to-br" },
      },
      elements: [
        createTextElement(
          "7 TIPS",
          80,
          440,
          920,
          120,
          { fontSize: 72, fontWeight: 800, color: "#FFFFFF", textAlign: "center" },
          "heading",
        ),
        createShapeElement("line", 440, 580, 200, 4, "#0891B2"),
        createTextElement(
          "to Achieve Your Goals",
          80,
          640,
          920,
          100,
          { fontSize: 42, fontWeight: 700, color: "#FFFFFF", textAlign: "center" },
          "heading",
        ),
        createTextElement(
          "A practical guide for professionals",
          80,
          760,
          920,
          50,
          { fontSize: 22, fontWeight: 400, color: "rgba(255,255,255,0.85)", textAlign: "center" },
          "subheading",
        ),
      ],
    },
    {
      id: generateSlideId(),
      name: "Tip 1",
      order: 1,
      background: { type: "solid", color: "#F8FAFC" },
      elements: [
        createShapeElement("rounded-rectangle", 80, 200, 110, 110, "#1E3A8A", { borderRadius: 16 }),
        createTextElement(
          "01",
          80,
          222,
          110,
          70,
          { fontSize: 48, fontWeight: 800, textAlign: "center", color: "#FFFFFF" },
          "text",
        ),
        createTextElement(
          "Your First Tip Title",
          220,
          222,
          780,
          70,
          { fontSize: 38, fontWeight: 700, color: "#0F172A" },
          "heading",
        ),
        createShapeElement("line", 80, 370, 920, 2, "#E2E8F0"),
        createTextElement(
          "Detailed explanation of the tip with actionable advice. Make it specific, practical, and immediately applicable to create real value.",
          80,
          440,
          920,
          160,
          { fontSize: 24, fontWeight: 400, lineHeight: 1.6, color: "#334155" },
          "body",
        ),
        createShapeElement("rounded-rectangle", 80, 680, 920, 220, "#FFFFFF", { borderRadius: 12 }),
        createTextElement(
          "ACTION STEP",
          120,
          720,
          840,
          30,
          { fontSize: 13, fontWeight: 600, letterSpacing: 2, color: "#115E59", textTransform: "uppercase" },
          "text",
        ),
        createTextElement(
          "Specific action to take right now to implement this tip successfully",
          120,
          765,
          840,
          110,
          { fontSize: 22, fontWeight: 500, color: "#0F172A", lineHeight: 1.5 },
          "text",
        ),
        createTextElement(
          "1 of 7",
          80,
          1240,
          920,
          30,
          { fontSize: 15, fontWeight: 500, textAlign: "center", color: "#94A3B8" },
          "text",
        ),
      ],
    },
    {
      id: generateSlideId(),
      name: "Tip 2",
      order: 2,
      background: { type: "solid", color: "#F8FAFC" },
      elements: [
        createShapeElement("rounded-rectangle", 80, 200, 110, 110, "#115E59", { borderRadius: 16 }),
        createTextElement(
          "02",
          80,
          222,
          110,
          70,
          { fontSize: 48, fontWeight: 800, textAlign: "center", color: "#FFFFFF" },
          "text",
        ),
        createTextElement(
          "Second Tip Title",
          220,
          222,
          780,
          70,
          { fontSize: 38, fontWeight: 700, color: "#0F172A" },
          "heading",
        ),
        createShapeElement("line", 80, 370, 920, 2, "#E2E8F0"),
        createTextElement(
          "Continue with your second valuable tip. Provide clear guidance that builds on the first tip and adds new dimensions to the strategy.",
          80,
          440,
          920,
          160,
          { fontSize: 24, fontWeight: 400, lineHeight: 1.6, color: "#334155" },
          "body",
        ),
        createShapeElement("rounded-rectangle", 80, 680, 920, 220, "#FFFFFF", { borderRadius: 12 }),
        createTextElement(
          "ACTION STEP",
          120,
          720,
          840,
          30,
          { fontSize: 13, fontWeight: 600, letterSpacing: 2, color: "#115E59", textTransform: "uppercase" },
          "text",
        ),
        createTextElement(
          "The immediate action to take for implementing this second tip",
          120,
          765,
          840,
          110,
          { fontSize: 22, fontWeight: 500, color: "#0F172A", lineHeight: 1.5 },
          "text",
        ),
        createTextElement(
          "2 of 7",
          80,
          1240,
          920,
          30,
          { fontSize: 15, fontWeight: 500, textAlign: "center", color: "#94A3B8" },
          "text",
        ),
      ],
    },
    {
      id: generateSlideId(),
      name: "Tip 3",
      order: 3,
      background: { type: "solid", color: "#F8FAFC" },
      elements: [
        createShapeElement("rounded-rectangle", 80, 200, 110, 110, "#0891B2", { borderRadius: 16 }),
        createTextElement(
          "03",
          80,
          222,
          110,
          70,
          { fontSize: 48, fontWeight: 800, textAlign: "center", color: "#FFFFFF" },
          "text",
        ),
        createTextElement(
          "Third Tip Title",
          220,
          222,
          780,
          70,
          { fontSize: 38, fontWeight: 700, color: "#0F172A" },
          "heading",
        ),
        createShapeElement("line", 80, 370, 920, 2, "#E2E8F0"),
        createTextElement(
          "Your third tip should build momentum. Keep the advice actionable with clear guidance that delivers measurable results.",
          80,
          440,
          920,
          160,
          { fontSize: 24, fontWeight: 400, lineHeight: 1.6, color: "#334155" },
          "body",
        ),
        createShapeElement("rounded-rectangle", 80, 680, 920, 220, "#FFFFFF", { borderRadius: 12 }),
        createTextElement(
          "ACTION STEP",
          120,
          720,
          840,
          30,
          { fontSize: 13, fontWeight: 600, letterSpacing: 2, color: "#115E59", textTransform: "uppercase" },
          "text",
        ),
        createTextElement(
          "Take this specific action to see immediate results from this tip",
          120,
          765,
          840,
          110,
          { fontSize: 22, fontWeight: 500, color: "#0F172A", lineHeight: 1.5 },
          "text",
        ),
        createTextElement(
          "3 of 7",
          80,
          1240,
          920,
          30,
          { fontSize: 15, fontWeight: 500, textAlign: "center", color: "#94A3B8" },
          "text",
        ),
      ],
    },
    {
      id: generateSlideId(),
      name: "Tip 4",
      order: 4,
      background: { type: "solid", color: "#F8FAFC" },
      elements: [
        createShapeElement("rounded-rectangle", 80, 200, 110, 110, "#1E40AF", { borderRadius: 16 }),
        createTextElement(
          "04",
          80,
          222,
          110,
          70,
          { fontSize: 48, fontWeight: 800, textAlign: "center", color: "#FFFFFF" },
          "text",
        ),
        createTextElement(
          "Fourth Tip Title",
          220,
          222,
          780,
          70,
          { fontSize: 38, fontWeight: 700, color: "#0F172A" },
          "heading",
        ),
        createShapeElement("line", 80, 370, 920, 2, "#E2E8F0"),
        createTextElement(
          "Tip four focuses on a distinct aspect that complements previous tips. Make it valuable and unique on its own merit.",
          80,
          440,
          920,
          160,
          { fontSize: 24, fontWeight: 400, lineHeight: 1.6, color: "#334155" },
          "body",
        ),
        createShapeElement("rounded-rectangle", 80, 680, 920, 220, "#FFFFFF", { borderRadius: 12 }),
        createTextElement(
          "ACTION STEP",
          120,
          720,
          840,
          30,
          { fontSize: 13, fontWeight: 600, letterSpacing: 2, color: "#115E59", textTransform: "uppercase" },
          "text",
        ),
        createTextElement(
          "Apply this strategy today to start seeing the benefits immediately",
          120,
          765,
          840,
          110,
          { fontSize: 22, fontWeight: 500, color: "#0F172A", lineHeight: 1.5 },
          "text",
        ),
        createTextElement(
          "4 of 7",
          80,
          1240,
          920,
          30,
          { fontSize: 15, fontWeight: 500, textAlign: "center", color: "#94A3B8" },
          "text",
        ),
      ],
    },
    {
      id: generateSlideId(),
      name: "Tip 5",
      order: 5,
      background: { type: "solid", color: "#F8FAFC" },
      elements: [
        createShapeElement("rounded-rectangle", 80, 200, 110, 110, "#0E7490", { borderRadius: 16 }),
        createTextElement(
          "05",
          80,
          222,
          110,
          70,
          { fontSize: 48, fontWeight: 800, textAlign: "center", color: "#FFFFFF" },
          "text",
        ),
        createTextElement(
          "Fifth Tip Title",
          220,
          222,
          780,
          70,
          { fontSize: 38, fontWeight: 700, color: "#0F172A" },
          "heading",
        ),
        createShapeElement("line", 80, 370, 920, 2, "#E2E8F0"),
        createTextElement(
          "Your fifth tip ties themes together. Show how all these tips work in harmony to create maximum impact and lasting results.",
          80,
          440,
          920,
          160,
          { fontSize: 24, fontWeight: 400, lineHeight: 1.6, color: "#334155" },
          "body",
        ),
        createShapeElement("rounded-rectangle", 80, 680, 920, 220, "#FFFFFF", { borderRadius: 12 }),
        createTextElement(
          "ACTION STEP",
          120,
          720,
          840,
          30,
          { fontSize: 13, fontWeight: 600, letterSpacing: 2, color: "#115E59", textTransform: "uppercase" },
          "text",
        ),
        createTextElement(
          "Start implementing this integrated approach in your workflow now",
          120,
          765,
          840,
          110,
          { fontSize: 22, fontWeight: 500, color: "#0F172A", lineHeight: 1.5 },
          "text",
        ),
        createTextElement(
          "5 of 7",
          80,
          1240,
          920,
          30,
          { fontSize: 15, fontWeight: 500, textAlign: "center", color: "#94A3B8" },
          "text",
        ),
      ],
    },
    {
      id: generateSlideId(),
      name: "Tip 6",
      order: 6,
      background: { type: "solid", color: "#F8FAFC" },
      elements: [
        createShapeElement("rounded-rectangle", 80, 200, 110, 110, "#1E3A8A", { borderRadius: 16 }),
        createTextElement(
          "06",
          80,
          222,
          110,
          70,
          { fontSize: 48, fontWeight: 800, textAlign: "center", color: "#FFFFFF" },
          "text",
        ),
        createTextElement(
          "Sixth Tip Title",
          220,
          222,
          780,
          70,
          { fontSize: 38, fontWeight: 700, color: "#0F172A" },
          "heading",
        ),
        createShapeElement("line", 80, 370, 920, 2, "#E2E8F0"),
        createTextElement(
          "The sixth tip adds an advanced layer. Share insider techniques or expert strategies that take results to the next level.",
          80,
          440,
          920,
          160,
          { fontSize: 24, fontWeight: 400, lineHeight: 1.6, color: "#334155" },
          "body",
        ),
        createShapeElement("rounded-rectangle", 80, 680, 920, 220, "#FFFFFF", { borderRadius: 12 }),
        createTextElement(
          "ACTION STEP",
          120,
          720,
          840,
          30,
          { fontSize: 13, fontWeight: 600, letterSpacing: 2, color: "#115E59", textTransform: "uppercase" },
          "text",
        ),
        createTextElement(
          "Level up with this advanced technique for exponential growth",
          120,
          765,
          840,
          110,
          { fontSize: 22, fontWeight: 500, color: "#0F172A", lineHeight: 1.5 },
          "text",
        ),
        createTextElement(
          "6 of 7",
          80,
          1240,
          920,
          30,
          { fontSize: 15, fontWeight: 500, textAlign: "center", color: "#94A3B8" },
          "text",
        ),
      ],
    },
    {
      id: generateSlideId(),
      name: "Tip 7",
      order: 7,
      background: { type: "solid", color: "#F8FAFC" },
      elements: [
        createShapeElement("rounded-rectangle", 80, 200, 110, 110, "#115E59", { borderRadius: 16 }),
        createTextElement(
          "07",
          80,
          222,
          110,
          70,
          { fontSize: 48, fontWeight: 800, textAlign: "center", color: "#FFFFFF" },
          "text",
        ),
        createTextElement(
          "Seventh Tip Title",
          220,
          222,
          780,
          70,
          { fontSize: 38, fontWeight: 700, color: "#0F172A" },
          "heading",
        ),
        createShapeElement("line", 80, 370, 920, 2, "#E2E8F0"),
        createTextElement(
          "End with your most powerful insight. This final tip brings everything together and inspires immediate, confident action.",
          80,
          440,
          920,
          160,
          { fontSize: 24, fontWeight: 400, lineHeight: 1.6, color: "#334155" },
          "body",
        ),
        createShapeElement("rounded-rectangle", 80, 680, 920, 220, "#FFFFFF", { borderRadius: 12 }),
        createTextElement(
          "ACTION STEP",
          120,
          720,
          840,
          30,
          { fontSize: 13, fontWeight: 600, letterSpacing: 2, color: "#115E59", textTransform: "uppercase" },
          "text",
        ),
        createTextElement(
          "Implement all 7 tips together for transformational results",
          120,
          765,
          840,
          110,
          { fontSize: 22, fontWeight: 500, color: "#0F172A", lineHeight: 1.5 },
          "text",
        ),
        createTextElement(
          "7 of 7",
          80,
          1240,
          920,
          30,
          { fontSize: 15, fontWeight: 500, textAlign: "center", color: "#94A3B8" },
          "text",
        ),
      ],
    },
    {
      id: generateSlideId(),
      name: "Outro",
      order: 8,
      background: {
        type: "gradient",
        gradient: { from: "#1E3A8A", to: "#115E59", direction: "to-br" },
      },
      elements: [
        createTextElement(
          "Thank you",
          80,
          540,
          920,
          70,
          { fontSize: 44, fontWeight: 700, textAlign: "center", color: "#FFFFFF" },
          "heading",
        ),
        createTextElement(
          "Like | Save | Share | Follow",
          80,
          630,
          920,
          50,
          { fontSize: 20, fontWeight: 400, textAlign: "center", color: "rgba(255,255,255,0.85)" },
          "text",
        ),
        createShapeElement("rounded-rectangle", 340, 740, 400, 60, "#FFFFFF", { borderRadius: 8 }),
        createTextElement(
          "@yourhandle",
          340,
          750,
          400,
          40,
          { fontSize: 24, fontWeight: 700, textAlign: "center", color: "#1E3A8A" },
          "text",
        ),
      ],
    },
  ],
}
