// ═══════════════════════════════════════════════════════════════════════════════
// Template: Trending Product
// Modern product showcase carousel with sleek design
// Perfect for product launches, features, and promotions
// ═══════════════════════════════════════════════════════════════════════════════

import type { CarouselTemplate } from "../carousel-designer-types"
import {
  createTextElement,
  createShapeElement,
  generateSlideId,
  createSwipeIndicator,
  SWIPE_TEXTS,
} from "./template-helpers"

export const trendingProductTemplate: CarouselTemplate = {
  id: "trending-product",
  name: "Trending Product",
  description: "Professional product showcase carousel for launches and promotions.",
  category: "trending-product",
  isPremium: false,
  isCustom: false,
  palette: {
    id: "charcoal-blue",
    name: "Charcoal Blue",
    category: "professional",
    colors: {
      primary: "#0F172A",
      secondary: "#1E3A8A",
      accent: "#3B82F6",
      background: "#0F172A",
      text: "#FFFFFF",
      textSecondary: "#94A3B8",
    },
    gradient: { from: "#0F172A", to: "#1E3A8A", direction: "to-br" },
  },
  size: "portrait",
  defaultFonts: {
    heading: "'Inter', sans-serif",
    body: "'Inter', sans-serif",
  },
  tags: ["product", "launch", "professional", "featured"],
  createdAt: Date.now(),
  updatedAt: Date.now(),
  slides: [
    // Slide 1: Cover - Product Introduction
    {
      id: generateSlideId(),
      name: "Cover",
      order: 0,
      background: {
        type: "gradient",
        color: "#0F172A",
        gradient: { from: "#0F172A", to: "#1E3A8A", direction: "to-br" },
      },
      elements: [
        createShapeElement("rounded-rectangle", 80, 420, 220, 50, "#3B82F6", { borderRadius: 25, zIndex: 1 }),
        createTextElement(
          "TRENDING NOW",
          80,
          428,
          220,
          35,
          { fontSize: 18, fontWeight: 700, textAlign: "center", color: "#FFFFFF" },
          "text",
        ),
        createTextElement(
          "The Game-Changing\nProduct You Need",
          80,
          540,
          920,
          160,
          { fontSize: 56, fontWeight: 700, textAlign: "center", color: "#FFFFFF", lineHeight: 1.1 },
          "heading",
        ),
        createTextElement(
          "Discover why thousands are switching",
          80,
          740,
          920,
          50,
          { fontSize: 24, fontWeight: 400, color: "#94A3B8", textAlign: "center" },
          "subheading",
        ),
        createShapeElement("line", 440, 820, 200, 3, "#3B82F6"),
        createTextElement(
          "10K+ Customers • 4.9 Rating",
          80,
          860,
          920,
          40,
          { fontSize: 18, fontWeight: 600, color: "#3B82F6", textAlign: "center" },
          "text",
        ),
        createSwipeIndicator(SWIPE_TEXTS.swipe, 780, 1180, 200, "#3B82F6", 18, "right"),
      ],
    },

    // Slide 2: Problem Statement
    {
      id: generateSlideId(),
      name: "The Problem",
      order: 1,
      background: {
        type: "gradient",
        color: "#1E293B",
        gradient: { from: "#1E293B", to: "#0F172A", direction: "to-b" },
      },
      elements: [
        createTextElement("01", 80, 180, 80, 40, { fontSize: 24, fontWeight: 700, color: "#3B82F6" }, "text"),
        createTextElement(
          "The Problem\nEveryone Faces",
          80,
          280,
          920,
          140,
          { fontSize: 48, fontWeight: 700, color: "#FFFFFF", lineHeight: 1.15, textAlign: "center" },
          "heading",
        ),
        createShapeElement("rounded-rectangle", 80, 480, 920, 480, "#1F2937", {
          borderRadius: 20,
          zIndex: 0,
        }),
        createShapeElement("circle", 130, 540, 10, 10, "#EF4444"),
        createTextElement(
          "Spending too much time on manual tasks",
          180,
          530,
          780,
          50,
          { fontSize: 22, fontWeight: 500, color: "#FFFFFF" },
          "text",
        ),
        createShapeElement("circle", 130, 640, 10, 10, "#EF4444"),
        createTextElement(
          "Inconsistent results every single time",
          180,
          630,
          780,
          50,
          { fontSize: 22, fontWeight: 500, color: "#FFFFFF" },
          "text",
        ),
        createShapeElement("circle", 130, 740, 10, 10, "#EF4444"),
        createTextElement(
          "Wasting money on solutions that fail",
          180,
          730,
          780,
          50,
          { fontSize: 22, fontWeight: 500, color: "#FFFFFF" },
          "text",
        ),
        createShapeElement("circle", 130, 840, 10, 10, "#EF4444"),
        createTextElement(
          "Missing growth opportunities",
          180,
          830,
          780,
          50,
          { fontSize: 22, fontWeight: 500, color: "#FFFFFF" },
          "text",
        ),
        createTextElement(
          "Sound familiar?",
          80,
          1020,
          920,
          40,
          { fontSize: 20, fontWeight: 500, color: "#94A3B8", textAlign: "center" },
          "text",
        ),
        createSwipeIndicator(SWIPE_TEXTS.next, 780, 1180, 200, "#3B82F6", 18, "right"),
      ],
    },

    // Slide 3: The Solution
    {
      id: generateSlideId(),
      name: "The Solution",
      order: 2,
      background: {
        type: "gradient",
        color: "#1E3A8A",
        gradient: { from: "#1E3A8A", to: "#3B82F6", direction: "to-br" },
      },
      elements: [
        createTextElement("02", 80, 180, 80, 40, { fontSize: 24, fontWeight: 700, color: "#FFFFFF" }, "text"),
        createTextElement(
          "Introducing\nThe Solution",
          80,
          480,
          920,
          200,
          { fontSize: 64, fontWeight: 700, textAlign: "center", color: "#FFFFFF", lineHeight: 1.1 },
          "heading",
        ),
        createTextElement(
          "Everything you need in one package",
          80,
          720,
          920,
          60,
          { fontSize: 24, fontWeight: 500, textAlign: "center", color: "rgba(255,255,255,0.9)" },
          "subheading",
        ),
        createSwipeIndicator(SWIPE_TEXTS.keepSwiping, 780, 1180, 200, "#FFFFFF", 18, "right"),
      ],
    },

    // Slide 4: Key Feature 1
    {
      id: generateSlideId(),
      name: "Feature 1",
      order: 3,
      background: {
        type: "gradient",
        color: "#0F172A",
        gradient: { from: "#0F172A", to: "#1E293B", direction: "to-b" },
      },
      elements: [
        createShapeElement("circle", 80, 200, 80, 80, "#3B82F6", { zIndex: 1 }),
        createTextElement(
          "01",
          80,
          215,
          80,
          55,
          { fontSize: 32, fontWeight: 700, textAlign: "center", color: "#FFFFFF" },
          "text",
        ),
        createTextElement(
          "Lightning Fast\nPerformance",
          80,
          340,
          920,
          120,
          { fontSize: 46, fontWeight: 700, color: "#FFFFFF", lineHeight: 1.15, textAlign: "center" },
          "heading",
        ),
        createShapeElement("rounded-rectangle", 80, 530, 920, 380, "#1F2937", {
          borderRadius: 20,
          zIndex: 0,
        }),
        createShapeElement("rounded-rectangle", 430, 590, 220, 60, "#3B82F6", { borderRadius: 10 }),
        createTextElement(
          "10× FASTER",
          430,
          602,
          220,
          40,
          { fontSize: 22, fontWeight: 700, textAlign: "center", color: "#FFFFFF" },
          "text",
        ),
        createTextElement(
          "10× faster than traditional solutions.\nSave hours every single week.",
          120,
          700,
          840,
          100,
          { fontSize: 22, fontWeight: 400, color: "#CBD5E1", textAlign: "center", lineHeight: 1.5 },
          "body",
        ),
        createTextElement(
          "Average time saved: 15 hours/week",
          80,
          1020,
          920,
          50,
          { fontSize: 20, fontWeight: 600, color: "#3B82F6", textAlign: "center" },
          "text",
        ),
        createSwipeIndicator(SWIPE_TEXTS.next, 780, 1180, 200, "#3B82F6", 18, "right"),
      ],
    },

    // Slide 5: Key Feature 2
    {
      id: generateSlideId(),
      name: "Feature 2",
      order: 4,
      background: {
        type: "gradient",
        color: "#1E293B",
        gradient: { from: "#1E293B", to: "#0F172A", direction: "to-b" },
      },
      elements: [
        createShapeElement("circle", 80, 200, 80, 80, "#1E3A8A", { zIndex: 1 }),
        createTextElement(
          "02",
          80,
          215,
          80,
          55,
          { fontSize: 32, fontWeight: 700, textAlign: "center", color: "#FFFFFF" },
          "text",
        ),
        createTextElement(
          "Seamless\nIntegration",
          80,
          340,
          920,
          120,
          { fontSize: 46, fontWeight: 700, color: "#FFFFFF", lineHeight: 1.15, textAlign: "center" },
          "heading",
        ),
        createShapeElement("rounded-rectangle", 80, 530, 920, 380, "#1F2937", {
          borderRadius: 20,
          zIndex: 0,
        }),
        createShapeElement("rounded-rectangle", 410, 590, 260, 60, "#1E3A8A", { borderRadius: 10 }),
        createTextElement(
          "CONNECTED",
          410,
          602,
          260,
          40,
          { fontSize: 22, fontWeight: 700, textAlign: "center", color: "#FFFFFF" },
          "text",
        ),
        createTextElement(
          "Works with all your favorite tools.\nNo complicated setup required.",
          120,
          700,
          840,
          100,
          { fontSize: 22, fontWeight: 400, color: "#CBD5E1", textAlign: "center", lineHeight: 1.5 },
          "body",
        ),
        createTextElement(
          "100+ integrations available",
          80,
          1020,
          920,
          50,
          { fontSize: 20, fontWeight: 600, color: "#3B82F6", textAlign: "center" },
          "text",
        ),
        createSwipeIndicator(SWIPE_TEXTS.next, 780, 1180, 200, "#3B82F6", 18, "right"),
      ],
    },

    // Slide 6: Key Feature 3
    {
      id: generateSlideId(),
      name: "Feature 3",
      order: 5,
      background: { type: "solid", color: "#0F172A" },
      elements: [
        createShapeElement("circle", 80, 200, 80, 80, "#3B82F6", { zIndex: 1 }),
        createTextElement(
          "03",
          80,
          215,
          80,
          55,
          { fontSize: 32, fontWeight: 700, textAlign: "center", color: "#FFFFFF" },
          "text",
        ),
        createTextElement(
          "Premium\nSupport 24/7",
          80,
          340,
          920,
          120,
          { fontSize: 46, fontWeight: 700, color: "#FFFFFF", lineHeight: 1.15, textAlign: "center" },
          "heading",
        ),
        createShapeElement("rounded-rectangle", 80, 530, 920, 380, "#1F2937", { borderRadius: 20, zIndex: 0 }),
        createShapeElement("rounded-rectangle", 435, 590, 210, 60, "#1E3A8A", { borderRadius: 10 }),
        createTextElement(
          "SUPPORT",
          435,
          602,
          210,
          40,
          { fontSize: 22, fontWeight: 700, textAlign: "center", color: "#FFFFFF" },
          "text",
        ),
        createTextElement(
          "Real humans, real help, anytime.\nAverage response: 5 minutes.",
          120,
          700,
          840,
          100,
          { fontSize: 22, fontWeight: 400, color: "#CBD5E1", textAlign: "center", lineHeight: 1.5 },
          "body",
        ),
        createTextElement(
          "98% satisfaction rate",
          80,
          1020,
          920,
          50,
          { fontSize: 20, fontWeight: 600, color: "#3B82F6", textAlign: "center" },
          "text",
        ),
        createSwipeIndicator(SWIPE_TEXTS.next, 780, 1180, 200, "#3B82F6", 18, "right"),
      ],
    },

    // Slide 7: Social Proof - Testimonial
    {
      id: generateSlideId(),
      name: "Testimonial",
      order: 6,
      background: {
        type: "gradient",
        color: "#1E293B",
        gradient: { from: "#1E293B", to: "#334155", direction: "to-br" },
      },
      elements: [
        createShapeElement("line", 100, 380, 5, 200, "#3B82F6"),
        createTextElement(
          "This product completely transformed how I work. I saved 20 hours in my first week alone!",
          160,
          400,
          820,
          220,
          { fontSize: 34, fontWeight: 600, color: "#FFFFFF", lineHeight: 1.35 },
          "body",
        ),
        createShapeElement("circle", 80, 700, 80, 80, "#3B82F6", { zIndex: 1 }),
        createTextElement(
          "JS",
          80,
          720,
          80,
          50,
          { fontSize: 28, fontWeight: 700, textAlign: "center", color: "#FFFFFF" },
          "text",
        ),
        createTextElement("John Smith", 180, 715, 600, 35, { fontSize: 24, fontWeight: 600, color: "#FFFFFF" }, "text"),
        createTextElement(
          "CEO, TechStart Inc.",
          180,
          755,
          600,
          30,
          { fontSize: 18, fontWeight: 400, color: "#94A3B8" },
          "text",
        ),
        createTextElement("5.0 Rating", 80, 860, 200, 50, { fontSize: 20, fontWeight: 600, color: "#3B82F6" }, "text"),
        createSwipeIndicator(SWIPE_TEXTS.next, 780, 1180, 200, "#3B82F6", 18, "right"),
      ],
    },

    // Slide 8: Results/Stats
    {
      id: generateSlideId(),
      name: "Results",
      order: 7,
      background: {
        type: "gradient",
        color: "#0F172A",
        gradient: { from: "#0F172A", to: "#1E293B", direction: "to-b" },
      },
      elements: [
        createTextElement(
          "Real Results",
          80,
          180,
          920,
          80,
          { fontSize: 44, fontWeight: 700, textAlign: "center", color: "#FFFFFF" },
          "heading",
        ),
        createShapeElement("rounded-rectangle", 80, 320, 440, 220, "#1E293B", { borderRadius: 16, zIndex: 0 }),
        createTextElement(
          "10K+",
          80,
          360,
          440,
          80,
          { fontSize: 52, fontWeight: 700, textAlign: "center", color: "#3B82F6" },
          "text",
        ),
        createTextElement(
          "Happy Customers",
          80,
          450,
          440,
          40,
          { fontSize: 18, fontWeight: 500, textAlign: "center", color: "#94A3B8" },
          "text",
        ),
        createShapeElement("rounded-rectangle", 560, 320, 440, 220, "#1E293B", { borderRadius: 16, zIndex: 0 }),
        createTextElement(
          "4.9",
          560,
          360,
          440,
          80,
          { fontSize: 52, fontWeight: 700, textAlign: "center", color: "#3B82F6" },
          "text",
        ),
        createTextElement(
          "Average Rating",
          560,
          450,
          440,
          40,
          { fontSize: 18, fontWeight: 500, textAlign: "center", color: "#94A3B8" },
          "text",
        ),
        createShapeElement("rounded-rectangle", 80, 580, 440, 220, "#1E293B", { borderRadius: 16, zIndex: 0 }),
        createTextElement(
          "300%",
          80,
          620,
          440,
          80,
          { fontSize: 52, fontWeight: 700, textAlign: "center", color: "#10B981" },
          "text",
        ),
        createTextElement(
          "ROI Increase",
          80,
          710,
          440,
          40,
          { fontSize: 18, fontWeight: 500, textAlign: "center", color: "#94A3B8" },
          "text",
        ),
        createShapeElement("rounded-rectangle", 560, 580, 440, 220, "#1E293B", { borderRadius: 16, zIndex: 0 }),
        createTextElement(
          "15hrs",
          560,
          620,
          440,
          80,
          { fontSize: 52, fontWeight: 700, textAlign: "center", color: "#10B981" },
          "text",
        ),
        createTextElement(
          "Saved Weekly",
          560,
          710,
          440,
          40,
          { fontSize: 18, fontWeight: 500, textAlign: "center", color: "#94A3B8" },
          "text",
        ),
        createTextElement(
          "Trusted by Fortune 500 teams",
          80,
          880,
          920,
          50,
          { fontSize: 20, fontWeight: 500, textAlign: "center", color: "#94A3B8" },
          "text",
        ),
        createSwipeIndicator(SWIPE_TEXTS.next, 780, 1180, 200, "#3B82F6", 18, "right"),
      ],
    },

    // Slide 9: Pricing/Offer
    {
      id: generateSlideId(),
      name: "Offer",
      order: 8,
      background: {
        type: "gradient",
        color: "#1E3A8A",
        gradient: { from: "#1E3A8A", to: "#3B82F6", direction: "to-br" },
      },
      elements: [
        createShapeElement("rounded-rectangle", 340, 180, 400, 50, "#FFFFFF", {
          borderRadius: 25,
          zIndex: 1,
          opacity: 0.2,
        }),
        createTextElement(
          "LIMITED TIME",
          340,
          188,
          400,
          35,
          { fontSize: 16, fontWeight: 700, textAlign: "center", color: "#FFFFFF" },
          "text",
        ),
        createTextElement(
          "Special Launch Price",
          80,
          300,
          920,
          80,
          { fontSize: 36, fontWeight: 600, textAlign: "center", color: "#FFFFFF" },
          "heading",
        ),
        createTextElement(
          "$49",
          80,
          420,
          920,
          150,
          { fontSize: 100, fontWeight: 800, textAlign: "center", color: "#FFFFFF" },
          "text",
        ),
        createTextElement(
          "was $199 — Save 75%",
          80,
          560,
          920,
          50,
          { fontSize: 22, fontWeight: 500, textAlign: "center", color: "rgba(255,255,255,0.9)" },
          "text",
        ),
        createShapeElement("rounded-rectangle", 180, 660, 720, 300, "rgba(255,255,255,0.1)", {
          borderRadius: 16,
          zIndex: 0,
        }),
        createTextElement(
          "WHAT'S INCLUDED",
          180,
          690,
          720,
          40,
          { fontSize: 16, fontWeight: 700, textAlign: "center", color: "#FFFFFF", letterSpacing: 2 },
          "text",
        ),
        createTextElement(
          "• Lifetime access\n• All premium features\n• Priority support\n• Future updates free",
          220,
          760,
          640,
          180,
          { fontSize: 20, fontWeight: 500, color: "#FFFFFF", lineHeight: 1.8 },
          "text",
        ),
        createSwipeIndicator(SWIPE_TEXTS.almostThere, 780, 1180, 200, "#FFFFFF", 18, "right"),
      ],
    },

    // Slide 10: CTA
    {
      id: generateSlideId(),
      name: "Call to Action",
      order: 9,
      background: {
        type: "gradient",
        color: "#0F172A",
        gradient: { from: "#0F172A", to: "#1E293B", direction: "to-b" },
      },
      elements: [
        createTextElement(
          "Ready to\nTransform?",
          80,
          400,
          920,
          180,
          { fontSize: 64, fontWeight: 700, textAlign: "center", color: "#FFFFFF", lineHeight: 1.1 },
          "heading",
        ),
        createShapeElement("rounded-rectangle", 240, 640, 600, 80, "#3B82F6", { borderRadius: 40, zIndex: 1 }),
        createTextElement(
          "Get Started Now →",
          240,
          655,
          600,
          55,
          { fontSize: 28, fontWeight: 700, textAlign: "center", color: "#FFFFFF" },
          "text",
        ),
        createTextElement(
          "Join 10,000+ customers today",
          80,
          770,
          920,
          50,
          { fontSize: 20, fontWeight: 400, textAlign: "center", color: "#94A3B8" },
          "text",
        ),
        createTextElement(
          "@yourhandle",
          80,
          920,
          920,
          40,
          { fontSize: 22, fontWeight: 600, textAlign: "center", color: "#3B82F6" },
          "text",
        ),
      ],
    },
  ],
}
