// ═══════════════════════════════════════════════════════════════════════════════
// Template: Trending Tools Weekly
// Weekly roundup of trending AI development tools with clean numbered layout
// ═══════════════════════════════════════════════════════════════════════════════

import type { CarouselTemplate } from "../carousel-designer-types"
import { generateSlideId, createTextElement, createShapeElement } from "./template-helpers"

export const trendingToolsWeekly: CarouselTemplate = {
  id: "trending-tools-weekly",
  name: "Trending Tools Weekly",
  description: "Weekly roundup of trending AI development tools with numbered badges and categories",
  category: "trending-product",
  isPremium: false,
  isCustom: false,
  palette: {
    id: "slate-gradient",
    name: "Slate Gradient",
    category: "dark",
    colors: {
      primary: "#60A5FA",
      secondary: "#3B82F6",
      accent: "#93C5FD",
      background: "#0F172A",
      text: "#FFFFFF",
      textSecondary: "#94A3B8",
    },
    gradient: { from: "#1E293B", to: "#0F172A", direction: "to-br" },
  },
  size: "portrait",
  defaultFonts: {
    heading: "'Inter', sans-serif",
    body: "'Inter', sans-serif",
  },
  tags: ["trending", "weekly", "tools", "numbered"],
  createdAt: Date.now(),
  updatedAt: Date.now(),
  slides: [
    // Cover Slide
    {
      id: generateSlideId(),
      name: "Cover",
      order: 0,
      background: {
        type: "gradient",
        gradient: { from: "#1E293B", to: "#0F172A", direction: "to-br" },
      },
      elements: [
        createTextElement(
          "TRENDING",
          80,
          380,
          920,
          90,
          {
            fontSize: 82,
            fontWeight: 900,
            color: "#FFFFFF",
            textAlign: "center",
            letterSpacing: 12,
          },
          "heading",
        ),
        createTextElement(
          "AI DEV TOOLS",
          80,
          490,
          920,
          80,
          {
            fontSize: 72,
            fontWeight: 800,
            color: "#60A5FA",
            textAlign: "center",
            letterSpacing: 8,
          },
          "subheading",
        ),
        createShapeElement("rounded-rectangle", 240, 620, 600, 100, "#1E40AF", { borderRadius: 16, opacity: 0.3 }),
        createTextElement(
          "5 HIGH IMPACTING",
          240,
          655,
          600,
          50,
          {
            fontSize: 32,
            fontWeight: 700,
            color: "#FFFFFF",
            textAlign: "center",
            letterSpacing: 4,
          },
          "text",
        ),
        createTextElement(
          "#AINATIVEDEVLANDSCAPE",
          80,
          790,
          920,
          28,
          {
            fontSize: 18,
            fontWeight: 600,
            color: "#94A3B8",
            textAlign: "center",
            letterSpacing: 3,
          },
          "text",
        ),
      ],
    },
    // Tool 1: Antigravity
    {
      id: generateSlideId(),
      name: "Tool 1 - Antigravity",
      order: 1,
      background: {
        type: "gradient",
        gradient: { from: "#1E293B", to: "#0F172A", direction: "to-br" },
      },
      elements: [
        createShapeElement("rounded-rectangle", 80, 100, 140, 140, "#1E40AF", { borderRadius: 24 }),
        createTextElement(
          "1",
          80,
          135,
          140,
          90,
          {
            fontSize: 82,
            fontWeight: 900,
            color: "#FFFFFF",
            textAlign: "center",
          },
          "text",
        ),
        createTextElement(
          "ANTIGRAVITY",
          80,
          280,
          920,
          70,
          {
            fontSize: 58,
            fontWeight: 800,
            color: "#FFFFFF",
            letterSpacing: 2,
          },
          "heading",
        ),
        createShapeElement("rounded-rectangle", 80, 360, 140, 48, "#1E40AF", { borderRadius: 24 }),
        createTextElement(
          "IDE",
          80,
          372,
          140,
          36,
          {
            fontSize: 20,
            fontWeight: 700,
            color: "#FFFFFF",
            textAlign: "center",
            letterSpacing: 3,
          },
          "text",
        ),
        createShapeElement("rounded-rectangle", 80, 450, 920, 340, "#1E293B", { borderRadius: 20 }),
        createTextElement(
          "Google Antigravity is an agentic development platform, evolving the IDE into the agent-first era.\n\nFEATURES:\n• Agent-first development environment\n• Deep agent autonomy with direct access\n• Multi-agent orchestration capabilities\n• End-to-end task execution",
          140,
          510,
          840,
          280,
          {
            fontSize: 24,
            fontWeight: 400,
            color: "#E2E8F0",
            lineHeight: 1.75,
          },
          "text",
        ),
        createShapeElement("rounded-rectangle", 80, 830, 920, 90, "#0F172A", { borderRadius: 16 }),
        createTextElement(
          "https://antigravity.google/",
          80,
          863,
          920,
          34,
          {
            fontSize: 22,
            fontWeight: 600,
            color: "#60A5FA",
            textAlign: "center",
          },
          "text",
        ),
      ],
    },
    // Tool 2: Beads
    {
      id: generateSlideId(),
      name: "Tool 2 - Beads",
      order: 2,
      background: {
        type: "gradient",
        gradient: { from: "#1E293B", to: "#0F172A", direction: "to-br" },
      },
      elements: [
        createShapeElement("rounded-rectangle", 80, 100, 140, 140, "#1E40AF", { borderRadius: 24 }),
        createTextElement(
          "2",
          80,
          135,
          140,
          90,
          {
            fontSize: 82,
            fontWeight: 900,
            color: "#FFFFFF",
            textAlign: "center",
          },
          "text",
        ),
        createTextElement(
          "BEADS",
          80,
          280,
          920,
          70,
          {
            fontSize: 58,
            fontWeight: 800,
            color: "#FFFFFF",
            letterSpacing: 2,
          },
          "heading",
        ),
        createShapeElement("rounded-rectangle", 80, 360, 180, 48, "#1E40AF", { borderRadius: 24 }),
        createTextElement(
          "MEMORY",
          80,
          372,
          180,
          36,
          {
            fontSize: 20,
            fontWeight: 700,
            color: "#FFFFFF",
            textAlign: "center",
            letterSpacing: 3,
          },
          "text",
        ),
        createShapeElement("rounded-rectangle", 80, 450, 920, 340, "#1E293B", { borderRadius: 20 }),
        createTextElement(
          "AI memory system for coding agents with git-backed issue tracking.\n\nFEATURES:\n• Lightweight memory system\n• Graph-based issue tracker\n• Git integration for persistence\n• Context retention across sessions",
          140,
          510,
          840,
          280,
          {
            fontSize: 24,
            fontWeight: 400,
            color: "#E2E8F0",
            lineHeight: 1.75,
          },
          "text",
        ),
        createShapeElement("rounded-rectangle", 80, 830, 920, 90, "#0F172A", { borderRadius: 16 }),
        createTextElement(
          "https://github.com/steveyegge/beads",
          80,
          863,
          920,
          34,
          {
            fontSize: 22,
            fontWeight: 600,
            color: "#60A5FA",
            textAlign: "center",
          },
          "text",
        ),
      ],
    },
    // Tool 3: LLM Council
    {
      id: generateSlideId(),
      name: "Tool 3 - LLM Council",
      order: 3,
      background: {
        type: "gradient",
        gradient: { from: "#1E293B", to: "#0F172A", direction: "to-br" },
      },
      elements: [
        createShapeElement("rounded-rectangle", 80, 100, 140, 140, "#1E40AF", { borderRadius: 24 }),
        createTextElement(
          "3",
          80,
          135,
          140,
          90,
          {
            fontSize: 82,
            fontWeight: 900,
            color: "#FFFFFF",
            textAlign: "center",
          },
          "text",
        ),
        createTextElement(
          "LLM COUNCIL",
          80,
          280,
          920,
          70,
          {
            fontSize: 58,
            fontWeight: 800,
            color: "#FFFFFF",
            letterSpacing: 2,
          },
          "heading",
        ),
        createShapeElement("rounded-rectangle", 80, 360, 300, 48, "#1E40AF", { borderRadius: 24 }),
        createTextElement(
          "AUTONOMOUS AGENT",
          80,
          372,
          300,
          36,
          {
            fontSize: 20,
            fontWeight: 700,
            color: "#FFFFFF",
            textAlign: "center",
            letterSpacing: 3,
          },
          "text",
        ),
        createShapeElement("rounded-rectangle", 80, 450, 920, 340, "#1E293B", { borderRadius: 20 }),
        createTextElement(
          "LLM Council works together to answer your hardest questions. A multi-model consensus.\n\nFEATURES:\n• Multi-model consensus system\n• Created by Andrej Karpathy\n• Collaborative AI decision making\n• Enhanced accuracy through voting",
          140,
          510,
          840,
          280,
          {
            fontSize: 24,
            fontWeight: 400,
            color: "#E2E8F0",
            lineHeight: 1.75,
          },
          "text",
        ),
        createShapeElement("rounded-rectangle", 80, 830, 920, 90, "#0F172A", { borderRadius: 16 }),
        createTextElement(
          "https://github.com/karpathy/llm-council",
          80,
          863,
          920,
          34,
          {
            fontSize: 22,
            fontWeight: 600,
            color: "#60A5FA",
            textAlign: "center",
          },
          "text",
        ),
      ],
    },
    // Tool 4: Sniffr.ai
    {
      id: generateSlideId(),
      name: "Tool 4 - Sniffr.ai",
      order: 4,
      background: {
        type: "gradient",
        gradient: { from: "#1E293B", to: "#0F172A", direction: "to-br" },
      },
      elements: [
        createShapeElement("rounded-rectangle", 80, 100, 140, 140, "#1E40AF", { borderRadius: 24 }),
        createTextElement(
          "4",
          80,
          135,
          140,
          90,
          {
            fontSize: 82,
            fontWeight: 900,
            color: "#FFFFFF",
            textAlign: "center",
          },
          "text",
        ),
        createTextElement(
          "SNIFFR.AI",
          80,
          280,
          920,
          70,
          {
            fontSize: 58,
            fontWeight: 800,
            color: "#FFFFFF",
            letterSpacing: 2,
          },
          "heading",
        ),
        createShapeElement("rounded-rectangle", 80, 360, 160, 48, "#1E40AF", { borderRadius: 24 }),
        createTextElement(
          "REVIEW",
          80,
          372,
          160,
          36,
          {
            fontSize: 20,
            fontWeight: 700,
            color: "#FFFFFF",
            textAlign: "center",
            letterSpacing: 3,
          },
          "text",
        ),
        createShapeElement("rounded-rectangle", 80, 450, 920, 340, "#1E293B", { borderRadius: 20 }),
        createTextElement(
          "Sniffr.ai is an AI-powered code and requirement review platform that helps engineering teams.\n\nFEATURES:\n• Detect issues early in development\n• Improve release accuracy\n• Accelerate delivery cycles\n• Automated code quality checks",
          140,
          510,
          840,
          280,
          {
            fontSize: 24,
            fontWeight: 400,
            color: "#E2E8F0",
            lineHeight: 1.75,
          },
          "text",
        ),
        createShapeElement("rounded-rectangle", 80, 830, 920, 90, "#0F172A", { borderRadius: 16 }),
        createTextElement(
          "https://sniffr.ai/",
          80,
          863,
          920,
          34,
          {
            fontSize: 22,
            fontWeight: 600,
            color: "#60A5FA",
            textAlign: "center",
          },
          "text",
        ),
      ],
    },
    // Tool 5: Mux
    {
      id: generateSlideId(),
      name: "Tool 5 - Mux",
      order: 5,
      background: {
        type: "gradient",
        gradient: { from: "#1E293B", to: "#0F172A", direction: "to-br" },
      },
      elements: [
        createShapeElement("rounded-rectangle", 80, 100, 140, 140, "#1E40AF", { borderRadius: 24 }),
        createTextElement(
          "5",
          80,
          135,
          140,
          90,
          {
            fontSize: 82,
            fontWeight: 900,
            color: "#FFFFFF",
            textAlign: "center",
          },
          "text",
        ),
        createTextElement(
          "MUX",
          80,
          280,
          920,
          70,
          {
            fontSize: 58,
            fontWeight: 800,
            color: "#FFFFFF",
            letterSpacing: 2,
          },
          "heading",
        ),
        createShapeElement("rounded-rectangle", 80, 360, 280, 48, "#1E40AF", { borderRadius: 24 }),
        createTextElement(
          "ORCHESTRATION",
          80,
          372,
          280,
          36,
          {
            fontSize: 20,
            fontWeight: 700,
            color: "#FFFFFF",
            textAlign: "center",
            letterSpacing: 3,
          },
          "text",
        ),
        createShapeElement("rounded-rectangle", 80, 450, 920, 340, "#1E293B", { borderRadius: 20 }),
        createTextElement(
          "Coding Agent Multiplexer - a cross-platform desktop application for AI-assisted development.\n\nFEATURES:\n• Isolated workspace management\n• Multi-agent coordination\n• Cross-platform compatibility\n• Desktop-native experience",
          140,
          510,
          840,
          280,
          {
            fontSize: 24,
            fontWeight: 400,
            color: "#E2E8F0",
            lineHeight: 1.75,
          },
          "text",
        ),
        createShapeElement("rounded-rectangle", 80, 830, 920, 90, "#0F172A", { borderRadius: 16 }),
        createTextElement(
          "https://github.com/coder/mux",
          80,
          863,
          920,
          34,
          {
            fontSize: 22,
            fontWeight: 600,
            color: "#60A5FA",
            textAlign: "center",
          },
          "text",
        ),
      ],
    },
    // Outro Slide
    {
      id: generateSlideId(),
      name: "Outro",
      order: 6,
      background: {
        type: "gradient",
        gradient: { from: "#1E293B", to: "#0F172A", direction: "to-br" },
      },
      elements: [
        createTextElement(
          "The AI NATIVE",
          80,
          350,
          920,
          70,
          {
            fontSize: 62,
            fontWeight: 800,
            color: "#FFFFFF",
            textAlign: "center",
            letterSpacing: 4,
          },
          "heading",
        ),
        createTextElement(
          "Dev Landscape",
          80,
          440,
          920,
          80,
          {
            fontSize: 72,
            fontWeight: 900,
            color: "#60A5FA",
            textAlign: "center",
            letterSpacing: 6,
          },
          "subheading",
        ),
        createTextElement(
          "is GROWING",
          80,
          540,
          920,
          60,
          {
            fontSize: 52,
            fontWeight: 700,
            color: "#FFFFFF",
            textAlign: "center",
            letterSpacing: 3,
          },
          "text",
        ),
        createShapeElement("rounded-rectangle", 240, 640, 600, 120, "#1E40AF", { borderRadius: 16, opacity: 0.3 }),
        createTextElement(
          "NEW TOOLS DROP\nEVERY WEEK",
          240,
          668,
          600,
          84,
          {
            fontSize: 32,
            fontWeight: 700,
            color: "#FFFFFF",
            textAlign: "center",
            lineHeight: 1.5,
          },
          "text",
        ),
        createTextElement(
          "HTTPS://AINATIVEDEV.IO/LANDSCAPE",
          80,
          850,
          920,
          30,
          {
            fontSize: 20,
            fontWeight: 600,
            color: "#60A5FA",
            textAlign: "center",
            letterSpacing: 2,
          },
          "text",
        ),
      ],
    },
  ],
}
