// Template: Vibrant Dark Mode - Bold neon colors on dark background
import type { CarouselTemplate } from "../carousel-designer-types"
import { VIBRANT_PALETTES } from "../carousel-designer-types"
import { generateSlideId, createTextElement, createShapeElement } from "./template-helpers"

export const vibrantDarkModeTemplate: CarouselTemplate = {
  id: "vibrant-dark-mode",
  name: "Vibrant Dark Mode",
  description: "Bold neon colors on dark background for eye-catching presentations",
  category: "vibrant",
  isPremium: false,
  isCustom: false,
  palette: VIBRANT_PALETTES.find((p) => p.id === "neon-nights") || VIBRANT_PALETTES[0],
  size: "portrait",
  defaultFonts: { heading: "'Inter', sans-serif", body: "'Inter', sans-serif" },
  tags: ["dark", "vibrant", "neon", "bold", "creative"],
  createdAt: Date.now(),
  updatedAt: Date.now(),
  slides: [
    {
      id: generateSlideId(),
      name: "Cover",
      order: 0,
      background: { type: "solid", color: "#0A0A0F" },
      elements: [
        createShapeElement("rectangle", 0, 0, 1080, 8, "#F472B6"),
        createShapeElement("circle", 700, -100, 500, 500, "#8B5CF6", { opacity: 0.15 }),
        createTextElement(
          "CREATIVE SERIES",
          80,
          200,
          280,
          50,
          { fontSize: 18, fontWeight: 700, color: "#F472B6", letterSpacing: 4 },
          "text",
        ),
        createTextElement(
          "Unlock Your\nCreative\nPotential",
          80,
          280,
          920,
          320,
          { fontSize: 76, fontWeight: 800, color: "#FFFFFF", lineHeight: 1.05 },
          "heading",
        ),
        createTextElement(
          "5 proven techniques to supercharge your creative output and stand out from the crowd",
          80,
          640,
          920,
          100,
          { fontSize: 24, fontWeight: 400, color: "#A1A1AA", lineHeight: 1.5 },
          "text",
        ),
        createShapeElement("rounded-rectangle", 80, 780, 280, 60, "#8B5CF6", { borderRadius: 30 }),
        createTextElement(
          "Swipe to Learn",
          80,
          795,
          280,
          40,
          { fontSize: 20, fontWeight: 600, color: "#FFFFFF", textAlign: "center" },
          "text",
        ),
        createShapeElement("rectangle", 0, 1250, 1080, 100, "#18181B"),
        createTextElement("Your Name", 80, 1275, 500, 50, { fontSize: 20, fontWeight: 600, color: "#FFFFFF" }, "text"),
        createTextElement(
          "@yourhandle",
          580,
          1275,
          420,
          50,
          { fontSize: 20, fontWeight: 500, color: "#F472B6", textAlign: "right" },
          "text",
        ),
      ],
    },
    {
      id: generateSlideId(),
      name: "Point 1",
      order: 1,
      background: { type: "solid", color: "#0A0A0F" },
      elements: [
        createShapeElement("rectangle", 0, 0, 8, 1350, "#8B5CF6"),
        createShapeElement("rounded-rectangle", 80, 80, 120, 120, "#8B5CF6", { borderRadius: 20 }),
        createTextElement(
          "01",
          80,
          100,
          120,
          100,
          { fontSize: 56, fontWeight: 800, color: "#FFFFFF", textAlign: "center" },
          "text",
        ),
        createTextElement(
          "Embrace Constraints",
          230,
          110,
          770,
          80,
          { fontSize: 36, fontWeight: 700, color: "#FFFFFF" },
          "heading",
        ),
        createTextElement(
          "Limitations fuel creativity. Set boundaries on time, tools, or resources to force innovative thinking.",
          80,
          260,
          920,
          200,
          { fontSize: 32, fontWeight: 500, color: "#E4E4E7", lineHeight: 1.5 },
          "text",
        ),
        createShapeElement("rounded-rectangle", 80, 500, 920, 300, "#18181B", { borderRadius: 16 }),
        createShapeElement("rectangle", 80, 500, 8, 300, "#F472B6", { borderRadius: 4 }),
        createTextElement(
          "EXAMPLE",
          120,
          530,
          200,
          40,
          { fontSize: 14, fontWeight: 700, color: "#F472B6", letterSpacing: 3 },
          "text",
        ),
        createTextElement(
          "Give yourself only 30 minutes to brainstorm. You will be amazed at how quickly ideas flow when there is pressure.",
          120,
          580,
          840,
          180,
          { fontSize: 22, fontWeight: 400, color: "#A1A1AA", lineHeight: 1.6 },
          "text",
        ),
        createTextElement(
          "Constraints are not obstacles - they are creative catalysts.",
          80,
          860,
          920,
          80,
          { fontSize: 24, fontWeight: 600, color: "#8B5CF6", lineHeight: 1.4 },
          "text",
        ),
      ],
    },
    {
      id: generateSlideId(),
      name: "Point 2",
      order: 2,
      background: { type: "solid", color: "#0A0A0F" },
      elements: [
        createShapeElement("rectangle", 0, 0, 8, 1350, "#F472B6"),
        createShapeElement("rounded-rectangle", 80, 80, 120, 120, "#F472B6", { borderRadius: 20 }),
        createTextElement(
          "02",
          80,
          100,
          120,
          100,
          { fontSize: 56, fontWeight: 800, color: "#FFFFFF", textAlign: "center" },
          "text",
        ),
        createTextElement(
          "Cross-Pollinate Ideas",
          230,
          110,
          770,
          80,
          { fontSize: 36, fontWeight: 700, color: "#FFFFFF" },
          "heading",
        ),
        createTextElement(
          "The best ideas come from combining concepts from different fields. Be curious about everything.",
          80,
          260,
          920,
          200,
          { fontSize: 32, fontWeight: 500, color: "#E4E4E7", lineHeight: 1.5 },
          "text",
        ),
        createShapeElement("rounded-rectangle", 80, 500, 440, 180, "#18181B", { borderRadius: 16 }),
        createTextElement(
          "Read Widely",
          110,
          530,
          380,
          50,
          { fontSize: 24, fontWeight: 600, color: "#FFFFFF" },
          "heading",
        ),
        createTextElement(
          "Explore topics outside your expertise",
          110,
          580,
          380,
          80,
          { fontSize: 18, fontWeight: 400, color: "#A1A1AA", lineHeight: 1.4 },
          "text",
        ),
        createShapeElement("rounded-rectangle", 560, 500, 440, 180, "#18181B", { borderRadius: 16 }),
        createTextElement(
          "Network Diversely",
          590,
          530,
          380,
          50,
          { fontSize: 24, fontWeight: 600, color: "#FFFFFF" },
          "heading",
        ),
        createTextElement(
          "Connect with people from different industries",
          590,
          580,
          380,
          80,
          { fontSize: 18, fontWeight: 400, color: "#A1A1AA", lineHeight: 1.4 },
          "text",
        ),
        createTextElement(
          '"Creativity is just connecting things." - Steve Jobs',
          80,
          750,
          920,
          150,
          { fontSize: 28, fontWeight: 500, color: "#F472B6", textAlign: "center", lineHeight: 1.4 },
          "text",
        ),
      ],
    },
    {
      id: generateSlideId(),
      name: "Point 3",
      order: 3,
      background: { type: "solid", color: "#0A0A0F" },
      elements: [
        createShapeElement("rectangle", 0, 0, 8, 1350, "#10B981"),
        createShapeElement("rounded-rectangle", 80, 80, 120, 120, "#10B981", { borderRadius: 20 }),
        createTextElement(
          "03",
          80,
          100,
          120,
          100,
          { fontSize: 56, fontWeight: 800, color: "#FFFFFF", textAlign: "center" },
          "text",
        ),
        createTextElement(
          "Practice Daily Creation",
          230,
          110,
          770,
          80,
          { fontSize: 36, fontWeight: 700, color: "#FFFFFF" },
          "heading",
        ),
        createTextElement(
          "Creativity is a muscle. The more you exercise it, the stronger it gets. Make creation a daily habit.",
          80,
          260,
          920,
          200,
          { fontSize: 32, fontWeight: 500, color: "#E4E4E7", lineHeight: 1.5 },
          "text",
        ),
        createShapeElement("rounded-rectangle", 80, 500, 920, 350, "#18181B", { borderRadius: 16 }),
        createTextElement(
          "Daily Creative Routine",
          110,
          530,
          860,
          50,
          { fontSize: 24, fontWeight: 600, color: "#10B981" },
          "heading",
        ),
        createTextElement(
          "Morning: 15 min freewriting or sketching",
          110,
          590,
          860,
          50,
          { fontSize: 20, fontWeight: 400, color: "#E4E4E7" },
          "text",
        ),
        createTextElement(
          "Afternoon: Capture 3 interesting observations",
          110,
          650,
          860,
          50,
          { fontSize: 20, fontWeight: 400, color: "#E4E4E7" },
          "text",
        ),
        createTextElement(
          "Evening: Review and connect ideas",
          110,
          710,
          860,
          50,
          { fontSize: 20, fontWeight: 400, color: "#E4E4E7" },
          "text",
        ),
        createTextElement(
          "Weekly: Create one finished piece",
          110,
          770,
          860,
          50,
          { fontSize: 20, fontWeight: 400, color: "#E4E4E7" },
          "text",
        ),
      ],
    },
    {
      id: generateSlideId(),
      name: "CTA",
      order: 4,
      background: { type: "solid", color: "#0A0A0F" },
      elements: [
        createShapeElement("circle", -100, 400, 400, 400, "#8B5CF6", { opacity: 0.1 }),
        createShapeElement("circle", 780, 700, 400, 400, "#F472B6", { opacity: 0.1 }),
        createTextElement(
          "Ready to Create?",
          80,
          280,
          920,
          60,
          { fontSize: 28, fontWeight: 500, color: "#F472B6", textAlign: "center" },
          "text",
        ),
        createTextElement(
          "Start Your\nCreative Journey\nToday",
          80,
          360,
          920,
          200,
          { fontSize: 64, fontWeight: 800, color: "#FFFFFF", textAlign: "center", lineHeight: 1.1 },
          "heading",
        ),
        createTextElement(
          "Follow for more tips on creativity,\nproductivity, and personal growth",
          80,
          600,
          920,
          100,
          { fontSize: 24, fontWeight: 400, color: "#A1A1AA", textAlign: "center", lineHeight: 1.5 },
          "text",
        ),
        createShapeElement("rounded-rectangle", 290, 750, 500, 70, "#8B5CF6", { borderRadius: 35 }),
        createTextElement(
          "Save This Post",
          290,
          765,
          500,
          50,
          { fontSize: 24, fontWeight: 600, color: "#FFFFFF", textAlign: "center" },
          "text",
        ),
        createShapeElement("rectangle", 0, 1250, 1080, 100, "#18181B"),
        createTextElement("Your Name", 80, 1275, 500, 50, { fontSize: 20, fontWeight: 600, color: "#FFFFFF" }, "text"),
        createTextElement(
          "@yourhandle",
          580,
          1275,
          420,
          50,
          { fontSize: 20, fontWeight: 500, color: "#F472B6", textAlign: "right" },
          "text",
        ),
      ],
    },
  ],
}
